#DEFINE LANG_ScopeOrders                 "Scope Orders"
#DEFINE LANG_Options                     "O\<ptions"
#DEFINE LANG_OptionCustomerInquire       "Customer \<Inquire"
#DEFINE LANG_OptionCustomerNotepad       "Customer \<Notepad"
#DEFINE LANG_OptionAgingSummary          "\<Aging Summary"
#DEFINE LANG_OptionStyleInquire          "\<Style Inquire"
#DEFINE LANG_OptionLineNotepad           "\<Line Notepad"
#DEFINE LANG_OptionCopyLine              "\<Copy Line"
#DEFINE LANG_OptionPasteLine             "\<Paste Line"
#DEFINE LANG_OptionAddPacks              "Add Pac\<ks"
#DEFINE LANG_OptionZoomInvoiceLines      "\<Zoom Invoice Lines"
#DEFINE LANG_OptionRefreshComm           "\<Refresh Invoice Sales Rep. Commission"
#DEFINE LANG_OptionSessionDefaults       "Session \<Defaults"
#DEFINE LANG_OptionBatchSummary          "\<Batch Summary"
#DEFINE LANG_OptionScopeOrders           "Scope \<Orders"
#DEFINE LANG_OptionChangeAll             "\<Global Changes"    
#DEFINE LANG_CannotShip                  "Cannot Ship."
#DEFINE LANG_ComputePacked               "Computing packed quantity..."
#DEFINE LANG_GSTTaxName                  "G.S.T. Tax"
#DEFINE LANG_Account                     "Account"
#DEFINE LANG_Store                       "Store"
#DEFINE LANG_PikTkt                      "PikTkt"
#DEFINE LANG_Order                       "Order#"
#DEFINE LANG_Complete                    "Complete"
#DEFINE LANG_PikDate                     "PikDate"
#DEFINE LANG_AccountName                 "Account Name"
#DEFINE LANG_PickTickets                 "Pick Tickets"
#DEFINE LANG_Name                        "Name"
#DEFINE LANG_Phone                       "Phone #..."
#DEFINE LANG_Buyer                       "Buyer"
#DEFINE LANG_Rep                         "Rep"
#DEFINE LANG_Locations                   "Locations for Customer: "
#DEFINE LANG_LabelCOnfiguration          "Configuration"
#DEFINE LANG_LabelDyelot                 "Dyelot"
#DEFINE LANG_MsgCOnfiguration            "Configurations"
#DEFINE LANG_MsgDyelot                   "Dyelots"
#DEFINE LANG_OptionReplaceConfig         "Replace Configuration"
*************
#DEFINE LANG_COLOrder            "Order#"
#DEFINE LANG_COLStatus           "Status"
#DEFINE LANG_COLAccount          "Acct"
#DEFINE LANG_COLStore            "Store"
#DEFINE LANG_COLname             "Name"
#DEFINE LANG_COLDept             "Department"
#DEFINE LANG_COLMultiPo          "Multi PO"
#DEFINE LANG_COLCustPo           "Cust. P.O#"
#DEFINE LANG_COLBulk             "Bulk"
#DEFINE LANG_COLMulti            "Multi"
#DEFINE LANG_COLcFacCode         "Factor Code"
#DEFINE LANG_COLRep1             "Sales Rep1"
#DEFINE LANG_COLComm1            "Commission 1"
#DEFINE LANG_COLRep2             "Sales Rep2"
#DEFINE LANG_COLComm2            "Commission 2"
#DEFINE LANG_COLOpen             "Open.Qty."
#DEFINE LANG_COLOpenAmt          "Open.Amt."
#DEFINE LANG_COLShip             "Ship.Qty."
#DEFINE LANG_COLShipAmt          "Ship.Amt."
#DEFINE LANG_COLBook             "Book.Qty."
#DEFINE LANG_COLBookAmt          "Book.Amt."
#DEFINE LANG_COLCancel           "Cancel.Qty."
#DEFINE LANG_COLCancelAmt        "Cancel.Amt."
#DEFINE LANG_COLEntered          "Entered"
#DEFINE LANG_COLStart            "Start"
#DEFINE LANG_COLComplete         "Complete"
#DEFINE LANG_COLCancelled        "Cancelled"
#DEFINE LANG_COLDisc             "Disc."
#DEFINE LANG_COLcWareCode        "Warehouse"
#DEFINE LANG_COLcAdd_User        "User"
#DEFINE LANG_COLdAdd_Date        "Date"
#DEFINE LANG_COLSeason           "Season"
#DEFINE LANG_COLDivision         "Division"
#DEFINE LANG_COLShipVia          "ShipVia"
#DEFINE LANG_COLNote1            "Notes 1"
#DEFINE LANG_COLNote2            "Notes 2"
#DEFINE LANG_COLCurrCode         "Currency"
#DEFINE LANG_COLExRate           "Ex. Rate"
#DEFINE LANG_COLCurrUnit         "Unit"
#DEFINE LANG_OrderBrowse         "Orders"
#DEFINE LANG_NoOrdersFound       "orders matching the"