#DEFINE LANG_ACCTNO	                  "Acct#"
#DEFINE LANG_NAME                         "Name"
#DEFINE LANG_STADDRESS                    "ST Address"
#DEFINE LANG_ST                           "ST"
#DEFINE LANG_STCity                       "ST City"
#DEFINE LANG_STState                      "ST State"
#DEFINE LANG_STZip                        "ST Zip"
#DEFINE LANG_BTAddress                    "BT Address"
#DEFINE LANG_BT                           "BT"
#DEFINE LANG_BTCity                       "BT City"
#DEFINE LANG_BTState                      "BT State"
#DEFINE LANG_BTZIP                        "BT Zip"
#DEFINE LANG_Phone				"Phone#"
#DEFINE LANG_Buyer          		      "Buyer"
#DEFINE LANG_SalesRep            		"Sales Rep."
#DEFINE LANG_Balance                      "Balance"