#DEFINE LANG_MAMATST_ItemSort          "Item"
#DEFINE LANG_MAMATST_ItemVendor        "Vendor"
#DEFINE LANG_MAMATST_Summary           "Summary"
#DEFINE LANG_MAMATST_Detail            "Detail"
#DEFINE LANG_MAMATST_ReportTitle       "Material Master List For Style"
#DEFINE LANG_MAMATST_NoRecord          "NO RECORDS SELECTED FOR REPORT!"