* N000862 ,1 Thabet Handle globalization issues [Start]
#DEFINE lang_Collecting_the_cost_sheet 'Collecting the cost sheet information for Style : '
#DEFINE lang_Checking_for_styles_useing_material 'Checking for styles useing material : '
#DEFINE lang_Calculating_requirements_for_Fabric 'Calculating requirements for Fabric: '
#DEFINE lang_Generate_po 'Generate P/Os...'
#DEFINE lang_Updating_projections_to_the_style_master_file 'Updating projections to the style master file ...'
#DEFINE lang_Collecting_data_for_Style 'Collecting data for Style : '
#DEFINE lang_Collecting_data_for_Fabric 'Collecting data for Fabric : '
#DEFINE LANG_Projected 'Projected'
#DEFINE LANG_Open 'Open'
#DEFINE LANG_Hold 'Hold'
#DEFINE LANG_Style_Component 'LANG_Style_Component'
#DEFINE LANG_Fabric 'Fabric'
#DEFINE LANG_Trim 'Trim'
#DEFINE LANG_Item_Type 'Item Type'
#DEFINE LANG_Item 'Item'
#DEFINE LANG_Vendor 'Vendor'
#DEFINE LANG_Delivry 'Delivry'
#DEFINE LANG_Complete 'Complete'
#DEFINE LANG_Price 'Price'
#DEFINE LANG_Qty_1_Needed 'Qty. 1 Needed'
#DEFINE LANG_Qty_2_Needed 'Qty. 2 Needed'
#DEFINE LANG_Qty_3_Needed 'Qty. 3 Needed'
#DEFINE LANG_Qty_4_Needed 'Qty. 4 Needed'
#DEFINE LANG_Qty_5_Needed 'Qty. 5 Needed'
#DEFINE LANG_Qty_6_Needed 'Qty. 6 Needed'
#DEFINE LANG_Qty_7_Needed 'Qty. 7 Needed'
#DEFINE LANG_Qty_8_Needed 'Qty. 8 Needed'
#DEFINE LANG_Tot_Qty_Needed 'Tot.Qty.Needed'
#DEFINE LANG_Duty_Cur 'Duty_Cur.'
#DEFINE LANG_Duty_Rate 'Duty Rate'
#DEFINE LANG_Supp_Item 'Supp. Item'
#DEFINE LANG_Supp_Color 'Supp. Color'
#DEFINE LANG_INLOCATION 'in location'
#DEFINE LANG_DESC 'Description'
#DEFINE LANG_EDITPROJ 'Edit projection'
#DEFINE LANG_UOMBUY 'UOM Buy'
#DEFINE LANG_PRICECURR 'Price Cur.'
#DEFINE LANG_PRICERATE 'Price Rate'
#DEFINE LANG_NEGTTLBROW 'Negative Remaining Materials and Style Components'
#DEFINE LANG_MPO "Material Po. "
#DEFINE LANG_SUMMARY 'Summary'
#DEFINE LANG_DETAIL 'Detail'
#DEFINE LANG_DETAILSHORT 'Detail Short'
#DEFINE LANG_DETAILLONG 'Detail Long'
#DEFINE LANG_DETAILLINES 'Detail Lines'
#DEFINE LANG_WIP 'WIP'
#DEFINE LANG_PLAN 'Plan'
#DEFINE LANG_WIPPLAN 'Wip+Plan'
#DEFINE LANG_FORECAST 'Forecast'
#DEFINE LANG_OTC 'OTC'
#DEFINE LANG_BOTH 'Both'
#DEFINE LANG_ITEMSTRCTURE 'Item structure not found'
* N000862 ,1 Thabet Handle globalization issues [end]