#DEFINE LANG_MAPMMO_Phone      'Phone# : '
#DEFINE LANG_MAPMMO_Open       'OPEN'
#DEFINE LANG_MAPMMO_Hold       'HOLD'
#DEFINE LANG_MAPMMO_Cancelled  'CANCELLED'
#DEFINE LANG_MAPMMO_Closed     'CLOSED'
#DEFINE LANG_MAPMMO_Actual     'ACTUAL'
#DEFINE LANG_MAPMMO_Complete   'COMPLETED'
#DEFINE LANG_MAPMMO_lcHead1    '                  DATE                 QTY      DATE     DIRECT'
#DEFINE LANG_MAPMMO_lcHead2    'VENDOR  ORDERD PO #  ORDRD RECVD. SHIPD.'
#DEFINE LANG_MAPMMO_lcHead11   '[-------------------- PULLED -------------------]  TOTAL'    
#DEFINE LANG_MAPMMO_Open2      'Open'
#DEFINE LANG_MAPMMO_Hold2      'Hold'
#DEFINE LANG_MAPMMO_Cancelled2 'Canceled'
#DEFINE LANG_MAPMMO_Closed2    'Closed'
#DEFINE LANG_MAPMMO_Actual2    'Actual'
#DEFINE LANG_MAPMMO_Complete2  'Complete'
#DEFINE LANG_MAPMMO_Select     'Select Order Status'
#DEFINE LANG_MAPMMO_Bid        'Bid'
#DEFINE LANG_MAPMMO_Selected   'Selected   '
#DEFINE LANG_MAPMMO_Records    '  Records in  '
#DEFINE LANG_MAPMMO_Second     ' Seconds...' 