#DEFINE REPORT_DATA "laData[1]= BOL_HDR.BOL_NO"
*N000682,1 MMT 11/20/2012 Globalization project[Start]
#DEFINE LANG_ALBOL_UNSHIP    'Un\<ship'
#DEFINE LANG_ALBOL_SHIP    '\<Ship...'
#DEFINE LANG_ALBOL_SHIPPINGDATE "Shipping Date"
#DEFINE LANG_ALBOL_BOL "Bill of lading"
#DEFINE LANG_ALBOL_CUSTOMERS 'Customers'
#DEFINE LANG_ALBOL_ACCNO 'Acct#'
#DEFINE LANG_ALBOL_NAME 'Name'
#DEFINE LANG_ALBOL_PHONE 'Phone #...'
#DEFINE LANG_ALBOL_BUYER "Buyer"
#DEFINE LANG_ALBOL_REP 'Rep'
#DEFINE LANG_ALBOL_BALANCE 'Balance'
#DEFINE LANG_ALBOL_STORE 'Store'
#DEFINE LANG_ALBOL_STORES 'Stores'
#DEFINE LANG_ALBOL_PIECES 'Pieces'
#DEFINE LANG_ALBOL_PACK 'Pack#'
#DEFINE LANG_ALBOL_PACKS 'Packs'
#DEFINE LANG_ALBOL_ORDER 'Order#'
#DEFINE LANG_ALBOL_CARTONS 'Cartons'
#DEFINE LANG_ALBOL_WEIGHT 'Weight'
#DEFINE LANG_ALBOL_PACKLISTNO "Packing list # "
#DEFINE LANG_ALBOL_ASSIGNBOL " is assigned to BOL# "
#DEFINE LANG_ALBOL_CANNOTSAVE " Cannot save Bill of Lading."
*N000682,1 MMT 11/20/2012 Globalization project[End]