#DEFINE LANG_Collect_Data 'Collecting Data.. GL Batch#: '
#DEFINE LANG_GL_Transaction '  GL Transaction#: '
#DEFINE LANG_TRAN_TYPE 'Transaction Type'
#DEFINE LANG_GLTRAN_BATCH 'GL Batch/Transaction'
#DEFINE LANG_Automatic_entry_code 'Automatic entry code'
#DEFINE LANG_Automatic_entry_TYPE 'Automatic entry type'
#DEFINE LANG_COMP_ID 'Company ID'
#DEFINE LANG_TOTAL_CREDIT 'Total credit'
#DEFINE LANG_TOTAL_DEBIT 'Total debit'
#DEFINE LANG_REV_DATE 'Reversing date'
#DEFINE LANG_SOURCE_MODULE 'Source module'
#DEFINE LANG_STANDARD_TYPE 'Standard type'
#DEFINE LANG_SOURCE_JRNL_ENTRY 'Source journal entry'
#DEFINE LANG_REV_YEAR 'Reversing year'
#DEFINE LANG_REV_PERIOD 'Reversing period'
#DEFINE LANG_REV_TRAN_ENTRY 'Reverse transaction entry'
#DEFINE LANG_TRAN_STATUS 'Transaction status'
#DEFINE LANG_POST_PERIOD 'Posting period'
#DEFINE LANG_TRANS_TYPE 'Tran. Type'
#DEFINE LANG_POST_YEAR 'Posting year'
#DEFINE LANG_POST_DATE 'Posting date'
#DEFINE LANG_TRAN_REF 'Transaction reference'
#DEFINE LANG_TRAN_DESC 'Transaction description'
#DEFINE LANG_BATCH_NO 'GL Batch Number'
#DEFINE LANG_TRAN_NO 'GL Transaction Number'
#DEFINE LANG_TRAN_IND 'Transaction indicator'
#DEFINE LANG_BATCH 'GL Batch'
#DEFINE LANG_TOTAL_CREDIT_S 'Total credits'
#DEFINE LANG_TOTAL_DEBIT_S 'Total debits'
#DEFINE LANG_BATCH_END_DATE 'Batch posting end date'
#DEFINE LANG_BATCH_REFER 'Batch reference'
#DEFINE LANG_BATCH_DESC 'Batch description'
#DEFINE LANG_BATCH_CONT_TOT 'Batch control total'
#DEFINE LANG_BATCH_BEG_DATE 'Batch posting begin date'
#DEFINE LANG_BATCH_TYPE 'Batch Type'
#DEFINE LANG_BATCH_STATUS 'Batch status'
#DEFINE LANG_GL_SESSION 'GL Session'
#DEFINE LANG_TRANS_DATE 'Tran. date'
#DEFINE LANG_TRANS_NO 'Tran. No.'
#DEFINE LANG_EX_DIFF 'EX.RATE DIFFERENCES'
#DEFINE LANG_DEBIT_MEMO   'DEBIT MEMO APPLICATION'
#DEFINE LANG_AP_PAYMENT  'AP PAYMENT'
#DEFINE LANG_BANK_ADJ 'BANK ADJUSTMENT'
#DEFINE LANG_PAY_INVOICE 'PAYABLE INVOICE'
#DEFINE LANG_CT_HON_CLOS 'C/T JOB COST CLOSING'
#DEFINE LANG_MA_JOB_CLOS 'MATERIAL JOB CLOSING'
#DEFINE LANG_KEY_OFF 'KEY OFF. '
#DEFINE LANG_NON_MAT_LIAB 'NON MAT. LIABILITY. '
#DEFINE LANG_INVOICE 'INVOICE             '

#DEFINE LANG_VOID_INV 'VOID INVOICE        '

#DEFINE LANG_CASH_REC 'CASH RECEIPT        '

#DEFINE LANG_CRED_ADJ 'CREDIT ADJUSTMENT   '

#DEFINE LANG_DEB_ADJ 'DEBIT ADJUSTMENT    '

#DEFINE LANG_RET_MERCH 'RETURN MERCHANDISE  '

#DEFINE LANG_VOID_RET 'VOID RETURN         '

#DEFINE LANG_INV_PHYISCAL 'INVENTORY PHYSICAL  '

#DEFINE LANG_INV_ADJ 'INVENTORY ADJUSTMENT'

#DEFINE LANG_PO_REC  'P/O RECEIVING       '

#DEFINE LANG_CT_REC  'C/T RECEIVING       '

#DEFINE LANG_ZERO_STK 'ZERO OUT STOCK      '

#DEFINE LANG_MA_INV_PHY 'MATERIAL INV. PHYSI.'

#DEFINE LANG_MA_INV_ADJ  'MATERIAL INV. ADJUS.'

#DEFINE LANG_MA_PO_REC  'MATERIAL P/O REC.   '


#DEFINE LANG_PO_JOB_CLOSING  'P/O JOB COST CLOSING'
 
#DEFINE LANG_GL_ENTRIES_REP "GL Entries Report"
#DEFINE LANG_GL_DETAIL "Details"
#DEFINE LANG_GL_SUMMARY  "Summary"