using System;
using System.CodeDom.Compiler;
using System.Xml.Serialization;

namespace Fedex.FedexTrack
{
	[GeneratedCode("System.Xml", "4.0.30319.1")]
	[Serializable]
	[XmlType(Namespace="http://fedex.com/ws/track/v4")]
	public enum ServiceType
	{
		EUROPE_FIRST_INTERNATIONAL_PRIORITY,
		FEDEX_1_DAY_FREIGHT,
		FEDEX_2_DAY,
		FEDEX_2_DAY_FREIGHT,
		FEDEX_3_DAY_FREIGHT,
		FEDEX_EXPRESS_SAVER,
		FEDEX_FREIGHT,
		FEDEX_GROUND,
		FEDEX_NATIONAL_FREIGHT,
		FIRST_OVERNIGHT,
		GROUND_HOME_DELIVERY,
		INTERNATIONAL_DISTRIBUTION_FREIGHT,
		INTERNATIONAL_ECONOMY,
		INTERNATIONAL_ECONOMY_DISTRIBUTION,
		INTERNATIONAL_ECONOMY_FREIGHT,
		INTERNATIONAL_FIRST,
		INTERNATIONAL_PRIORITY,
		INTERNATIONAL_PRIORITY_DISTRIBUTION,
		INTERNATIONAL_PRIORITY_FREIGHT,
		PRIORITY_OVERNIGHT,
		SMART_POST,
		STANDARD_OVERNIGHT
	}
}