CREATE TABLE [dbo].[CARRIER_LOGIN_INFORMATION_T](
	[CARRIER_ID] [varchar](20) NULL,
	[LOGIN_REQUREMENT_ID] [varchar](20) NULL,
	[LOGIN_REQUREMENT_VALUE] [varchar](100) NULL,
	[LOGIN_REQUIREMENTS_KEY] [bigint] NOT NULL,
	[CARRIER_LOGIN_INFORMATION_KEY] [bigint] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

CREATE TABLE [dbo].[CARRIER_T](
	[CARRIER_ID] [varchar](20) NULL,
	[STATUS] [varchar](1) NULL,
	[PERIOD_START] [datetime] NULL,
	[PERIOD_END] [datetime] NULL,
	[SHIPPED_CARTONS] [int] NULL,
	[SHIPPED_WEIGHT] [int] NULL,
	[TOTAL_FREIGHT] [int] NULL,
	[BALANCE] [int] NULL,
	[CARRIER_KEY] [bigint] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

