#DEFINE LANG_CONVERT_START    '     Starting conversion for Aria 4.0 XP ,please wait ...     '
#DEFINE LANG_CONVERT_SELFILES 'Select files'
#DEFINE LANG_CONVERT_LOGFILE  'Log file: def.(CnvLog.txt) '
#DEFINE LANG_CONVERT_SELECT   'Select'
#DEFINE LANG_CONVERT_PREPAR   'Preparing data for the conversion... module :'
#DEFINE LANG_CONVERT_CREATE   '     Create Aria 4.0 XP tables ,please wait ...     '
#DEFINE LANG_CONVERT_DATABASE 'Cannot create company database'
#DEFINE LANG_CONVERT_DICTNARY 'Cannot get the dictionary'
#DEFINE LANG_CONVERT_STRUCTUR ' cannot get the structure).'
#DEFINE LANG_CONVERT_INDICES  ' cannot get the indices).'
#DEFINE LANG_CONVERT_CONVERTE ' cannot get the Conversion information).'
#DEFINE LANG_CONVERT_OPENFILE ' cannot open).'
#DEFINE LANG_CONVERT_UPDSTRU  ' cannot update structure).'
#DEFINE LANG_CONVERT_UPDINDEX ' cannot update indices).'
#DEFINE LANG_CONVERT_MODULES  'modules'
#DEFINE LANG_CONVERT_INFORMAT 'information'
#DEFINE LANG_CONVERT_MODULE   'Module :'
#DEFINE LANG_CONVERT_FILE     ' ( File '
#DEFINE LANG_CONVERT_NOUPDATE ' was not Updated).'
#DEFINE LANG_CONVERT_RECNO    ' Rec No '
#DEFINE LANG_CONVERT_NORETREI ' cannot retreive data).'
#DEFINE LANG_CONVERT_NOUPDATA ' cannot update data).'
#DEFINE LANG_CONVERT_NODELETE ' cannot Delete data).'
#DEFINE LANG_CONVERT_COMPLETE 'The conversion was succesfuly completed.'
#DEFINE LANG_CONVERT_STYMAJOR ' Style Major '
#DEFINE LANG_CONVERT_TYPE     ' Type '
#DEFINE LANG_CONVERT_NOTOPEN  ' cannot open '
#DEFINE LANG_CONVERT_FILE2    ' file).'
#DEFINE LANG_CONVERT_WORKORD  ' Work Order '
#DEFINE LANG_CONVERT_LINENO   ' Line No. '
#DEFINE LANG_CONVERT_SHIPMENT ' Shipment '
#DEFINE LANG_CONVERT_ITEM     ' Item '
#DEFINE LANG_CONVERT_WARECODE ' Warehouse '
#DEFINE LANG_CONVERT_DYELOT   ' Dyelot '
#DEFINE LANG_CONVERT_SEGMENT  ' Segment '
#DEFINE LANG_CONVERT_SYCCOMP  'Cannot update file "SYCCOMP"'
#DEFINE LANG_CONVERT_RECORDS  ' record(s) converted).'
#DEFINE LANG_CONVERT_WEEK     ' Week '
#DEFINE LANG_CONVERT_YEAR     ' Year '