CLOSE ALL
lcPath = GETDIR()
IF EMPTY(lcPath)
  RETURN
ENDIF

CD (lcPath)  
USE glptrnhd
SET ORDER TO BATCHTRN   && CBATCHNO+CTRANNO
SELECT 0
USE glptrndt
SET RELATION TO CBATCHNO+CTRANNO INTO glptrnhd
LOCATE 
SELECT 0
USE apdist

SELECT glptrndt
SCAN FOR glptrnhd.CSRCMODUL = 'AP' AND (EMPTY(CINVNO) OR EMPTY(CVENDCODE))
  SELECT APDIST
  LOCATE FOR APDIST.cbatchno+APDIST.ctrnsledn = GLPTRNDT.cbatchno+GLPTRNDT.ctranno
  IF FOUND()
    SELECT GLPTRNDT
    REPLACE CINVNO WITH APDIST.CINVNO ;
            CVENDCODE WITH APDIST.CVENDCODE
  ENDIF 
ENDSCAN