//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [RelatedEntity("Aria5-Windows8Xaml-ApplicationBuildEntries_T")]
  public partial class ApplicationBuildEntries_T : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private Aria5SystemAdmin.Module.BusinessObjects.TrackingEntry _trackingEntry;
   // private Aria5SystemAdmin.Module.BusinessObjects.ApplicationBuild_T _applicationBuild_T;
    private System.String _trackingEntryId;
    public ApplicationBuildEntries_T(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String TrackingEntryId
    {
      get
      {
        return _trackingEntryId;
      }
      set
      {
        SetPropertyValue("TrackingEntryId", ref _trackingEntryId, value);
      }
    }
   // [DevExpress.Xpo.AssociationAttribute("ApplicationBuildEntries_Ts-ApplicationBuild_T")]
    //public Aria5SystemAdmin.Module.BusinessObjects.ApplicationBuild_T ApplicationBuild_T
    //{
    //  get
    //  {
    //    return _applicationBuild_T;
    //  }
    //  set
    //  {
    //    SetPropertyValue("ApplicationBuild_T", ref _applicationBuild_T, value);
    //  }
    //}
    //[DevExpress.Xpo.AssociationAttribute("ApplicationBuild_T-TrackingEntrys")]
    //public Aria5SystemAdmin.Module.BusinessObjects.TrackingEntry TrackingEntry
    //{
    //  get
    //  {
    //    return _trackingEntry;
    //  }
    //  set
    //  {
    //    SetPropertyValue("TrackingEntry", ref _trackingEntry, value);
    //  }
    //}
  }
}
