//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.Security.Strategy;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [RelatedEntity("Aria5-SystemAdmin-AriaSecuritySystemUser")]
  public partial class AriaSecuritySystemUser : SecuritySystemUser
  {
    private Aria5SystemAdmin.Module.BusinessObjects.Account _account;
    private Aria5SystemAdmin.Module.BusinessObjects.Division _division;

    public AriaSecuritySystemUser(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public static Account CurrentAccount;
      [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public Aria5SystemAdmin.Module.BusinessObjects.Account Account
    {
      get
      {
        return _account;
      }
      set
      {
        SetPropertyValue("Account", ref _account, value);
      }
    }
      public Aria5SystemAdmin.Module.BusinessObjects.Division Division
      {
          get
          {
              return _division;
          }
          set
          {
              SetPropertyValue("Division", ref _division, value);
          }
      }

      //ATA add employee profile for the security user HR system work requied this action 1/15/2017 [start]
      private HREmployee _employee;
     // [Association("Ariasecurityuser-Employee")]
      public HREmployee Employee
      {
          get
          {
              return _employee;
          }
          set
          {
              SetPropertyValue("Employee", ref _employee, value);
          }
      }
      //ATA add employee profile for the security user HR system work requied this action 1/15/2017 [End]

  }
}
