//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.Persistent.Validation;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class AriaObjectBrowse : XPCustomObject
  {
    private System.String _objectOid;
    private System.String _key;
    private System.Int32 _objectID;
    private System.String _activeRevision;
    private System.String _objectDescription;
    private System.String _objectName;
    public AriaObjectBrowse(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.Int32 ObjectID
    {
      get
      {
        return _objectID;
      }
      set
      {
        SetPropertyValue("ObjectID", ref _objectID, value);
      }
    }
    public System.String ActiveRevision
    {
      get
      {
        return _activeRevision;
      }
      set
      {
        SetPropertyValue("ActiveRevision", ref _activeRevision, value);
      }
    }
    public System.String ObjectName
    {
      get
      {
        return _objectName;
      }
      set
      {
        SetPropertyValue("ObjectName", ref _objectName, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String ObjectDescription
    {
      get
      {
        return _objectDescription;
      }
      set
      {
        SetPropertyValue("ObjectDescription", ref _objectDescription, value);
      }
    }
    [DevExpress.Xpo.KeyAttribute]
    public System.String Key
    {
      get
      {
        return _key;
      }
      set
      {
        SetPropertyValue("Key", ref _key, value);
      }
    }
    public System.String ObjectOid
    {
      get
      {
        return _objectOid;
      }
      set
      {
        SetPropertyValue("ObjectOid", ref _objectOid, value);
      }
    }
  }
}
