//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [RelatedEntity("Aria5-SystemAdmin-AriaObjectShelve")]

  public partial class AriaObjectShelve : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.String _state;
    private Aria5SystemAdmin.Module.BusinessObjects.TrackingEntry _trackingEntry;
    private Aria5SystemAdmin.Module.BusinessObjects.AriaObject _parentObject;
    private ModificationTypes _modificationType;
    private Aria5SystemAdmin.Module.BusinessObjects.AriaObject _ariaObject;
    private System.Int32 _objectID;
    private Aria5SystemAdmin.Module.BusinessObjects.ObjectType _objectType;
    private System.String _changeSet;
    private System.String _objectDescription;
    private System.String _objectName;
    private System.String _description;
    public AriaObjectShelve(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public Aria5SystemAdmin.Module.BusinessObjects.AriaObject ParentObject
    {
      get
      {
        return _parentObject;
      }
      set
      {
        SetPropertyValue("ParentObject", ref _parentObject, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(-1)]
    public System.String Description
    {
      get
      {
        return _description;
      }
      set
      {
        SetPropertyValue("Description", ref _description, value);
      }
    }
    public System.String ObjectName
    {
      get
      {
        return _objectName;
      }
      set
      {
        SetPropertyValue("ObjectName", ref _objectName, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(250)]
    public System.String ObjectDescription
    {
      get
      {
        return _objectDescription;
      }
      set
      {
        SetPropertyValue("ObjectDescription", ref _objectDescription, value);
      }
    }
    public Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelve.ModificationTypes ModificationType
    {
      get
      {
        return _modificationType;
      }
      set
      {
        SetPropertyValue("ModificationType", ref _modificationType, value);
      }
    }
    public System.String ChangeSet
    {
      get
      {
        return _changeSet;
      }
      set
      {
        SetPropertyValue("ChangeSet", ref _changeSet, value);
      }
    }
    public Aria5SystemAdmin.Module.BusinessObjects.ObjectType ObjectType
    {
      get
      {
        return _objectType;
      }
      set
      {
        SetPropertyValue("ObjectType", ref _objectType, value);
      }
    }
    //public Aria5SystemAdmin.Module.BusinessObjects.TrackingEntry TrackingEntry
    //{
    //  get
    //  {
    //    return _trackingEntry;
    //  }
    //  set
    //  {
    //    SetPropertyValue("TrackingEntry", ref _trackingEntry, value);
    //  }
    //}
    public System.Int32 ObjectID
    {
      get
      {
        return _objectID;
      }
      set
      {
        SetPropertyValue("ObjectID", ref _objectID, value);
      }
    }
    public Aria5SystemAdmin.Module.BusinessObjects.AriaObject AriaObject
    {
      get
      {
        return _ariaObject;
      }
      set
      {
          
        SetPropertyValue("AriaObject", ref _ariaObject, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("AriaObjectShelveProperties-AriaObjectShelve")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelveProperty> AriaObjectShelveProperties
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelveProperty>("AriaObjectShelveProperties");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("AriaObjectShelves-TrackingEntry")]
    public Aria5SystemAdmin.Module.BusinessObjects.TrackingEntry TrackingEntry
    {
      get
      {
        return _trackingEntry;
      }
      set
      {
        SetPropertyValue("TrackingEntry", ref _trackingEntry, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("AriaObjectShelveSettings-AriaObjectShelve")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelveSetting> AriaObjectShelveSettings
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelveSetting>("AriaObjectShelveSettings");
      }
    }
    public System.String State
    {
      get
      {
        return _state;
      }
      set
      {
        SetPropertyValue("State", ref _state, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("AriaObjectShelveMethods-AriaObjectShelve")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelveMethod> AriaObjectShelveMethods
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelveMethod>("AriaObjectShelveMethods");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("AriaObjectShelveEvents-AriaObjectShelve")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelveEvent> AriaObjectShelveEvents
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelveEvent>("AriaObjectShelveEvents");
      }
    }

      //ATA 2/1/2017 add status to shelve if it checked out or checked in [Start]
    private Status? _status;
    public Status? CodeStatus
    {
        get
        {
            return _status;
        }
        set
        {
            SetPropertyValue("Status", ref _status, value);

        }
    }
      public enum Status
    {
        CheckedOut,
        CheckedIn
    }
  }
}
