//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class AriaObjectShelveEventParameterSetting : DevExpress.Persistent.BaseImpl.BaseObject
  {
    [DevExpress.Xpo.AssociationAttribute("AriaObjectShelveEventParameterSettings-AriaObjectShelveEventParameter")]
    public Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelveEventParameter AriaObjectShelveEventParameter
    {
      get
      {
        return _ariaObjectShelveEventParameter;
      }
      set
      {
        SetPropertyValue("AriaObjectShelveEventParameter", ref _ariaObjectShelveEventParameter, value);
      }
    }
    private System.Boolean _modified;
    private bool _valueIsChanged;
    private Aria5SystemAdmin.Module.BusinessObjects.AriaObjectShelveEventParameter _ariaObjectShelveEventParameter;
    private System.Int32 _decimalPlaces;
    private System.Int32 _width;
    private Aria5SystemAdmin.Module.BusinessObjects.SettingType _settingType;
    private System.String _dataType;
    private System.String _value;
    public AriaObjectShelveEventParameterSetting(DevExpress.Xpo.Session session)
      : base(session)
    {
      _valueIsChanged = false;
    }
    public Aria5SystemAdmin.Module.BusinessObjects.SettingType SettingType
    {
      get
      {
        return _settingType;
      }
      set
      {
        SetPropertyValue("SettingType", ref _settingType, value);
      }
    }
    public System.String Value
    {
      get
      {
        return _value;
      }
      set
      {
        SetPropertyValue("Value", ref _value, value);
        if (IsLoading == false)
          _valueIsChanged = true;
      }
    }
    public System.String DataType
    {
      get
      {
        return _dataType;
      }
      set
      {
        SetPropertyValue("DataType", ref _dataType, value);
      }
    }
    public System.Int32 Width
    {
      get
      {
        return _width;
      }
      set
      {
        SetPropertyValue("Width", ref _width, value);
      }
    }
    public System.Int32 DecimalPlaces
    {
      get
      {
        return _decimalPlaces;
      }
      set
      {
        SetPropertyValue("DecimalPlaces", ref _decimalPlaces, value);
      }
    }
    public System.Boolean Modified
    {
      get
      {
        return _modified;
      }
      set
      {
        SetPropertyValue("Modified", ref _modified, value);
      }
    }
  }
}
