//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class AriaObjectBrowseMethodParameter : XPCustomObject
  {
    private System.String _keyProperty;
    private System.String _methodParameterOid;
    private Aria5SystemAdmin.Module.BusinessObjects.PropertyType _parameterType;
    private System.Int32 _parameterNo;
    private System.String _parameterName;
    public AriaObjectBrowseMethodParameter(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String ParameterName
    {
      get
      {
        return _parameterName;
      }
      set
      {
        SetPropertyValue("ParameterName", ref _parameterName, value);
      }
    }
    public System.Int32 ParameterNo
    {
      get
      {
        return _parameterNo;
      }
      set
      {
        SetPropertyValue("ParameterNo", ref _parameterNo, value);
      }
    }
    public Aria5SystemAdmin.Module.BusinessObjects.PropertyType ParameterType
    {
      get
      {
        return _parameterType;
      }
      set
      {
        SetPropertyValue("ParameterType", ref _parameterType, value);
      }
    }
    public System.String MethodParameterOid
    {
      get
      {
        return _methodParameterOid;
      }
      set
      {
        SetPropertyValue("MethodParameterOid", ref _methodParameterOid, value);
      }
    }
    [DevExpress.Xpo.KeyAttribute]
    public System.String KeyProperty
    {
      get
      {
        return _keyProperty;
      }
      set
      {
        SetPropertyValue("KeyProperty", ref _keyProperty, value);
      }
    }
  }
}
