//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using System.Linq;

using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;

namespace Aria5SystemAdmin.Module.BusinessObjects
{
    [DefaultClassOptions]
    [RelatedEntity("Aria5-SystemAdmin-DefectDensityReport")]
    public partial class DefectDensityReport : DevExpress.Persistent.BaseImpl.BaseObject
    {
        public DefectDensityReport(DevExpress.Xpo.Session session)
            : base(session)
        {

        }
        private string _title;

        public string Title
        {
            get
            {
                return _title;
            }
            set
            {
                _title = value;
            }
        }
        private DateTime _datefrom;

        public DateTime DateFrom
        {
            get
            {
                return _datefrom;
            }
            set
            {
                _datefrom = value;
            }
        }
        private DateTime _dateto;

        public DateTime DateTo
        {
            get
            {
                return _dateto;
            }
            set
            {
                _dateto = value;
            }
        }
        private Application_T _application;
        public Application_T Application
        {
            get
            {
                return _application;
            }
            set
            {
                _application = value;
            }
        }


        
        [Association("DefectDensityvalues-DefectDensityReport")]
        public XPCollection<DefectDensityvalues> DefectDensityValues
        {
            get
            {
                return GetCollection<DefectDensityvalues>("DefectDensityValues");
            }
        }
    }
}
