//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [RelatedEntity("Aria5-SystemAdmin-HR_ActivityCategory")]
  [XafDefaultProperty("Name")]
  public partial class HR_ActivityCategory : DevExpress.Persistent.BaseImpl.BaseObject
  {
    public HR_ActivityCategory(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    private string _name;
    public string Name
    {
      get
      {
        return _name;
      }
      set
      {
        _name = value;
      }
    }
    private Department _department;
    [Association("HR_ActivityCategory-Department")]
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public Department Department
    {
      get
      {
        if (_departmentcode == null && _department != null)
        {
          if (_department.Id != null)
          {
            _departmentcode = _department.Id;
            _departmentname = _department.Description;
          }
        }
        return _department;
      }
      set
      {
        _department = value;
      }
    }
   
    private HR_Role _role;
       [Association("HRRole-Categories")]
    public HR_Role Role
    {
        get { return _role; }
        set { _role = value; }
    }

    private string _departmentcode;
    public string DepartmentCode
    {
      get
      {
        return _departmentcode;
      }
      set
      {
        _departmentcode = value;
      }
    }
    private string _departmentname;
    public string DepartmentName
    {
      get
      {
        return _departmentname;
      }
      set
      {
        _departmentname = value;
      }
    }
    private string _description;
    public string Description
    {
      get
      {
        return _description;
      }
      set
      {
        _description = value;
      }
    }
    [Association("HRActivity-HR_ActivityCategory")]
    public XPCollection<HRActivity> Activities
    {
      get
      {
        return GetCollection<HRActivity>("Activities");
      }
    }
  }
}
