//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.Persistent.Validation;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class HR_Company : HR_Entity
  {
    public HR_Company(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    private String _companyname;
    private string _aboutcompany;
    [RuleRequiredField]
    public string CompanyName
    {
      get
      {
        return _companyname;
      }
      set
      {
        _companyname = value;
      }
    }
    [DevExpress.Xpo.Size(150)]
    public string AboutCompany
    {
      get
      {
        return _aboutcompany;
      }
      set
      {
        _aboutcompany = value;
      }
    }
    //[Association("HR_Company-HR_Branches")]
    //public XPCollection<HR_Branches> CompanyBranches
    //{
    //  get
    //  {
    //    return GetCollection<HR_Branches>("CompanyBranches");
    //  }
    //}
    //[Association("HR_Company-Department")]
    //public XPCollection<Department> CompanyDepartments
    //{
    //  get
    //  {
    //    return GetCollection<Department>("CompanyDepartments");
    //  }
    //}
    //   [Association("HR_Employees-HR_Company")]
    //public XPCollection<HR_Employee> Employees
    //{
    //    get
    //    {
    //        return GetCollection<HR_Employee>("Employees");
    //    }
    //}
  }
}
