//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using System.Linq;

using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using System.ComponentModel;
using DevExpress.Persistent.Validation;

namespace Aria5SystemAdmin.Module.BusinessObjects
{
  
    // [Appearance("CertifiedLevelapperance", AppearanceItemType = "ViewItem", TargetItems = "LanguageLevel", Criteria = "Type!='CertificateandTraining'", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
    [DefaultClassOptions]
    [RelatedEntity("Aria5-SystemAdmin-Skillinstance")]
    [Appearance("Levelapperance", AppearanceItemType = "ViewItem", TargetItems = "Level", Criteria = "Type!='Skill'", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
    [Appearance("langLevelapperance", AppearanceItemType = "ViewItem", TargetItems = "LanguageLevel", Criteria = "Type!='Languages'", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
    [Appearance("Comleteapperance", AppearanceItemType = "ViewItem", TargetItems = "Faculty,Major,CompletionDate,Grade,Unvirsety,Completed", Criteria = "Type =='Skill' Or Type =='Languages'", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
    [Appearance("Comleteapperance1", AppearanceItemType = "ViewItem", TargetItems = "Major,Grade,Unvirsety,Faculty", Criteria = "Type =='CertificateandTraining'", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
   
    // [Appearance("Emplapperance", AppearanceItemType = "ViewItem", TargetItems = "Employee", Criteria = "Employee Is Null", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
   // [Appearance("Jobposlapperance", AppearanceItemType = "ViewItem", TargetItems = "JobPosition", Criteria = "JobPosition Is Null", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
    public partial class HRSkillInstance : DevExpress.Persistent.BaseImpl.BaseObject
    {
        public HRSkillInstance(DevExpress.Xpo.Session session)
            : base(session)
        {

        }
        private Skillstype _type;
        [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
        [RuleRequiredField]
        public Skillstype Type
        {
            get
            {
                return _type;
            }
            set
            {
                SetPropertyValue("Type", ref _type, value);
                if (!IsLoading)
                {
                    Category = null;
                }
            }
        }
        private HRSkillsCategory _category;
        [ImmediatePostData(true)]
        [DataSourceCriteria("Type = '@This.Type'")]
       // [RuleRequiredField]
        public HRSkillsCategory Category
        {
            get
            {
                return _category;
            }
            set
            {
                SetPropertyValue("Category", ref _category, value);
                if (!IsLoading)
                {
                    Skill = null;
                }
            }
        }
        private HRSkill _skill;
        [DataSourceCriteria("Category = '@This.Category'")]
      //  [RuleRequiredField]
        public HRSkill Skill
        {
            get
            {
                return _skill;
            }
            set
            {
                _skill = value;
            }
        }
        private bool _completed;
        public bool Completed
        {
            get
            {
                return _completed;
            }
            set
            {
                _completed = value;
            }
        }
        private HREmployee _employee;
        [Association("HREmployee-Skillsinstance")]
        [Browsable(false)]
        public HREmployee Employee
        {
            get
            {
                return _employee;
            }
            set
            {
                SetPropertyValue("Employee", ref _employee, value);
            }
        }
        private HRJobPosition _jobposition;
        [Association("HRJobPosition-Skillsinstance")]
        [Browsable(false)]
        public HRJobPosition JobPosition
        {
            get
            {
                return _jobposition;
            }
            set
            {
                SetPropertyValue("JobPosition", ref _jobposition, value);
            }
        }
        private Skill_Level? _level;
        public Skill_Level? Level
        {
            get
            {
                return _level;
            }
            set
            {
                _level = value;
            }
        }
        private Language_level? _languageLevel;
        [Browsable(false)]
        public Language_level? LanguageLevel
        {
            get
            {
                return _languageLevel;
            }
            set
            {
                _languageLevel = value;
            }
        }
        public enum Skill_Level
        {
            Fair, good, verygood, Excellent 
        }
        public enum Language_level
        {
            Faire,
            Intermediate,
            Good,
            Fluent,
            native
        }

        //ATA add this 2 fields to handle the education skill details as per HR request 
        
       
        private string _unvirsety;
        [VisibleInListView(false)]
        public string Unvirsety
        {
            get { return _unvirsety; }
            set { _unvirsety = value; }
        }
        private string _faculty;
        [VisibleInListView(false)]
        public string Faculty
        {
            get { return _faculty; }
            set { _faculty = value; }
        }  private string _major;
        [VisibleInListView(false)]
        public string Major
        {
            get { return _major; }
            set { _major = value; }
        }
        private string _grade;
        [VisibleInListView(false)]
        public string Grade
        {
            get { return _grade; }
            set { _grade = value; }
        }
        private DateTime _graduationDate;
        [VisibleInListView(false)]
        public DateTime CompletionDate
        {
            get { return _graduationDate; }
            set { _graduationDate = value; }
        }
    }
}
