//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
    [NonPersistent]
  public partial class JobPosition : HR_Entity
  {
    public JobPosition(DevExpress.Xpo.Session session)
      : base(session)
    {
    }

    private bool _sat;
    private bool _sun;
    private bool _mon;
    private bool _tue;
    private bool _wed;
    private bool _Thu;
    private bool _fri;
    private string _name;
    public string Name
    {
      get
      {
        return _name;
      }
      set
      {
        _name = value;
      }
    }

    //private Department _department;
    //[Association("JobPosition-Department")]
    //public Department Department
    //{
    //    get
    //    {
    //        return _department;
    //    }
    //    set
    //    {
    //        _department = value;
    //    }
    //}
    private JobPosition _backup;

    public JobPosition BackUp
    {
        get { return _backup; }
        set { _backup = value; }
    }
    //private HR_Branches _location;

    //public HR_Branches Location
    //{
    //    get { return _location; }
    //    set { _location = value; }
    //}

    private JobPosition _reportTO1;

    public JobPosition ReportTo1
    {
        get { return _reportTO1; }
        set { _reportTO1 = value; }
    }

    private JobPosition _reportTo2;

    public JobPosition ReportTo2
    {
        get { return _reportTo2; }
        set { _reportTo2 = value; }
    }
    public bool Sat
    {
        get
        {
            return _sat;
        }
        set
        {
            _sat = value;
        }
    }
    public bool Sun
    {
        get
        {
            return _sun;
        }
        set
        {
            _sun = value;
        }
    }
    public bool Mon
    {
        get
        {
            return _mon;
        }
        set
        {
            _mon = value;
        }
    }
    public bool Tue
    {
        get
        {
            return _tue;
        }
        set
        {
            _tue = value;
        }
    }
    public bool Wed
    {
        get
        {
            return _wed;
        }
        set
        {
            _wed = value;
        }
    }
    public bool Thu
    {
        get
        {
            return _Thu;
        }
        set
        {
            _Thu = value;
        }
    }
    public bool Fri
    {
        get
        {
            return _fri;
        }
        set
        {
            _fri = value;
        }
    }

    private TimeSpan _Workinghoursfrom;

    public TimeSpan WorkingHoursFrom
    {
        get { return _Workinghoursfrom; }
        set { _Workinghoursfrom = value; }
    }
    private TimeSpan _workingHoursTo;

    public TimeSpan WorkingHoursTo
    {
        get { return _workingHoursTo; }
        set { _workingHoursTo = value; }
    }

    //private int _agefrom;
    //public int AgeFrom
    //{
    //  get
    //  {
    //    return _agefrom;
    //  }
    //  set
    //  {
    //    _agefrom = value;
    //  }
    //}
    //private int _ageto;
    //public int AgeTo
    //{
    //  get
    //  {
    //    return _ageto;
    //  }
    //  set
    //  {
    //    _ageto = value;
    //  }
    //}
    private double _salaryfrom;
    public double SalaryFrom
    {
      get
      {
        return _salaryfrom;
      }
      set
      {
        _salaryfrom = value;
      }
    }
    private double _salaryto;
    public double SalaryTo
    {
      get
      {
        return _salaryto;
      }
      set
      {
        _salaryto = value;
      }
    }

    private string _jobdescription;
    public string JobDescription
    {
        get
        {
            return _jobdescription;
        }
        set
        {
            _jobdescription = value;
        }
    }
    private string _education;
    public string EducationCertificates
    {
        get
        {
            return _education;
        }
        set
        {
            _education = value;
        }
    }
    private string _technicalKnowledge;

    public string TechnicalKnowledge
    {
        get { return _technicalKnowledge; }
        set { _technicalKnowledge = value; }
    }

    private string _Businessknowledge;

    public string Businessknowledge
    {
        get { return _Businessknowledge; }
        set { _Businessknowledge = value; }
    }
    private string _personalAbilitiesSkills;

    public string PersonalAbilitiesSkills
    {
        get { return _personalAbilitiesSkills; }
        set { _personalAbilitiesSkills = value; }
    }

    private string _ManagerialSkills;

    public string ManagerialSkills
    {
        get { return _ManagerialSkills; }
        set { _ManagerialSkills = value; }
    }

    private string _languages;

    public string Languages
    {
        get { return _languages; }
        set { _languages = value; }
    }

    private string _yearsOfExperience;

    public string YearsOfExperience
    {
        get { return _yearsOfExperience; }
        set { _yearsOfExperience = value; }
    }
    //[Association("JobPosition-HR_Employee")]
    //public XPCollection<HR_Employee> Employees
    //{
    //  get
    //  {
    //    return GetCollection<HR_Employee>("Employees");
    //  }
    //}

    //[Association("JobPosition-HR_Activity")]
    //public XPCollection<HR_Activity> Activities
    //{
    //    get
    //    {
    //        return GetCollection<HR_Activity>("Activities");
    //    }
    //}
  }

}
