//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [RelatedEntity("Aria5-Windows8Xaml-MicelloLocationType")]
  [DivisionAttribute(true)]
  public partial class MicelloLocationType : Aria5SystemAdmin.Module.BusinessObjects.Entity
  {
    private System.String _name;
    private System.String _iD;
    public MicelloLocationType(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.Xpo.NonPersistentAttribute]
    public System.String ID
    {
      get
      {
        return _iD;
      }
      set
      {
        SetPropertyValue("ID", ref _iD, value);
      }
    }
    [DevExpress.Xpo.NonPersistentAttribute]
    public System.String Name
    {
      get
      {
        return _name;
      }
      set
      {
        SetPropertyValue("Name", ref _name, value);
      }
    }
  }
}
