//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class Notes : DevExpress.Persistent.BaseImpl.BaseObject
  {
    public Notes(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    private string _title;
    public string Title
    {
      get
      {
        return _title;
      }
      set
      {
        _title = value;
      }
    }
    private string _description;
    [Size(SizeAttribute.Unlimited)]
    public string Description
    {
      get
      {
        return _description;
      }
      set
      {
        _description = value;
      }
    }
    private DateTime _date;
    public DateTime Date
    {
      get
      {
        return _date;
      }
      set
      {
        _date = value;
      }
    }
    private Entity _entity;
    [Association("Entity-Notes")]
    public Entity Entity
    {
      get
      {
        return _entity;
      }
      set
      {
        _entity = value;
      }
    }
  }
}
