//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using System.Linq;

using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.Persistent.Validation;

namespace Aria5SystemAdmin.Module.BusinessObjects
{
    [DefaultClassOptions]
    [RelatedEntity("Aria5-Windows8Xaml-OnlineGame")]
    [MapInheritance(MapInheritanceType.ParentTable)]
  //  [NavigationItem("1TouchAway")]
    [DivisionAttribute(true)]
    public partial class OnlineGame : Entity
    {
        public OnlineGame(DevExpress.Xpo.Session session)
            : base(session)
        {

        }
        private System.String _URL;

        [RuleRequiredField]
        [RuleRegularExpression("HyperLinkDemoObject.Url.RuleRegularExpression", DefaultContexts.Save, @"(((http|https|ftp)\://)?[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(:[a-zA-Z0-9]*)?/?([a-zA-Z0-9\-\._\?\,\'/\\\+&amp;%\$#\=~])*)|([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6})")]
        [EditorAlias("HyperLinkStringPropertyEditor")]
        public System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                SetPropertyValue("URL", ref _URL, value);
            }
        }

        private System.Double _UnitCost;
        public System.Double UnitCost
        {
            get
            {
                return _UnitCost;
            }
            set
            {
                SetPropertyValue("UnitCost", ref _UnitCost, value);
            }
        }
    }
}
