//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.Persistent.Validation;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [Appearance("EndDate", AppearanceItemType = "ViewItem", TargetItems = "Enddate", Criteria = "!IsCurrentUserInRole('IterationAdmin')", Context = "DetailView", Enabled = false)]
  [Appearance("Action", AppearanceItemType = "Action", TargetItems = "ScopeApproval", Criteria = "!IsCurrentUserInRole('Managers')", Context = "ListView", Enabled = false)]
  [RelatedEntity("Aria5-SystemAdmin-ProjectScope")]
  public partial class ProjectScope : DevExpress.Persistent.BaseImpl.BaseObject
  {
    public ProjectScope(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    private string _description;
    private approvalstatus _status;
    private DateTime _approvdate;
    private AriaSecuritySystemUser _approveby;
    private ProjectTemplate _project;
    [Size(SizeAttribute.Unlimited)]
    [RuleRequiredField]
    public string Description
    {
      get
      {
        return _description;
      }
      set
      {
        SetPropertyValue("Description", ref _description, value);
      }
    }
    public approvalstatus Status
    {
      get
      {
        return _status;
      }
      set
      {
        SetPropertyValue("Status", ref _status, value);
      }
    }
    public DateTime ApprovalDate
    {
      get
      {
        return _approvdate;
      }
      set
      {
        SetPropertyValue("ApprovalDate", ref _approvdate, value);
      }
    }
    public AriaSecuritySystemUser ApprovedBy
    {
      get
      {
        return _approveby;
      }
      set
      {
        SetPropertyValue("ApprovedBy", ref _approveby, value);
      }
    }
    [Association("Projecttemplate-ProjectScopes")]
    public ProjectTemplate Project
    {
      get
      {
        return _project;
      }
      set
      {
        SetPropertyValue("Project", ref _project, value);
      }
    }
    private DateTime _enddate;
    public DateTime EndDate
    {
      get
      {
        return _enddate;
      }
      set
      {
        SetPropertyValue("EndDate", ref _enddate, value);
      }
    }
  }
  public enum approvalstatus
  {
    New,
    Approved
  }
}
