//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.Persistent.Validation;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]

  [Appearance("Action", AppearanceItemType = "Action", TargetItems = "ProofOfConceptApproval", Criteria = "!IsCurrentUserInRole('Managers')", Context = "DetailView", Enabled = false)]
  [Appearance("DeleteAction", AppearanceItemType = "Action", TargetItems = "Delete", Criteria = "Status == 'Approved'", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
  
  public partial class ProofOfConcept : DevExpress.Persistent.BaseImpl.BaseObject
  {
    public ProofOfConcept(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    private string _name;
    [RuleRequiredField]
    public string Name
    {
      get
      {
        return _name;
      }
      set
      {
        _name = value;
      }
    }
    private string _description;
    [Size(SizeAttribute.Unlimited)]
    [RuleRequiredField]
    public string Description
    {
      get
      {
        return _description;
      }
      set
      {
        _description = value;
      }
    }
    private string _conclusion;
    [Size(SizeAttribute.Unlimited)]
    public string Conclusion
    {
      get
      {
        return _conclusion;
      }
      set
      {
        _conclusion = value;
      }
    }
    private string _refrence1;
    [RuleRegularExpression("POCRefrence1.RuleRegularExpression", DefaultContexts.Save, @"(((http|https|ftp)\://)?[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(:[a-zA-Z0-9]*)?/?([a-zA-Z0-9\-\._\?\,\'/\\\+&amp;%\$#\=~])*)|([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6})")]
    [EditorAlias("HyperLinkStringPropertyEditor")]
    [Size(4000)]
    public string Refrence1
    {
      get
      {
        return _refrence1;
      }
      set
      {
        _refrence1 = value;
      }
    }
    private string _refrence2;
    [RuleRegularExpression("pocRefrence2.RuleRegularExpression", DefaultContexts.Save, @"(((http|https|ftp)\://)?[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(:[a-zA-Z0-9]*)?/?([a-zA-Z0-9\-\._\?\,\'/\\\+&amp;%\$#\=~])*)|([a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6})")]
    [EditorAlias("HyperLinkStringPropertyEditor")]
    [Size(4000)]
    public string Refrence2
    {
      get
      {
        return _refrence2;
      }
      set
      {
        _refrence2 = value;
      }
    }
    private DateTime _approvalDate;
    public DateTime ApprovalDate
    {
      get
      {
        return _approvalDate;
      }
      set
      {
        _approvalDate = value;
      }
    }
    private AriaSecuritySystemUser _approvedBy;
    public AriaSecuritySystemUser ApprovedBy
    {
      get
      {
        return _approvedBy;
      }
      set
      {
        _approvedBy = value;
      }
    }
    private approvalstatus _status;
    public approvalstatus Status
    {
      get
      {
        return _status;
      }
      set
      {
          SetPropertyValue("Status",ref _status, value);
      }
    }
    private ProjectTemplate _project;
    [Association("ProjectTemplate-ProofOfConcepts")]
    public ProjectTemplate Project
    {
      get
      {
        return _project;
      }
      set
      {
        _project = value;
      }
    }
    [Association("ProofOfConcept-POCQuestions")]
    public XPCollection<POCQuestions> Questions
    {
      get
      {
        return GetCollection<POCQuestions>("Questions");
      }
    }
  }
}
