//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.Persistent.Validation;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  //[Appearance("QADefect", AppearanceItemType = "ViewItem", TargetItems = "QADefect", Criteria = "QADefect!=null", Context = "DetailView", Enabled = false)]
  //[Appearance("QAProjectEntity", AppearanceItemType = "ViewItem", TargetItems = "QAProjectEntity", Criteria = "QAProjectEntity!=null", Context = "DetailView", Enabled = false)]
  //[Appearance("QAUseCase", AppearanceItemType = "ViewItem", TargetItems = "QAUseCase", Criteria = "QAUseCase!=null", Context = "DetailView", Enabled = false)]
  //[Appearance("QAUseCaseFlow", AppearanceItemType = "ViewItem", TargetItems = "QAUseCaseFlow", Criteria = "QAUseCaseFlow!=null", Context = "DetailView", Enabled = false)]
  //[Appearance("Requirement", AppearanceItemType = "ViewItem", TargetItems = "Requirement", Criteria = "Requirement!=null", Context = "DetailView", Enabled = false)]
  //[Appearance("TestCase", AppearanceItemType = "ViewItem", TargetItems = "TestCase", Criteria = "TestCase!=null", Context = "DetailView", Enabled = false)]
  //[Appearance("TestCaseSteps", AppearanceItemType = "ViewItem", TargetItems = "TestCaseSteps", Criteria = "TestCaseSteps!=null", Context = "DetailView", Enabled = false)]
  //[Appearance("TestRun", AppearanceItemType = "ViewItem", TargetItems = "TestRun", Criteria = "TestRun!=null", Context = "DetailView", Enabled = false)]
  [DefaultClassOptions]
  [XafDefaultProperty("File")]
  [RelatedEntity("Aria5-SystemAdmin-Attachement")]
  [Appearance("ProjectTemplate", AppearanceItemType = "ViewItem", TargetItems = "ProjectTemplate", Criteria = "ProjectTemplate!=null", Context = "DetailView", Enabled = false)]
  public partial class QAAttachement : FileAttachmentBase
  {
    private System.DateTime _addDate;
    // private Aria5SystemAdmin.Module.BusinessObjects.Resources _resourceName;
    private Aria5SystemAdmin.Module.BusinessObjects.TestRun _testRun;
    private Aria5SystemAdmin.Module.BusinessObjects.TestCaseSteps _testCaseSteps;
    private Aria5SystemAdmin.Module.BusinessObjects.TestCase _testCase;
    private Aria5SystemAdmin.Module.BusinessObjects.Requirement _requirement;
    private Aria5SystemAdmin.Module.BusinessObjects.QAUseCaseFlow _qAUseCaseFlow;
    private Aria5SystemAdmin.Module.BusinessObjects.QAUseCase _qAUseCase;
    private Aria5SystemAdmin.Module.BusinessObjects.QAProjectEntity _qAProjectEntity;
    private Aria5SystemAdmin.Module.BusinessObjects.QADefect _qADefect;
    private Aria5SystemAdmin.Module.BusinessObjects.ProjectTemplate _projectTemplate;
    public QAAttachement(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.Xpo.AssociationAttribute("QAAttachements-ProjectTemplate")]
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    //ATA add the rule required 2/2/2017 
      [RuleRequiredField]
    public Aria5SystemAdmin.Module.BusinessObjects.ProjectTemplate ProjectTemplate
    {
      get
      {
        return _projectTemplate;
      }
      set
      {
        SetPropertyValue("ProjectTemplate", ref _projectTemplate, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-QADefect")]
    public Aria5SystemAdmin.Module.BusinessObjects.QADefect QADefect
    {
      get
      {
        return _qADefect;
      }
      set
      {
        SetPropertyValue("QADefect", ref _qADefect, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-QAProjectEntity")]
    public Aria5SystemAdmin.Module.BusinessObjects.QAProjectEntity QAProjectEntity
    {
      get
      {
        return _qAProjectEntity;
      }
      set
      {
        SetPropertyValue("QAProjectEntity", ref _qAProjectEntity, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-QAUseCase")]
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public Aria5SystemAdmin.Module.BusinessObjects.QAUseCase QAUseCase
    {
      get
      {
        return _qAUseCase;
      }
      set
      {
        SetPropertyValue("QAUseCase", ref _qAUseCase, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-QAUseCaseFlow")]
    public Aria5SystemAdmin.Module.BusinessObjects.QAUseCaseFlow QAUseCaseFlow
    {
      get
      {
        return _qAUseCaseFlow;
      }
      set
      {
        SetPropertyValue("QAUseCaseFlow", ref _qAUseCaseFlow, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-Requirement")]
    public Aria5SystemAdmin.Module.BusinessObjects.Requirement Requirement
    {
      get
      {
        return _requirement;
      }
      set
      {
        SetPropertyValue("Requirement", ref _requirement, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-TestCase")]
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public Aria5SystemAdmin.Module.BusinessObjects.TestCase TestCase
    {
      get
      {
        return _testCase;
      }
      set
      {
        SetPropertyValue("TestCase", ref _testCase, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-TestCaseSteps")]
    public Aria5SystemAdmin.Module.BusinessObjects.TestCaseSteps TestCaseSteps
    {
      get
      {
        return _testCaseSteps;
      }
      set
      {
        SetPropertyValue("TestCaseSteps", ref _testCaseSteps, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-TestRun")]
    public Aria5SystemAdmin.Module.BusinessObjects.TestRun TestRun
    {
      get
      {
        return _testRun;
      }
      set
      {
        SetPropertyValue("TestRun", ref _testRun, value);
      }
    }
    private XPCollection<AuditDataItemPersistent> changeHistory;
    public XPCollection<AuditDataItemPersistent> ChangeHistory
    {
      get
      {
        if (changeHistory == null)
        {
          changeHistory = AuditedObjectWeakReference.GetAuditTrail(Session, this);
        }
        return changeHistory;
      }
    }
    //public Aria5SystemAdmin.Module.BusinessObjects.Resources ResourceName
    //{
    //  get
    //  {
    //    return _resourceName;
    //  }
    //  set
    //  {
    //    SetPropertyValue("ResourceName", ref _resourceName, value);
    //  }
    //}
    public System.DateTime AddDate
    {
      get
      {
        return _addDate;
      }
      set
      {
        SetPropertyValue("AddDate", ref _addDate, value);
      }
    }
  }
}
