//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [RelatedEntity("Aria5-SystemAdmin-QABrowser")]
  public partial class QABrowser : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.String _description;
    private System.String _name;
    public QABrowser(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String Name
    {
      get
      {
        return _name;
      }
      set
      {
        SetPropertyValue("Name", ref _name, value);
      }
    }
    public System.String Description
    {
      get
      {
        return _description;
      }
      set
      {
        SetPropertyValue("Description", ref _description, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Environments-QABrowser")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.Environment> Environments
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.Environment>("Environments");
      }
    }
    private XPCollection<AuditDataItemPersistent> changeHistory;
    public XPCollection<AuditDataItemPersistent> ChangeHistory
    {
        get
        {
            if (changeHistory == null)
            {
                changeHistory = AuditedObjectWeakReference.GetAuditTrail(Session, this);
            }
            return changeHistory;
        }
    }
  }
}
