//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;
using DevExpress.Persistent.Validation;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  // Ras 8-11-2015 add validation to prevent add Risk after choose it,and prevent showing Resource or Due date if status not action planned [begin]
  // Ras 8-11-2015 add validation to prevent add Risk after choose it,and prevent showing Resource or Due date if status not action planned [end]
  [DefaultClassOptions]
  [XafDefaultProperty("Issue")]
  [RelatedEntity("Aria5-SystemAdmin-QAManagementIssues")]

  [Appearance("ProjectTemplate", AppearanceItemType = "ViewItem", TargetItems = "ProjectTemplate", Criteria = "ProjectTemplate!=null", Context = "DetailView", Enabled = false)]
  [Appearance("RiskRefrence", AppearanceItemType = "ViewItem", TargetItems = "RiskRefrence", Criteria = "RiskRefrence!=null", Context = "DetailView", Enabled = false)]
  [Appearance("Resource", AppearanceItemType = "ViewItem", TargetItems = "Resource", Criteria = "Status!='ActionPlanned'", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
  [Appearance("DueDate", AppearanceItemType = "ViewItem", TargetItems = "DueDate", Criteria = "Status!='ActionPlanned'", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
  public partial class QAManagementIssues : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private Aria5SystemAdmin.Module.BusinessObjects.QARisk _riskRefrence;
    private Aria5SystemAdmin.Module.BusinessObjects.Resources _resource;
    private System.DateTime _dueDate;
    private System.String _rootCause;
    public QAManagementIssues(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    private Aria5SystemAdmin.Module.BusinessObjects.ProjectTemplate _projectTemplate;
    private System.DateTime _addDate;
    private System.DateTime _closureDate;
    private Aria5SystemAdmin.Module.BusinessObjects.Resources _OpenBy;
    private Aria5SystemAdmin.Module.BusinessObjects.Resources _ClosedBy;
    private System.String _Issue;
    private System.String _Resolution;
    private System.String _Description;
    private Priorities? _Priority;
    private IssueTypes? _IssueType;
    private status? _status;
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    [RuleRequiredField]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    public Aria5SystemAdmin.Module.BusinessObjects.Resources OpenBy
    {
      get
      {
        return _OpenBy;
      }
      set
      {
        SetPropertyValue("OpenBy", ref _OpenBy, value);
      }
    }

    public Aria5SystemAdmin.Module.BusinessObjects.Resources ClosedBy
    {
      get
      {
        return _ClosedBy;
      }
      set
      {
        SetPropertyValue("ClosedBy", ref _ClosedBy, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(4000)]
    public System.String Description
    {
      get
      {
        return _Description;
      }
      set
      {
        SetPropertyValue("Description", ref _Description, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(4000)]
    public System.String Resolution
    {
      get
      {
        return _Resolution;
      }
      set
      {
        SetPropertyValue("Resolution", ref _Resolution, value);
      }
    }
    public System.DateTime AddDate
    {
      get
      {
        _addDate = DateTime.Now;
        return _addDate;
      }
      set
      {
        SetPropertyValue("AddDate", ref _addDate, value);
      }
    }
    public System.DateTime ClosureDate
    {
      get
      {
        return _closureDate;
      }
      set
      {
        SetPropertyValue("ClosureDate", ref _closureDate, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(4000)]
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    [RuleRequiredField]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    public System.String Issue
    {
      get
      {
        return _Issue;
      }
      set
      {
        SetPropertyValue("Issue", ref _Issue, value);
      }
    }
    public IssueTypes? IssueType
    {
      get
      {
        return _IssueType;
      }
      set
      {
        SetPropertyValue("IssueType", ref _IssueType, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("ManagementIssues-ProjectTemplate")]
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public Aria5SystemAdmin.Module.BusinessObjects.ProjectTemplate ProjectTemplate
    {
      get
      {
        return _projectTemplate;
      }
      set
      {
        SetPropertyValue("ProjectTemplate", ref _projectTemplate, value);
      }
    }
    //ATA make status default value is null and make it required 1/11/2017 [Start]

    public Priorities? Priority
    {
      get
      {
        return _Priority;
      }
      set
      {
        SetPropertyValue("Priority", ref _Priority, value);
      }
    }
    public enum IssueTypes
    {
      // Ras 8-11-2015 update Issue types enum with new issue types [begin]
      /*  Error,
        Question,
        Change,*/Technical,
      Resources,
      Scheduling,
      // Ras 8-11-2015 update Issue types enum with new issue types [end]
    }
    public enum Priorities
    {
      Low,
      High,
      medium
    }
    public enum status
    {
      // Ras 8-11-2015 update status enum with new status [begin]
      /*Open,
        InWork,
        Closed*/Reported,
      Analyzed,
      ActionPlanned,
      Closed,
      // Ras 8-11-2015 update status enum with new status [end]
    }
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public status? Status
    {
        //ATA make status default value is null and make it required 1/11/2017 [End]

      get
      {
        return _status;
      }
      set
      {
        SetPropertyValue("Status", ref _status, value);
      }
    }
    public System.String RootCause
    {
      get
      {
        return _rootCause;
      }
      set
      {
        SetPropertyValue("RootCause", ref _rootCause, value);
      }
    }
    //[Appearance("Resource", AppearanceItemType = "ViewItem", TargetItems = "Resource",Visibility = ViewItemVisibility.Hide,  Context = "DetailView")]
    public Aria5SystemAdmin.Module.BusinessObjects.Resources Resource
    {
      get
      {
        return _resource;
      }
      set
      {
        SetPropertyValue("Resource", ref _resource, value);
      }
    }
    public System.DateTime DueDate
    {
      get
      {
        return _dueDate;
      }
      set
      {
        SetPropertyValue("DueDate", ref _dueDate, value);
      }
    }
    public Aria5SystemAdmin.Module.BusinessObjects.QARisk RiskRefrence
    {
      get
      {
        return _riskRefrence;
      }
      set
      {
        SetPropertyValue("RiskRefrence", ref _riskRefrence, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("IssueFollowup-ManagementIssues")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QARiskFollowup> IssueFollowup
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QARiskFollowup>("IssueFollowup");
      }
    }
  }
}
