//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using System.Linq;

using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.Persistent.Base.General;
using System.ComponentModel;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp.Editors;

namespace Aria5SystemAdmin.Module.BusinessObjects
{
    [DefaultClassOptions]
    [RelatedEntity("Aria5-SystemAdmin-QANonComplains")]
    [Appearance("requiremenApperance", AppearanceItemType = "ViewItem", TargetItems = "Requirement", Criteria = "Requirement == Null", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
    [Appearance("UsecaseApperance", AppearanceItemType = "ViewItem", TargetItems = "UseCase", Criteria = "UseCase == Null", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
    [Appearance("TestcaseApperance", AppearanceItemType = "ViewItem", TargetItems = "ProjectEntity", Criteria = "ProjectEntity == Null", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
    [Appearance("projectentityApperance", AppearanceItemType = "ViewItem", TargetItems = "TestCase", Criteria = "TestCase == Null", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
    [Appearance("WBSApperance", AppearanceItemType = "ViewItem", TargetItems = "WBS", Criteria = "WBS == Null", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]

    public partial class QANonComplains : DevExpress.Persistent.BaseImpl.BaseObject ,ISupportNotifications
    {
        public QANonComplains(DevExpress.Xpo.Session session)
            : base(session)
        {

        }

        private severity _Severity;
        public severity Severity
        {
            get
            {
                return _Severity;
            }
            set
            {
                SetPropertyValue("Severity", ref _Severity, value);
            }
        }
        public enum severity
        {
            Critical,
            Major,
            Moderate,
            Minor,
            Cosmetic
        }


        private ComplainStatus _Status;
        public ComplainStatus Status
        {
            get
            {
                return _Status;
            }
            set
            {
                SetPropertyValue("Status", ref _Status, value);
            }
        }
        public enum ComplainStatus
        {
            New,
            InWork,
            Completed,
           
        }
        private QAComplainType _ComplainType;
        public QAComplainType NonComplainType
        {
            get
            {
                return _ComplainType;
            }
            set
            {
                SetPropertyValue("NonComplainType", ref _ComplainType, value);
            }
        }
       
        private ProjectTemplate _RelatedProject;
      [Association("QANonComplains-ProjectTemplate")]
        public ProjectTemplate RelatedProject
        {
            get
            {
                return _RelatedProject;
            }
            set
            {
                SetPropertyValue("RelatedProject", ref _RelatedProject, value);
            }
        }

        private Resources _Owner;
        public Resources Owner
        {
            get
            {
                return _Owner;
            }
            set
            {
                SetPropertyValue("_Owner", ref _Owner, value);
            }
        }

        private System.String _Description;
        [Size(200)]
        
        public System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                SetPropertyValue("Description", ref _Description, value);
            }
        }

        private DateTime _DueDate;
        public DateTime DueDate
        {
            get
            {
                return _DueDate;
            }
            set
            {
                SetPropertyValue("DueDate", ref _DueDate, value);
            }
        }

        private QAComplainActivity _NonComplainActivity;
        public QAComplainActivity NonComplainActivity
        {
            get
            {
                return _NonComplainActivity;
            }
            set
            {
                SetPropertyValue("NonComplainActivity", ref _NonComplainActivity, value);
            }
        }
        private NonComplianceItems _noncomplianceobjects;
        public NonComplianceItems NonComplianceObjects
        {
            get
            {
                return _noncomplianceobjects;
            }
            set
            {
                SetPropertyValue("NonComplianceObjects", ref _noncomplianceobjects, value);
            }
        }
        public enum NonComplianceItems
        {
            Requirement,
            UseCases,
            ProjectEntities,
            UseCasePoints,
            TestCases,
            Risks,
            ManagmentIssues,
            ProjectScope,
            TrackingTask,
            DesignTasks,
            ProgramingandTestingTasks,
            TestRun,
            Defects,
            DetailDesign,
            WBS,
            CreatePackage,
            TechnicalDocumentation,
            CheckInFiles,
            TestPlan
        }


        //ATA automate NOncompliance cycle 1/24/2017 [Start]
        private Requirement _requirement;
        public Requirement Requirement
        {
            get
            {
                return _requirement;
            }
            set
            {
                SetPropertyValue("Requirement", ref _requirement, value);
            }
        }

        private QAUseCase _usecase;
        public QAUseCase UseCase
        {
            get
            {
                return _usecase;
            }
            set
            {
                SetPropertyValue("UseCase", ref _usecase, value);
            }
        }

        private TestCase _testcase;
        public TestCase TestCase
        {
            get
            {
                return _testcase;
            }
            set
            {
                SetPropertyValue("TestCase", ref _testcase, value);
            }
        }
        private QAProjectEntity _projectentity;
        public QAProjectEntity ProjectEntity
        {
            get
            {
                return _projectentity;
            }
            set
            {
                SetPropertyValue("ProjectEntity", ref _projectentity, value);
            }
        }

        private QAWBS _wbs;
        public QAWBS WBS
        {
            get
            {
                return _wbs;
            }
            set
            {
                SetPropertyValue("WBS", ref _wbs, value);
            }
        }
        //ATA 14/7/2016 start notification task
        #region notification region
        private DateTime? alarmTime;
        [Browsable(false)]
        public DateTime? AlarmTime
        {
            get { return alarmTime; }
            set
            {
                alarmTime = value;
                if (value == null)
                {
                    RemindIn = null;
                    IsPostponed = false;
                }
            }
        }
        [Browsable(false)]
        public bool IsPostponed { get; set; }
        private string _notificationmessage;
        [Browsable(false)]
        [Size(4000)]
        public string NotificationMessage
        {
            get { return _notificationmessage; }
            set { SetPropertyValue("NotificationMessage", ref  _notificationmessage, value); }
        }
        [Browsable(false)]
        public TimeSpan? RemindIn { get; set; }
        [Browsable(false)]
        public object UniqueId
        {
            get { return Oid; }
        }
        #endregion
        //ATA 14/7/2016 end 
        //private ComplainType _Type;
        //public ComplainType Type
        //{
        //    get
        //    {
        //        return _Type;
        //    }
        //    set
        //    {
        //        SetPropertyValue("Type", ref _Type, value);
        //    }
        //}
        //public enum ComplainType
        //{
        //    New,
        //    InWork,
        //    Completed,

        //}

        //private System.String _Activity;
        //public System.String Activity
        //{
        //    get
        //    {
        //        return _Activity;
        //    }
        //    set
        //    {
        //        SetPropertyValue("Activity", ref _Activity, value);
        //    }
        //}
    }
}
