//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.Data.Filtering;
using DevExpress.Persistent.Validation;
using DevExpress.ExpressApp;
using DevExpress.Persistent.Base.General;
using System.ComponentModel;
using DevExpress.ExpressApp.Editors;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [XafDefaultProperty("Name")]
  [RelatedEntity("Aria5-SystemAdmin-QAProjectEntity")]
  [Appearance("EndDate", AppearanceItemType = "ViewItem", TargetItems = "Enddate", Criteria = "!IsCurrentUserInRole('IterationAdmin')", Context = "DetailView", Enabled = false)]
  [Appearance("ProjectTemplate", AppearanceItemType = "ViewItem", TargetItems = "ProjectTemplate", Criteria = "ProjectTemplate!=null", Context = "DetailView", Enabled = false)]
  [Appearance("MainFeatures", AppearanceItemType = "ViewItem", TargetItems = "MainFeatures", Criteria = "ProjectTemplate.Type!='CustomNonSoftware'", Context = "DetailView", Visibility = ViewItemVisibility.Hide)]
 
    
    [OptimisticLocking(OptimisticLockingBehavior.NoLocking)] 
  public partial class QAProjectEntity : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private Aria5SystemAdmin.Module.BusinessObjects.Requirement _requirement;
    private Aria5SystemAdmin.Module.BusinessObjects.QATestPlan _testPlan;
    private Aria5SystemAdmin.Module.BusinessObjects.Application_T _application;
    private System.Double _totalEstimate;
    private System.Double _testingTime;
    private System.Double _programmingTime;
    private System.Double _detailDesignTime;
    private System.Double _profOfConceptEstimationTime;
    private System.Double _entityEstimationTime;
    private System.String _profOfConceptLink;
    private System.String _specificationsLink;
    private Aria5SystemAdmin.Module.BusinessObjects.TrackingEntry _trackingNumber;
    private System.String _name;
    private Aria5SystemAdmin.Module.BusinessObjects.AriaObject _ariaObject;
    private Aria5SystemAdmin.Module.BusinessObjects.ProjectTemplate _projectTemplate;
    //ATA
    private System.Double totalactualdetaildesign;
    private System.Double totalactualprogramming;
    private Statues? _statues;
    //ATA
    /*ATA ,1,23/3/2016, Baselineflag , add 2 new attribute to calcuate end date,
   and disable or enable edit or delet for this enddate property according to loginuser [start] 
   */private System.DateTime _enddate;
    //[NonPersistent]
    //[DevExpress.Persistent.Base.VisibleInDetailViewAttribute(false)]
    //[DevExpress.Persistent.Base.VisibleInListViewAttribute(false)]
    //[DevExpress.Persistent.Base.VisibleInLookupListViewAttribute(false)]
    //public string LoginUser { get; set; }
    //private XPCollection<TrackingEntry> filteredlist;
    /*ATA ,1,23/3/2016, Baselineflag , add 2 new attribute to calcuate end date,
      and disable or enable edit or delet for this enddate property according to loginuser [end] 
     */public QAProjectEntity(DevExpress.Xpo.Session session)
      : base(session)
    {
      //ATA get login user ,23/3/2016
      // LoginUser = SecuritySystem.CurrentUserName.Trim().ToUpper();
      // filteredlist = new XPCollection<TrackingEntry>(this.Session, CriteriaOperator.Parse("IsNull([ProjectEntity])"));
      //ATA , end 
    }
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    [DevExpress.Xpo.AssociationAttribute("QAProjectEntities-ProjectTemplate")]
    [RuleRequiredField]
    public Aria5SystemAdmin.Module.BusinessObjects.ProjectTemplate ProjectTemplate
    {
      get
      {
        if (_projectTemplate != null)
        {
          //ATA, 1,23/3/2016,check if _enddate not calculated and it is assign to a project then calculate it according to project type [start]
          //{
          //  this.Application = _projectTemplate.Application;
          //  //this.AriaObject = Application.AriaObjects;
          //}
          if (this._enddate == DateTime.MinValue)
          {
            if (_projectTemplate.Type.ToString() == "Key")
            {
              //this._enddate = CalcEnddate(_projectTemplate.StartDate,2);
              this._enddate = CalcEndate.CalcEnddate(_projectTemplate.StartDate, 2);
            }
            else
            {
              this._enddate = _projectTemplate.EndDate;
            }
          }
        }
        //ATA, 1,23/3/2016,check if _enddate not calculated and it is assign to a project then calculate it according to project type [end]
        return _projectTemplate;
      }
      set
      {
        SetPropertyValue("ProjectTemplate", ref _projectTemplate, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("QAProjectEntities-QAUseCases")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QAUseCase> QAUseCases
    {
      get
      {
        //  this.Requirements.Add(this.QAUseCases[0].Requirement);
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QAUseCase>("QAUseCases");
      }
    }
    //[RuleRequiredField]
    public Aria5SystemAdmin.Module.BusinessObjects.AriaObject AriaObject
    {
      get
      {
        return _ariaObject;
      }
      set
      {
        SetPropertyValue("AriaObject", ref _ariaObject, value);
        //if (_ariaObject == value)
        //  return;
        //Aria5SystemAdmin.Module.BusinessObjects.AriaObject prevAriaObject = _ariaObject;
        //_ariaObject = value;
        //if (IsLoading)
        //  return;
        //if (prevAriaObject != null && prevAriaObject.QAProjectEntity == this)
        //  prevAriaObject.QAProjectEntity = null;
        //if (_ariaObject != null)
        //  _ariaObject.QAProjectEntity = this;
        //OnChanged("AriaObject");
      }
    }
    //ATA
    //ATA 
    //[DataSourceProperty("QAUseCase.Requirement")]
    [DevExpress.Xpo.AssociationAttribute("Requirements-QAProjectEntity")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.Requirement> Requirements
    {
      get
      {
        ////ATA
        //for (int i = 0; i < QAUseCases.Count; i++)
        //{
        //    if (this.QAUseCases[i] != null && this.QAUseCases[i].Requirement != null)
        //    {
        //      if (!this.Requirements.Contains(this.QAUseCases[i].Requirement))
        //        {
        //            this.Requirements.Add(this.QAUseCases[i].Requirement);
        //        }
        //    }
        //}
        ////ATA
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.Requirement>("Requirements");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-QAProjectEntity")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QAAttachement> Attachements
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QAAttachement>("Attachements");
      }
    }
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    [Size(200)]
    [RuleRequiredField]
    public System.String Name
    {
      get
      {
        return _name;
      }
      set
      {
        SetPropertyValue("Name", ref _name, value);
      }
    }
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    [DevExpress.Xpo.AssociationAttribute("QAProjectEntities-Application")]
    [RuleRequiredField]
    public Aria5SystemAdmin.Module.BusinessObjects.Application_T Application
    {
      get
      {
        return _application;
      }
      set
      {
        SetPropertyValue("Application", ref _application, value);
      }
    }
    //  [DataSourceCriteria("ProjectEntity.Name = 'aaaa'")]
    // [DataSourceProperty("filteredlist")]
    //[DataSourceCriteriaProperty("IsNull(ProjectEntity)")]
    // [RuleRequiredField]
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public Aria5SystemAdmin.Module.BusinessObjects.TrackingEntry TrackingNumber
    {
      get
      {
        // 8-10 QA Enhance Phase 3,Filtering Issue[Start]
        //if (Application!=null & ProjectTemplate!=null)
        //{
        //    XPCollection<TrackingEntry> Collection= new XPCollection<TrackingEntry>(this.Session, CriteriaOperator.Parse("ProjectTemplate='" + this.ProjectTemplate.Oid +  "' and Application ='" + this.Application.Oid + "' "));
        //    Collection.Load();
        //    _trackingNumber = Collection;                                 
        //}
        return _trackingNumber;
      }
      set
      {
        SetPropertyValue("TrackingNumber", ref _trackingNumber, value);
        if (TrackingNumber != null)
        {
          //  TrackingNumber.ProjectEntity = this;
          if (TrackingNumber.Entity != null)
          {
            AriaObject = TrackingNumber.Entity;
          }
          if (TrackingNumber.Application != null)
          {
            Application = TrackingNumber.Application;
          }
        }
        //if (TrackingNumber.Entity != null && TrackingNumber.Entity.ObjectDescription != null)
        //{
        //  Name = TrackingNumber.Entity.ObjectDescription;
        //}
      }
    }
    //ATA 30/5/2016 [start]
    // [RuleRequiredField]
    //ATA 30/5/2016 [end]
    [EditorAlias("HyperLinkStringPropertyEditor")]
    public System.String SpecificationsLink
    {
      get
      {
        return _specificationsLink;
      }
      set
      {
        SetPropertyValue("SpecificationsLink", ref _specificationsLink, value);
      }
    }
    [Size(200)]
    public System.String ProfOfConceptLink
    {
      get
      {
        return _profOfConceptLink;
      }
      set
      {
        SetPropertyValue("ProfOfConceptLink", ref _profOfConceptLink, value);
      }
    }
    // [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public System.Double EntityEstimationTime
    {
      get
      {
        //if (_detailDesignTime != null)
        //{
        //  //  this.DetailDesignTime = _profOfConceptEstimationTime + _entityEstimationTime * 1.5;
        // //   this.TestingTime = _entityEstimationTime * 0.25;
        //  //  this.ProgrammingTime = _testingTime + _entityEstimationTime * 1.5;
        //}
        return _entityEstimationTime;
      }
      set
      {
        SetPropertyValue("EntityEstimationTime", ref _entityEstimationTime, value);
      }
    }
    [DevExpress.Persistent.Base.VisibleInDetailViewAttribute(false)]
    public System.Double ProfOfConceptEstimationTime
    {
      get
      {
        return _profOfConceptEstimationTime;
      }
      set
      {
        SetPropertyValue("ProfOfConceptEstimationTime", ref _profOfConceptEstimationTime, value);
      }
    }
    // [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public System.Double DetailDesignTime
    {
      get
      {
        return _detailDesignTime;
      }
      set
      {
        SetPropertyValue("DetailDesignTime", ref _detailDesignTime, value);
      }
    }
    public System.Double ProgrammingTime
    {
      get
      {
        return _programmingTime;
      }
      set
      {
        SetPropertyValue("ProgrammingTime", ref _programmingTime, value);
      }
    }
    [DevExpress.Persistent.Base.VisibleInDetailViewAttribute(false)]
    public System.Double TestingTime
    {
      get
      {
        return _testingTime;
      }
      set
      {
        SetPropertyValue("TestingTime", ref _testingTime, value);
      }
    }
    public System.Double TotalEstimate
    {
      get
      {
        if (true)
        {
        }
        return _totalEstimate;
      }
      set
      {
        SetPropertyValue("TotalEstimate", ref _totalEstimate, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("MainFeatures-ProjectEntity")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QAMainFeature> MainFeatures
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QAMainFeature>("MainFeatures");
      }
    }
    private XPCollection<AuditDataItemPersistent> changeHistory;
    public XPCollection<AuditDataItemPersistent> ChangeHistory
    {
      get
      {
        if (changeHistory == null)
        {
          changeHistory = AuditedObjectWeakReference.GetAuditTrail(Session, this);
        }
        return changeHistory;
      }
    }
    [DevExpress.Xpo.AssociationAttribute("ProjectEntities-TestPlan")]
    public Aria5SystemAdmin.Module.BusinessObjects.QATestPlan TestPlan
    {
      get
      {
        return _testPlan;
      }
      set
      {
        SetPropertyValue("TestPlan", ref _testPlan, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("EntitySystemDesign-QAProjectEntity")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.EntitySystemDesign> EntitySystemDesign
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.EntitySystemDesign>("EntitySystemDesign");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("DetailDesignEstimates-QAProjectEntity")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.DesignDetailEstimate> DetailDesignEstimates
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.DesignDetailEstimate>("DetailDesignEstimates");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TestCases-QAProjectEntity")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.TestCase> TestCases
    {
      get
      {
        //XPCollection<TestCase> x = GetCollection<Aria5SystemAdmin.Module.BusinessObjects.TestCase>("TestCases");
        //x.Filter = new BinaryOperator("ProjectEntity", Oid, BinaryOperatorType.Equal);
        //x.Load();
        //if (x.Count > 0)
        //{
        //  return x;
        //}
        //else
        //{
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.TestCase>("TestCases");
        // }
      }
    }
    [DevExpress.Xpo.AssociationAttribute("UserInterfaceRules-ProjectEntity")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QAUserInterfaceRules> UserInterfaceRules
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QAUserInterfaceRules>("UserInterfaceRules");
      }
    }
    //public override void AfterConstruction()
    //{
    //    base.AfterConstruction();
    //    //ATA
    //    //for (int i = 0; i < QAUseCases.Count; i++)
    //    //{
    //    //    if (this.QAUseCases[i] != null && this.QAUseCases[i].Requirement != null)
    //    //    {
    //    //        if (!this.Requirements.Contains(this.QAUseCases[i].Requirement))
    //    //        {
    //    //            this.Requirements.Add(this.QAUseCases[i].Requirement);
    //    //        }
    //    //    }
    //    //}
    //    //ATA
    //}
    [DevExpress.Xpo.AssociationAttribute("QAProjectEntities-Requirement")]
    public Aria5SystemAdmin.Module.BusinessObjects.Requirement Requirement
    {
      get
      {
        return _requirement;
      }
      set
      {
        SetPropertyValue("Requirement", ref _requirement, value);
      }
    }
    //ATA ,1,23/3/2016 add new property end date to calculate the edit end date for this usecase [start]
    public System.DateTime Enddate
    {
      get
      {
        return _enddate;
      }
      set
      {
        SetPropertyValue("Enddate", ref _enddate, value);
      }
    }
    //ATA ,1,23/3/2016 add new property end date to calculate the edit end date for this usecase [End]
    public System.Double TotalActualDetaildesign
    {
      get
      {
        return totalactualdetaildesign;
      }
      set
      {
        SetPropertyValue("TotalActualDetaildesign", ref totalactualdetaildesign, value);
      }
    }
    public System.Double TotalActualProgramming
    {
      get
      {
        return totalactualprogramming;
      }
      set
      {
        SetPropertyValue("TotalActualProgramming", ref totalactualprogramming, value);
      }
    }
    [RuleRequiredField]
    public Statues? ProjectEntity_Statues
    {
      get
      {
        return _statues;
      }
      set
      {
        SetPropertyValue("ProjectEntity_Statues", ref _statues, value);
      }
    }
    public enum Statues
    {
      New,
      Cancel,
      InWork,
      Complete
    }
    //ATA 14/7/2016 start notification task
    //ATA 14/7/2016 end 
    private ApproveStatu _approvestatus;
    public ApproveStatu ApproveStatus
    {
      get
      {
        return _approvestatus;
      }
      set
      {
        SetPropertyValue("ApproveStatus", ref _approvestatus, value);
      }
    }
    public enum ApproveStatu
    {
      New,
      Ready
    }
  }
}
