//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [XafDefaultProperty("Rolename")]
  [RelatedEntity("Aria5-SystemAdmin-QAResourceRoles")]


  [Appearance("QAResourceShare", AppearanceItemType = "ViewItem", TargetItems = "QAResourceShare", Criteria = "QAResourceShare!=null", Context = "DetailView", Enabled = false)]

  public partial class QAResourceRoles : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private Aria5SystemAdmin.Module.BusinessObjects.QAResourceShare _qAResourceShare;
    public QAResourceRoles(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    // Sara.N, Customize Clonning of usecase Points [Start]
    public QAResourceRoles(DevExpress.Xpo.Session session,QAResourceRoles RS)
        : base(session)
    {
        this.Description = RS.Description;
        this.EndtDate = RS.EndtDate;
        this.QAResourceShare = RS.QAResourceShare;
        this.Rolename = RS.Rolename;
        this.StartDate = RS.StartDate;
        
    }
    // Sara.N, Customize Clonning of usecase Points [End]
    private System.String _Rolename;
    public System.String Rolename
    {
      get
      {
        return _Rolename;
      }
      set
      {
        SetPropertyValue("Rolename", ref _Rolename, value);
      }
    }
    private System.String _Description;
    public System.String Description
    {
      get
      {
        return _Description;
      }
      set
      {
        SetPropertyValue("Description", ref _Description, value);
      }
    }
    private System.DateTime _StartDate;
    public System.DateTime StartDate
    {
      get
      {
        return _StartDate;
      }
      set
      {
        SetPropertyValue("StartDate", ref _StartDate, value);
      }
    }
    private System.DateTime _EndtDate;
    public System.DateTime EndtDate
    {
      get
      {
        return _EndtDate;
      }
      set
      {
        SetPropertyValue("EndDate", ref _EndtDate, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("RolesandResponsabilities-QAResourceShare")]
    public Aria5SystemAdmin.Module.BusinessObjects.QAResourceShare QAResourceShare
    {
      get
      {
        return _qAResourceShare;
      }
      set
      {
        SetPropertyValue("QAResourceShare", ref _qAResourceShare, value);
      }
    }
  }
}
