//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
    [DefaultClassOptions]
    [RelatedEntity("Aria5-SystemAdmin-QATestCaseChild")]
    [MapInheritance(MapInheritanceType.ParentTable)]
    [Appearance("ProjectTemplate", AppearanceItemType = "ViewItem", TargetItems = "ProjectTemplate", Criteria = "ProjectTemplate!=null", Context = "DetailView", Enabled = false)]
    [Appearance("Application", AppearanceItemType = "ViewItem", TargetItems = "Application", Criteria = "Application!=null", Context = "DetailView", Enabled = false)]
    public partial class QATestCaseChild : TestCase
    {
    public QATestCaseChild(DevExpress.Xpo.Session session)
      : base(session)
    {

    }
  }
}
