//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.Persistent.Validation;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [RelatedEntity("Aria5-SystemAdmin-QAUsecaseActors")]
  public partial class QAUsecaseActors : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private Aria5SystemAdmin.Module.BusinessObjects.QAUseCaseActorCategory _actorName;
    private Aria5SystemAdmin.Module.BusinessObjects.QAUseCasePoints _useCasePoints;
    public QAUsecaseActors(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    // Sara.N, Customize Clonning of usecase Points [Start]
    public QAUsecaseActors(DevExpress.Xpo.Session session, QAUsecaseActors UsecaseActors)
      : base(session)
    {
      this.ActorName = UsecaseActors.ActorName;
      this.Complexity = UsecaseActors.Complexity;
      this.NumberOfUseCases = UsecaseActors.NumberOfUseCases;
      this.UAW = UsecaseActors.UAW;
      this.UseCasePoints = UsecaseActors.UseCasePoints;
    }
    // Sara.N, Customize Clonning of usecase Points [End]
    private Category category;
    private System.Int16 _NumberOfUseCases;
    private short _Totalweight;
    public enum Category
    {
      Simple,
      Average,
      Complex
    }
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
      //ATA enhance the systema dmin to set the required field at all screens 1/9/2017 [start]
      [RuleRequiredField]
    //ATA enhance the systema dmin to set the required field at all screens 1/9/2017 [End]

    public System.Int16 NumberOfUseCases
    {
      get
      {
        return _NumberOfUseCases;
      }
      set
      {
        SetPropertyValue("NumberOfUseCases", ref _NumberOfUseCases, value);
      }
    }
    private short _UAW;
    //ATA enhance the systema dmin to set the required field at all screens 1/9/2017 [start]
    [RuleRequiredField]
    //ATA enhance the systema dmin to set the required field at all screens 1/9/2017 [End]
    public short UAW
    {
      get
      {
        if (category == Category.Simple)
        {
          _UAW = (short)(_NumberOfUseCases * 1);
        }
        else
          if (category == Category.Average)
            _UAW = (short)(_NumberOfUseCases * 2);
          else
            if (category == Category.Complex)
              _UAW = (short)(_NumberOfUseCases * 3);
        return _UAW;
      }
      set
      {
        SetPropertyValue("UAW", ref _UAW, value);
      }
    }
    //ATA enhance the systema dmin to set the required field at all screens 1/9/2017 [start]
    [RuleRequiredField]
    //ATA enhance the systema dmin to set the required field at all screens 1/9/2017 [End]
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public Category Complexity
    {
      get
      {
        return category;
      }
      set
      {
        SetPropertyValue("Complexity", ref category, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("UsecaseActors-UseCasePoints")]
    //ATA enhance the systema dmin to set the required field at all screens 1/9/2017 [start]
    [RuleRequiredField]
    //ATA enhance the systema dmin to set the required field at all screens 1/9/2017 [End]
    public Aria5SystemAdmin.Module.BusinessObjects.QAUseCasePoints UseCasePoints
    {
      get
      {
        return _useCasePoints;
      }
      set
      {
        SetPropertyValue("UseCasePoints", ref _useCasePoints, value);
      }
    }
    //private Aria5SystemAdmin.Module.BusinessObjects.QAUseCaseActorCategory _Actors;
    //public QAUseCaseActorCategory Actors
    //{
    //  get
    //  {
    //    return _Actors;
    //  }
    //  set
    //  {
    //    SetPropertyValue("Actors", ref _Actors, value);
    //  }
    //}
    //ATA enhance the systema dmin to set the required field at all screens 1/9/2017 [start]
    [RuleRequiredField]
    //ATA enhance the systema dmin to set the required field at all screens 1/9/2017 [End]
    public Aria5SystemAdmin.Module.BusinessObjects.QAUseCaseActorCategory ActorName
    {
      get
      {
        return _actorName;
      }
      set
      {
        SetPropertyValue("ActorName", ref _actorName, value);
      }
    }
  }
}
