//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  public partial class QAUseCasePoint : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.String _useCaseCategory;
    public QAUseCasePoint(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public System.String UseCaseCategory
    {
      get
      {
        return _useCaseCategory;
      }
      set
      {
        SetPropertyValue("UseCaseCategory", ref _useCaseCategory, value);
      }
    }
  }
}
