//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.Persistent.Validation;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [XafDefaultProperty("FlowType")]
  [RelatedEntity("Aria5-SystemAdmin-QAUseCaseFlow")]
  [Appearance("QAUseCase", AppearanceItemType = "ViewItem", TargetItems = "QAUseCase", Criteria = "QAUseCase!=null", Context = "DetailView", Enabled = false)]
  public partial class QAUseCaseFlow : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private Aria5SystemAdmin.Module.BusinessObjects.QAUseCase _qAUseCase;
    private System.String _notes;
    private System.String _postConditions;
    private System.String _preConditions;
    private System.String _flowType;
    public QAUseCaseFlow(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    [DevExpress.Xpo.AssociationAttribute("QAUseCaseSteps-QAUseCaseFlow")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QAUseCaseSteps> QAUseCaseSteps
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QAUseCaseSteps>("QAUseCaseSteps");
      }
    }
       [Size(200)]
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    [RuleRequiredField]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    public System.String FlowType
    {
      get
      {
        return _flowType;
      }
      set
      {
        SetPropertyValue("FlowType", ref _flowType, value);
      }
    }
       [Size(1000)]
    public System.String PreConditions
    {
      get
      {
        return _preConditions;
      }
      set
      {
        SetPropertyValue("PreConditions", ref _preConditions, value);
      }
    }
       [Size(1000)]
    public System.String PostConditions
    {
      get
      {
        return _postConditions;
      }
      set
      {
        SetPropertyValue("PostConditions", ref _postConditions, value);
      }
    }
       [Size(1000)]
    public System.String Notes
    {
      get
      {
        return _notes;
      }
      set
      {
        SetPropertyValue("Notes", ref _notes, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("QAUseCaseFlows-QAUseCase")]
    public Aria5SystemAdmin.Module.BusinessObjects.QAUseCase QAUseCase
    {
      get
      {
        return _qAUseCase;
      }
      set
      {
        SetPropertyValue("QAUseCase", ref _qAUseCase, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Comments-QAUseCaseFlow")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.Comments> Comments
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.Comments>("Comments");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-QAUseCaseFlow")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QAAttachement> Attachements
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QAAttachement>("Attachements");
      }
    }
    private XPCollection<AuditDataItemPersistent> changeHistory;
    public XPCollection<AuditDataItemPersistent> ChangeHistory
    {
        get
        {
            if (changeHistory == null)
            {
                changeHistory = AuditedObjectWeakReference.GetAuditTrail(Session, this);
            }
            return changeHistory;
        }
    }
  }
}
