//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.Persistent.Validation;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  //[Appearance("TestCase", AppearanceItemType = "ViewItem", TargetItems = "TestCase",
  //Criteria = "TestCase!=null", Context = "DetailView", Enabled = false)]
  //ATA to fix error that the object is modified by another user 
  [DefaultClassOptions]
  [XafDefaultProperty("Number")]
  [RelatedEntity("Aria5-SystemAdmin-TestCaseSteps")]
  [OptimisticLocking(OptimisticLockingBehavior.NoLocking)]
  public partial class TestCaseSteps : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private System.Int64 _number;
    private Aria5SystemAdmin.Module.BusinessObjects.TestCase _testCase;
    private System.Boolean _passed;
    private System.String _actualResult;
    private System.String _expectedResult;
    private System.String _action;
    //ATA , 1 , add this 2 properties  as mr.ahmed request to test the time performance [start]
    private System.Int32 _expectedperformance;
    private System.Int32 _actualperformance;
    //ATA , 1 , add this 2 properties  as mr.ahmed request to test the time performance [end]
    public TestCaseSteps(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    public TestCaseSteps(DevExpress.Xpo.Session session, TestCaseSteps testCaseStep)
      : base(session)
    {
      this.Passed = false;
      this.Number = testCaseStep.Number;
      this.ExpectedResult = testCaseStep.ExpectedResult;
      this.ActualResult = testCaseStep.ActualResult;
      this.Action = testCaseStep.Action;
      this.Expectedperformance = testCaseStep.Expectedperformance;
      this.Actualperformance = testCaseStep.Actualperformance;
    }
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    [Size(200)]
    [RuleRequiredField]
    public System.String Action
    {
      get
      {
        return _action;
      }
      set
      {
        SetPropertyValue("Action", ref _action, value);
      }
    }
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    [Size(1000)]
    [RuleRequiredField]
    public System.String ExpectedResult
    {
      get
      {
        return _expectedResult;
      }
      set
      {
        SetPropertyValue("ExpectedResult", ref _expectedResult, value);
      }
    }
    [Size(1000)]
    public System.String ActualResult
    {
      get
      {
        return _actualResult;
      }
      set
      {
        SetPropertyValue("ActualResult", ref _actualResult, value);
      }
    }
    public System.Boolean Passed
    {
      get
      {
        return _passed;
      }
      set
      {
        SetPropertyValue("Passed", ref _passed, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TestCaseSteps-TestCase")]
    public Aria5SystemAdmin.Module.BusinessObjects.TestCase TestCase
    {
      get
      {
        return _testCase;
      }
      set
      {
        SetPropertyValue("TestCase", ref _testCase, value);
        if (!IsLoading && !IsSaving && value != null && this.Oid == Guid.Empty && this.Number == 0)
        {
          this.Number = value.TestCaseSteps.Count + 1;
        }
      }
    }
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    [RuleRequiredField]
    public System.Int64 Number
    {
      get
      {
        return _number;
      }
      set
      {
        SetPropertyValue("Number", ref _number, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Comments-TestCaseSteps")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.Comments> Comments
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.Comments>("Comments");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-TestCaseSteps")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QAAttachement> Attachements
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QAAttachement>("Attachements");
      }
    }
    private XPCollection<AuditDataItemPersistent> changeHistory;
    public XPCollection<AuditDataItemPersistent> ChangeHistory
    {
      get
      {
        if (changeHistory == null)
        {
          changeHistory = AuditedObjectWeakReference.GetAuditTrail(Session, this);
        }
        return changeHistory;
      }
    }
    //ATA , 1 , add this 2 properties  as mr.ahmed request to test the time performance [start]
    public System.Int32 Expectedperformance
    {
      get
      {
        return _expectedperformance;
      }
      set
      {
        SetPropertyValue("Expectedperformance", ref _expectedperformance, value);
      }
    }
    public System.Int32 Actualperformance
    {
      get
      {
        return _actualperformance;
      }
      set
      {
        SetPropertyValue("Actualperformance", ref _actualperformance, value);
      }
    }
    //ATA , 1 , add this 2 properties  as mr.ahmed request to test the time performance [end]
  }
}
