//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.ExpressApp;
using DevExpress.Persistent.Validation;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  //[OptimisticLocking(false)]
  //[Appearance("EndDate", AppearanceItemType = "ViewItem", TargetItems = "Enddate", Criteria = "!IsCurrentUserInRole('IterationAdmin')", Context = "DetailView", Enabled = false)]
  //ATA this object was modified or deleting by another user error while select test cases [satrt]
  //ATA this object was modified or deleting by another user error while select test cases [End]
  [Appearance("SelectTestCases", AppearanceItemType = "Action", TargetItems = "SelectTestCases", Criteria = "!IsCurrentUserInRole('Quality')", Context = "DetailView", Enabled = false)]
  [Appearance("ProjectTemplate", AppearanceItemType = "ViewItem", TargetItems = "ProjectTemplate,Application", Criteria = "ProjectTemplate!=null", Context = "DetailView", Enabled = false)]
  [DefaultClassOptions]
  [RelatedEntity("Aria5-SystemAdmin-TestRun")]
  [XafDefaultProperty("Name")]
  [OptimisticLocking(OptimisticLockingBehavior.NoLocking)]
  public partial class TestRun : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private Aria5SystemAdmin.Module.BusinessObjects.QATestPlan _testPlan;
    private Aria5SystemAdmin.Module.BusinessObjects.Application_T _application;
    private Aria5SystemAdmin.Module.BusinessObjects.TrackingEntry _trackingEntry;
    private Aria5SystemAdmin.Module.BusinessObjects.AriaSecuritySystemUser _assignedUser;
    private Aria5SystemAdmin.Module.BusinessObjects.ProjectTemplate _projectTemplate;
    /*ATA ,1,bgn,15/3/2016, Baselineflag , add 2 new attribute to calcuate end date,
     and disable or enable edit or delet for this enddate property according to loginuser  
     */private System.DateTime _enddate;
    //[NonPersistent]
    //[DevExpress.Persistent.Base.VisibleInDetailViewAttribute(false)]
    //[DevExpress.Persistent.Base.VisibleInListViewAttribute(false)]
    //[DevExpress.Persistent.Base.VisibleInLookupListViewAttribute(false)]
    //public string LoginUser { get; set; }
    //ATA, end  
    private Aria5SystemAdmin.Module.BusinessObjects.QADefect _qADefect;
    private System.String _description;
    private System.String _name;
    public TestRun(DevExpress.Xpo.Session session)
      : base(session)
    {
      //LoginUser = SecuritySystem.CurrentUserName.Trim().ToUpper();
    }
    public TestRun(DevExpress.Xpo.Session session, TestRun testRun)
      : base(session)
    {
      this.Name = testRun.Name + " " + DateTime.Now.ToString() + "_Copy";
      this.TrackingEntry = testRun.TrackingEntry;
      this.ProjectTemplate = testRun.ProjectTemplate;
      //ATA add the test plan also to the copied test run 6/14/2017 [start]
      this.TestPlan = testRun.TestPlan;
      //ATA add the test plan also to the copied test run 6/14/2017 [End]
      this.Description = testRun.Description;
      foreach (var Environmwnt in testRun.Environments)
        this.Environments.Add(new Environment(session, Environmwnt));
      foreach (var testCase in testRun.TestCases)
        this.TestCases.Add(new TestCase(session, testCase));
    }
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    [Size(200)]
    [RuleRequiredField]
    public System.String Name
    {
      get
      {
        return _name;
      }
      set
      {
        SetPropertyValue("Name", ref _name, value);
      }
    }
    [Size(8000)]
    public System.String Description
    {
      get
      {
        return _description;
      }
      set
      {
        SetPropertyValue("Description", ref _description, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Environments-TestRuns")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.Environment> Environments
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.Environment>("Environments");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Comments-TestRun")]
    [DevExpress.Xpo.AggregatedAttribute]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.Comments> Comments
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.Comments>("Comments");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TestCases-TestRuns")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.TestCase> TestCases
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.TestCase>("TestCases");
      }
    }
    public Aria5SystemAdmin.Module.BusinessObjects.QADefect QADefect
    {
      get
      {
        return _qADefect;
      }
      set
      {
        if (_qADefect == value)
          return;
        Aria5SystemAdmin.Module.BusinessObjects.QADefect prevQADefect = _qADefect;
        _qADefect = value;
        if (IsLoading)
          return;
        if (prevQADefect != null && prevQADefect.TestRun == this)
          prevQADefect.TestRun = null;
        if (_qADefect != null)
          _qADefect.TestRun = this;
        OnChanged("QADefect");
      }
    }
    //ATA add rule required to this field project template 2\2\2017
    [DevExpress.Xpo.AssociationAttribute("TestRuns-ProjectTemplate")]
    [RuleRequiredField]
    public Aria5SystemAdmin.Module.BusinessObjects.ProjectTemplate ProjectTemplate
    {
      get
      {
        //ATA, 1,bgn,14/3/2016,check if _enddate not calculated and it is assign to a project then calculate it according to project type 
        if (_projectTemplate != null)
        {
          if (this._enddate == DateTime.MinValue)
          {
            if (_projectTemplate.Type.ToString() == "Key")
            {
              this._enddate = CalcEndate.CalcEnddate(_projectTemplate.StartDate, 4);
            }
            else
            {
              this._enddate = _projectTemplate.EndDate;
            }
            //this._enddate = CalcEnddate(_projectTemplate.StartDate, 3);
          }
          _application = _projectTemplate.Application;
        }
        //ATA, end 
        return _projectTemplate;
      }
      set
      {
        SetPropertyValue("ProjectTemplate", ref _projectTemplate, value);
      }
    }
    //ATA , 1, bgn , define the end date property
    public System.DateTime Enddate
    {
      get
      {
        return _enddate;
      }
      set
      {
        SetPropertyValue("Enddate", ref _enddate, value);
      }
    }
    public Aria5SystemAdmin.Module.BusinessObjects.AriaSecuritySystemUser AssignedUser
    {
      get
      {
        return _assignedUser;
      }
      set
      {
        SetPropertyValue("AssignedUser", ref _assignedUser, value);
      }
    }
    //ATA , end 
    //ATA add new field named testers to specify which resource will run this test plan 11/19/2017 [start]
    private Aria5SystemAdmin.Module.BusinessObjects.Resources _tester;
    //  [RuleRequiredField]
    public Aria5SystemAdmin.Module.BusinessObjects.Resources Tester
    {
      get
      {
        return _tester;
      }
      set
      {
        SetPropertyValue("Tester", ref _tester, value);
      }
    }
    //ATA add new field named testers to specify which resource will run this test plan 11/19/2017 [end]
    [DevExpress.Xpo.AssociationAttribute("Attachements-TestRun")]
    [DevExpress.Xpo.AggregatedAttribute]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QAAttachement> Attachements
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QAAttachement>("Attachements");
      }
    }
    private XPCollection<AuditDataItemPersistent> changeHistory;
    public XPCollection<AuditDataItemPersistent> ChangeHistory
    {
      get
      {
        if (changeHistory == null)
        {
          changeHistory = AuditedObjectWeakReference.GetAuditTrail(Session, this);
        }
        return changeHistory;
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TestRuns-TrackingEntry")]
    public Aria5SystemAdmin.Module.BusinessObjects.TrackingEntry TrackingEntry
    {
      get
      {
        return _trackingEntry;
      }
      set
      {
        SetPropertyValue("TrackingEntry", ref _trackingEntry, value);
        if (!IsSaving && !IsLoading && value != null)
        {
          this.ProjectTemplate = value.ProjectTemplate;
        }
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TestRuns-Application")]
    public Aria5SystemAdmin.Module.BusinessObjects.Application_T Application
    {
      get
      {
        return _application;
      }
      set
      {
        SetPropertyValue("Application", ref _application, value);
      }
    }
    //[RuleRequiredField]
    //public Aria5SystemAdmin.Module.BusinessObjects.QATestPlan TestPlan
    //{
    //    get
    //    {
    //        return _testPlan;
    //    }
    //    set
    //    {
    //        if (_testPlan == value)
    //            return;
    //        Aria5SystemAdmin.Module.BusinessObjects.QATestPlan prevTestPlan = _testPlan;
    //        _testPlan = value;
    //        if (IsLoading)
    //            return;
    //        if (prevTestPlan != null && prevTestPlan.TestRun == this)
    //            prevTestPlan.TestRun = null;
    //        if (_testPlan != null)
    //            _testPlan.TestRun = this;
    //        OnChanged("TestPlan");
    //    }
    //}
    //ATA 19/5/2016 enhance relation between test plan and test run to be one to many [start ]
    [RuleRequiredField]
    [DevExpress.Xpo.AssociationAttribute("QATestPlan-TestRun")]
    public Aria5SystemAdmin.Module.BusinessObjects.QATestPlan TestPlan
    {
      get
      {
        return _testPlan;
      }
      set
      {
        SetPropertyValue("TestPlan", ref _testPlan, value);
      }
    }
    //ATA 19/5/2016 enhance relation between test plan and test run to be one to many [End]
    //ATA add defect as a list under the test run 4/241/2017 [star]
    [Association("Testrun-Defects")]
    public XPCollection<QADefect> Defects
    {
      get
      {
        return GetCollection<QADefect>("Defects");
      }
    }
    //ATA add defect as a list under the test run 4/241/2017 [End]
    //mmt
    private Aria5SystemAdmin.Module.BusinessObjects.ApplicationBuild_T _ApplicationBuild;
    [DevExpress.Xpo.AssociationAttribute("ApplicationBuild_T-TestRuns")]
    public ApplicationBuild_T ApplicationBuild
    {
      get
      {
        return _ApplicationBuild;
      }
      set
      {
        SetPropertyValue("ApplicationBuild", ref _ApplicationBuild, value);
      }
    }
    //mmt
  }
}
