//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.ExpressApp.ConditionalAppearance;
using DevExpress.Persistent.Validation;
using DevExpress.ExpressApp;
using System.ComponentModel;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  // [Appearance("ProjectTemplate", AppearanceItemType = "Action!=CloneObject", TargetItems = "ProjectTemplate", Criteria = "ProjectTemplate!=null", Context = "DetailView", Enabled = false)]
  // [Appearance("ProjectTemplate", AppearanceItemType = "ViewItem", TargetItems = "ProjectTemplate", Criteria = "ProjectTemplate!=null ", Context = "DetailView", Enabled = false)]
  //[Appearance("Application", AppearanceItemType = "ViewItem", TargetItems = "Application", Criteria = "Requirement!=null", Context = "DetailView", Enabled = false)]
  //[OptimisticLocking(false)]
  [Appearance("EndDate", AppearanceItemType = "ViewItem", TargetItems = "Enddate", Criteria = "!IsCurrentUserInRole('IterationAdmin')", Context = "DetailView", Enabled = false)]
  [Appearance("Title", AppearanceItemType = "ViewItem", TargetItems = "Title", Criteria = "!IsCurrentUserInRole('IterationAdmin')", Context = "DetailView", Enabled = false)]
 
    [DefaultClassOptions]
  [XafDefaultProperty("Title")]
  [RelatedEntity("Aria5-SystemAdmin-TestCase")]
  [OptimisticLocking(OptimisticLockingBehavior.NoLocking)]
  public partial class TestCase : DevExpress.Persistent.BaseImpl.BaseObject
  {
    private Aria5SystemAdmin.Module.BusinessObjects.QAProjectEntity _qAProjectEntity;
    private Aria5SystemAdmin.Module.BusinessObjects.QAProjectEntity _projectEntity;
    private Aria5SystemAdmin.Module.BusinessObjects.Application_T _application;
    private Aria5SystemAdmin.Module.BusinessObjects.ProjectTemplate _projectTemplate;
    /*ATA ,1,bgn,15/3/2016, Baselineflag , add 2 new attribute to calcuate end date,
       and disable or enable edit or delet for this enddate property according to loginuser  
       */private System.DateTime _enddate;
    //[NonPersistent]
    //[DevExpress.Persistent.Base.VisibleInDetailViewAttribute(false)]
    //[DevExpress.Persistent.Base.VisibleInListViewAttribute(false)]
    //[DevExpress.Persistent.Base.VisibleInLookupListViewAttribute(false)]
    //public string LoginUser { get; set; }
    //ATA, end 
    private Aria5SystemAdmin.Module.BusinessObjects.AriaSecuritySystemUser _assignedUser;
    private status? _status;
    private Aria5SystemAdmin.Module.BusinessObjects.QAUseCase _qAUseCase;
    private Aria5SystemAdmin.Module.BusinessObjects.QADefect _qADefect;
    private Aria5SystemAdmin.Module.BusinessObjects.AriaObject _entity;
    private Aria5SystemAdmin.Module.BusinessObjects.Requirement _requirement;
    private System.String _description;
    private System.Boolean _IsOriginal;
    private System.String _title;
    private System.String _refrence;
      //ATA add new relation with tracking entry 
    private TrackingEntry _trackingEntry;
    public TestCase(DevExpress.Xpo.Session session)
      : base(session)
    {
      
      //ATA get login user ,14/3/2016
      //LoginUser = SecuritySystem.CurrentUserName.Trim().ToUpper();
        //if (this.ProjectTemplate != null)
        //{
        //    this.Title = "TC -Iteration #" + this.ProjectTemplate.EndDate.Year + "-" + this.ProjectTemplate.IterationNumber + "#" + (this.ProjectTemplate.TestCases.FindIndex(x => x.IsOriginal = true) + 1).ToString("00");

        //}
      //ATA , end 
    }
    public TestCase(DevExpress.Xpo.Session session, TestCase testCase)
      : base(session)
    {
      //  session.Equals(testCase.Session)
      this.Application = testCase.Application;
      this.Description = testCase.Description;
      this.Entity = testCase.Entity;
      this.ProjectTemplate = testCase.ProjectTemplate;
      this.QAUseCase = testCase.QAUseCase;
      this.Refrence = testCase.Refrence;
      this.Requirement = testCase.Requirement;
      this.Title = testCase.Title + " " + DateTime.Now.ToString();
        //ATA add the project entity in case cloning [start]
     // this.ProjectEntity = testCase.ProjectEntity;
      this.EntityFeature = testCase.EntityFeature;
      //ATA add the project entity in case cloning [End]
        //ATA add the test level and test case type 5/4/2017[start]
      this.TestCaselevel = testCase.TestCaselevel;
      this.TestcaseType = testCase.TestcaseType;
      //ATA add the test level and test case type 5/4/2017[End]
      this.Status = TestCase.status.New;
      this.IsOriginal = false;
      //ATA modify non original test case end date [start]
        if(testCase.ProjectTemplate != null)
      this.Enddate = CalcEndate.CalcEnddate(testCase.ProjectTemplate.StartDate, 3);
      //ATA
      foreach (var testCasestep in testCase.TestCaseSteps)
        this.TestCaseSteps.Add(new TestCaseSteps(session, testCasestep));
    }

      //ATA add new constructor that mapping the tracking Entry as a variable to work with it 11/19/2017 [start]
    public TestCase(DevExpress.Xpo.Session session, TestCase testCase,TrackingEntry Tracking)
        : base(session)
    {
        //  session.Equals(testCase.Session)
        this.Application = testCase.Application;
        this.Description = testCase.Description;
        this.Entity = testCase.Entity;
        this.ProjectTemplate = Tracking.ProjectTemplate;
        this.QAUseCase = testCase.QAUseCase;
        this.Refrence = testCase.Refrence;
        this.Requirement = testCase.Requirement;
        this.Title = testCase.Title + " -" + DateTime.Now.ToString();
        //ATA add the project entity in case cloning [start]
       // this.ProjectEntity = testCase.ProjectEntity;
        this.EntityFeature = testCase.EntityFeature;
        //ATA add the project entity in case cloning [End]
        //ATA add the test level and test case type 5/4/2017[start]
        this.TestCaselevel = testCase.TestCaselevel;
        this.TestcaseType = testCase.TestcaseType;
        //ATA add the test level and test case type 5/4/2017[End]
        this.Status = TestCase.status.New;
        this.IsOriginal = false;
        //ATA modify non original test case end date [start]
        if (Tracking.ProjectTemplate != null)
            this.Enddate = CalcEndate.CalcEnddate(Tracking.ProjectTemplate.StartDate, 3);
        //ATA
        foreach (var testCasestep in testCase.TestCaseSteps)
            this.TestCaseSteps.Add(new TestCaseSteps(session, testCasestep));
    }
    //ATA add new constructor that mapping test taske the test run as a variable to work with it 11/19/2017 [ENd]

    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    [Size(200)]
    [RuleRequiredField]
    public System.String Refrence
    {
      get
      {
        return _refrence;
      }
      set
      {
        SetPropertyValue("Refrence", ref _refrence, value);
      }
    }
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    //[RuleRequiredField]
    [Size(200)]
    public System.String Title
    {
      get
      {
        return _title;
      }
      set
      {
        SetPropertyValue("Title", ref _title, value);
      }
    }
    [Size(8000)]
    public System.String Description
    {
      get
      {
        return _description;
      }
      set
      {
        SetPropertyValue("Description", ref _description, value);
      }
    }
    //ATA 19/6/2016 [start]
    // [RuleRequiredField]
    //ATA 19/6/2016  [end]
    [DevExpress.Xpo.AssociationAttribute("TestCases-Requirement")]
    public Aria5SystemAdmin.Module.BusinessObjects.Requirement Requirement
    {
      get
      {
        return _requirement;
      }
      set
      {
        SetPropertyValue("Requirement", ref _requirement, value);
      }
    }
      //ATA add new realtion with tracking entry 
         [Association("Trackingentry-TestCases")]
    public TrackingEntry TrackingEntry
    {
        get { return _trackingEntry; }
        set { SetPropertyValue("TrackingEntry", ref _trackingEntry, value);
        if (!IsSaving && !IsLoading && value != null)
        {
            this.ProjectTemplate = value.ProjectTemplate;
            this.Entity = value.Entity;
        }
        }
    }
      [Association("AriaObjectEntity-TeastCases")]
    public Aria5SystemAdmin.Module.BusinessObjects.AriaObject Entity
    {
      get
      {
        return _entity;
      }
      set
      {
        SetPropertyValue("Entity", ref _entity, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TestCaseSteps-TestCase")]
    [DevExpress.Xpo.AggregatedAttribute]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.TestCaseSteps> TestCaseSteps
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.TestCaseSteps>("TestCaseSteps");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TestCases-TestRuns")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.TestRun> TestRuns
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.TestRun>("TestRuns");
      }
    }
    public Aria5SystemAdmin.Module.BusinessObjects.QADefect QADefect
    {
      get
      {
        return _qADefect;
      }
      set
      {
        if (_qADefect == value)
          return;
        Aria5SystemAdmin.Module.BusinessObjects.QADefect prevQADefect = _qADefect;
        _qADefect = value;
        if (IsLoading)
          return;
        if (prevQADefect != null && prevQADefect.TestCase == this)
          prevQADefect.TestCase = null;
        if (_qADefect != null)
          _qADefect.TestCase = this;
        OnChanged("QADefect");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TestCases-QAUseCase")]
    public Aria5SystemAdmin.Module.BusinessObjects.QAUseCase QAUseCase
    {
      get
      {
        return _qAUseCase;
      }
      set
      {
        SetPropertyValue("QAUseCase", ref _qAUseCase, value);
      }
    }
    //ATA enhancestatus to be status of work and status of approval and make the status of work default value is null [Start]
  //ATA add defect as a list under the test case 4/241/2017 [star]
      [Association("TestCase-Defects")]
    public XPCollection<QADefect> Defects
    {
        get
        {
            return GetCollection<QADefect>("Defects");
        }
    }
    //ATA add defect as a list under the test case 4/241/2017 [End]
      [RuleRequiredField]
      public status? Status
    {
      get
      {
        return _status;
      }
      set
      {
        SetPropertyValue("Status", ref _status, value);
      }
    }
    public enum status
    {
      New,
      InWork,
      Passed,
      Failed,
      Completed,
      Retried,
      partiallypassed
    }
    private ApproveStatu _approvestatus;
    public ApproveStatu ApproveStatus
    {
      get
      {
        return _approvestatus;
      }
      set
      {
        SetPropertyValue("ApproveStatus", ref _approvestatus, value);
      }
    }
    //ATA enhancestatus to be status of work and status of approval and make the status of work default value is null 1/11/2017[End]
    public enum ApproveStatu
    {
      New,
      Ready
    }
    [DevExpress.Xpo.AssociationAttribute("Comments-TestCase")]
    [DevExpress.Xpo.AggregatedAttribute]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.Comments> Comments
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.Comments>("Comments");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("Attachements-TestCase")]
    [DevExpress.Xpo.AggregatedAttribute]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QAAttachement> Attachements
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QAAttachement>("Attachements");
      }
    }
    public Aria5SystemAdmin.Module.BusinessObjects.AriaSecuritySystemUser AssignedUser
    {
      get
      {
        return _assignedUser;
      }
      set
      {
        SetPropertyValue("AssignedUser", ref _assignedUser, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TestCases-ProjectTemplate")]
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    public Aria5SystemAdmin.Module.BusinessObjects.ProjectTemplate ProjectTemplate
    {
      get
      {
        if (_projectTemplate != null)
        {
          this.Application = _projectTemplate.Application;
          //ATA, 1,bgn,15/3/2016,check if _enddate not calculated and it is assign to a project then calculate it according to project type 
          if (_enddate == DateTime.MinValue)
          {
            if (_projectTemplate.Type.ToString() == "Key")
            {
              this._enddate = CalcEndate.CalcEnddate(_projectTemplate.StartDate, 2);
            }
            else
            {
              this._enddate = _projectTemplate.EndDate;
            }
            //this._enddate = CalcEnddate(_projectTemplate.StartDate, 3);
          }
          //ATA,1 , end 
        }
        return _projectTemplate;
      }
      set
      {
        SetPropertyValue("ProjectTemplate", ref _projectTemplate, value);
          //ATA auto generate the test case title with sequence number 
        if (!IsLoading && !IsSaving && value != null && this.Oid == Guid.Empty && this.Title == null)
        {
            this.Title = "TC -Iteration #" + value.EndDate.Year + "-" + value.IterationNumber + "#" + (value.TestCases.Count<TestCase>(x => x.IsOriginal == true) + 1).ToString("00");
           //// Doaa 05/01/2019 {start}
           // this.Title = "TC -" + this.TrackingEntry.ID + "#" + (value.TestCases.Count<TestCase>(x => x.IsOriginal == true) + 1).ToString("00");
           // // Doaa 05/01/2019 {End}
        }
      }
    }
    //ATA bgn 15/3/2016
    public System.DateTime Enddate
    {
      get
      {
        return _enddate;
      }
      set
      {
        //if (this.ProjectTemplate != null)
        //{
        //    SetPropertyValue("Enddate", ref _enddate, CalcEnddate(this.ProjectTemplate.StartDate, 3)); 
        //}
        //else
        //{
        SetPropertyValue("Enddate", ref _enddate, value);
        //}
      }
    }
    //ATA 
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    [DevExpress.Xpo.AssociationAttribute("TestCases-Application")]
    public Aria5SystemAdmin.Module.BusinessObjects.Application_T Application
    {
      get
      {
        return _application;
      }
      set
      {
        SetPropertyValue("Application", ref _application, value);
      }
    }
    private XPCollection<AuditDataItemPersistent> changeHistory;
    public XPCollection<AuditDataItemPersistent> ChangeHistory
    {
      get
      {
        if (changeHistory == null)
        {
          changeHistory = AuditedObjectWeakReference.GetAuditTrail(Session, this);
        }
        return changeHistory;
      }
    }
    // [RuleRequiredField]
    [DevExpress.Persistent.Base.ImmediatePostDataAttribute]
    [DevExpress.Xpo.AssociationAttribute("TestCases-QAProjectEntity")]
      [Browsable(false)]
    public Aria5SystemAdmin.Module.BusinessObjects.QAProjectEntity ProjectEntity
    {
      get
      {
        return _projectEntity;
      }
      set
      {
        SetPropertyValue("ProjectEntity", ref _projectEntity, value);
        if (_projectEntity != null)
        {
          Entity = _projectEntity.AriaObject;
        }
      }
    }
    //ATA add relation with testing cases 3/23/2017 [start]
    private QAMainFeature _entityFeature;
    [Association("EntityFeature-testcases")]
    [DataSourceProperty("ProjectEntity.MainFeatures")]
    public QAMainFeature EntityFeature
    {
        get
        {
            return _entityFeature;
        }
        set
        {
            SetPropertyValue("EntityFeature", ref _entityFeature, value);
        }
    }
    public System.Boolean IsOriginal
    {
      get
      {
        return _IsOriginal;
      }
      set
      {
        SetPropertyValue("IsOriginal", ref _IsOriginal, value);
      }
    }
    //Sara,SPIG Last Meeting 21/12/2015[start]
    //public enum Testlevels
    //{
    //  Component_Test,
    //  Integration_Test,
    //  SystemTest,
    //  AcceptanceTest,
    //}
    private Aria5SystemAdmin.Module.BusinessObjects.QATestPlan.Testlevels? _TestCaselevel;
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    [RuleRequiredField]
    public Aria5SystemAdmin.Module.BusinessObjects.QATestPlan.Testlevels? TestCaselevel
    {
      get
      {
        return _TestCaselevel;
      }
      set
      {
        SetPropertyValue("TestCaselevel", ref _TestCaselevel, value);
      }
    }
    //public enum Testtype
    //{
    //  FunctionTesting,
    //  UsabilityTesting,
    //  PerformanceTesting,
    //  PortabilityTesting
    //}
    private Aria5SystemAdmin.Module.BusinessObjects.QATestPlan.Testtype? _TestcaseType;
    //ATA add rule required field attribute to be mandatory 1/5/2017[start]
    //ATA add rule required field attribute to be mandatory 1/5/2017[End]
    [RuleRequiredField]
    public Aria5SystemAdmin.Module.BusinessObjects.QATestPlan.Testtype? TestcaseType
    {
      get
      {
        return _TestcaseType;
      }
      set
      {
        SetPropertyValue("TestcaseType", ref _TestcaseType, value);
      }
    }
    //Sara,SPIG Last Meeting 21/12/2015 [END]
    //public Aria5SystemAdmin.Module.BusinessObjects.QAProjectEntity QAProjectEntity
    //{
    //  get
    //  {
    //    return _qAProjectEntity;
    //  }
    //  set
    //  {
    //    SetPropertyValue("QAProjectEntity", ref _qAProjectEntity, value);
    //  }
    //}
  }
}
