//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using System.ComponentModel;
namespace Aria5SystemAdmin.Module.BusinessObjects
{
  [DefaultClassOptions]
  [XafDefaultProperty("Name")]
  [RelatedEntity("Aria5-SystemAdmin-TicketAHT")]
  public partial class TicketAHT : DevExpress.Persistent.BaseImpl.BaseObject
  {
    public TicketAHT(DevExpress.Xpo.Session session)
      : base(session)
    {
    }
    private System.String _tiecketnum;
    private System.Double _customercare;
    private System.Double _PMO;
    private System.Double _sales;
    private System.Double _helpdesk;
    private System.Double _webbased;
    private System.Double _constoultdispatch;
    private System.Double _pcwaiting;
    private System.Double _customeracceptance;
    private System.Double _validation;
    private System.Double _erpQ;
    private System.Double _edi;
    private System.Double _cwa;
    private System.Double _html5;
    private System.Double _review;
    private System.Double _defwaitingsch;
    private System.Double _defindev;
    private System.Double _distrbution;
    private System.Double _it;
    private System.Double _pendingenhanc;
    private System.Double _holdingentires;
    private System.Double _postsale;
    private System.Double _billingdisputes;
    private Udfenum _udf;
    private System.DateTime completedate;
    private System.DateTime createdate;
    private System.String _title;
    private System.String _account;
    private System.Double _dot;
    private Resources _primary_resource;
    public System.String TiecketNum
    {
      get
      {
        return _tiecketnum;
      }
      set
      {
        SetPropertyValue("TiecketNum", ref _tiecketnum, value);
      }
    }
   
    public System.DateTime Completedate
    {
      get
      {
        return completedate;
      }
      set
      {
        SetPropertyValue("Completedate", ref completedate, value);
      }
    }
    public System.DateTime CreateDate
    {
      get
      {
        return createdate;
      }
      set
      {
        SetPropertyValue("CreateDate", ref createdate, value);
      }
    }
    public Udfenum UDF
    {
      get
      {
        return _udf;
      }
      set
      {
        SetPropertyValue("UDF", ref _udf, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(400)]
    public System.String Title
    {
      get
      {
        return _title;
      }
      set
      {
        SetPropertyValue("Title", ref _title, value);
      }
    }
    [DevExpress.Xpo.SizeAttribute(200)]
    public System.String Account
    {
      get
      {
        return _account;
      }
      set
      {
        SetPropertyValue("Account", ref _account, value);
      }
    }
    private Account _systemaccoun;
    [DevExpress.Xpo.AssociationAttribute("TicketAHT-Account")]
    public Account Account_profile
    {
      get
      {
        return _systemaccoun;
      }
      set
      {
        SetPropertyValue("Account_profile", ref _systemaccoun, value);
      }
    }
    [DevExpress.Xpo.AssociationAttribute("QueueValues-TicketAHT")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.QueueValues> QueuesValues
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.QueueValues>("QueuesValues");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("DepartmentAHT-TicketAHT")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.DepartmentAHT> DepartmentsAHT
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.DepartmentAHT>("DepartmentsAHT");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("TicketDetail-TicketAHT")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.TicketDetail> TicketDetail
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.TicketDetail>("TicketDetail");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("AverageHandleTime-TicketAHT")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.AverageHandleTime> Averge_handle_time
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.AverageHandleTime>("Averge_handle_time");
      }
    }
    [DevExpress.Xpo.AssociationAttribute("DeliveryOnTime-TicketAHT")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.DeliveryOnTime> DeliveryOnTimes
    {
      get
      {
        return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.DeliveryOnTime>("DeliveryOnTimes");
      }
    }

    [DevExpress.Xpo.AssociationAttribute("ResourceAHT-TicketAHT")]
    public XPCollection<Aria5SystemAdmin.Module.BusinessObjects.ResourcesAHT> ResourcesAHT
    {
        get
        {
            return GetCollection<Aria5SystemAdmin.Module.BusinessObjects.ResourcesAHT>("ResourcesAHT");
        }
    }
    private System.Double _ticketage;
    public System.Double Ticketage
    {
      get
      {
        return _ticketage;
      }
      set
      {
        SetPropertyValue("Ticketage", ref _ticketage, value);
      }
    }
    public Resources PrimaryResource
    {
      get
      {
        return _primary_resource;
      }
      set
      {
        _primary_resource = value;
      }
    }
    [DevExpress.Persistent.Base.VisibleInDetailViewAttribute(false)]
    [DevExpress.Persistent.Base.VisibleInListViewAttribute(false)]
    [DevExpress.Persistent.Base.VisibleInLookupListViewAttribute(false)]
    public System.Double DeliveryOnTime
    {
      get
      {
        return _dot;
      }
      set
      {
        SetPropertyValue("DeliveryOnTime", ref _dot, value);
      }
    }
      //ATA add ticket status to insert nucompleted ticketes in the calculation [Statrt]
    private TicketStatus _status;
    public TicketStatus Status
    {
        get
        {
            return _status;
        }
        set
        {
            SetPropertyValue("Status", ref _status, value);
        }
    }
      //ATA add ticket status to insert nucompleted ticketes in the calculation [End]
    private int _id;
      [Browsable(false)]
    public int ID
    {
        get
        {
            return _id;
        }
        set
        {
            SetPropertyValue("ID", ref _id, value);
        }
    }
  }
  public enum Udfenum
  {
      //ATA add this UnKnown Type for the tickets that have no udf need schecdule 2/19/2017
    UnKnown = 0,
    SD = 2,
    ERP = 3,
    EDI = 4,
    CWA = 5,
    IT = 6,
    consulting = 9,
    sales = 7,
    Internal = 8
  }
  public enum TicketStatus
  {
      Complete,
      NotCompleted
      
  }
}
