//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using System.Linq;

using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.Persistent.Validation;

namespace Aria5SystemAdmin.Module.BusinessObjects
{
    [DefaultClassOptions]
    public partial class TypeSettings : DevExpress.Persistent.BaseImpl.BaseObject
    {
        public TypeSettings(DevExpress.Xpo.Session session)
            : base(session)
        {

        }

        private string _settingName;

        public string SettingName
        {
            get { return _settingName; }
            set { _settingName = value; }
        }
        private SettingType _settingtype;
        [RuleRequiredField]
        public SettingType Settingtype
        {
            get { return _settingtype; }
            set { _settingtype = value; }
        }
        private string _value;
        [RuleRequiredField]
        public string Value
        {
            get { return _value; }
            set { _value = value; }
        }

        private EntityTypeSettings _settingHeader;

          [Association("EntityTypeSettings-TypeSettings")]
        public EntityTypeSettings SettingHeader
        {
            get { return _settingHeader; }
            set
            {
                _settingHeader = value;
            }
        }
    }
}
