#DEFINE MENU_WIDTH 230
#DEFINE MENU_HIEGHT 500

#DEFINE LABLE_WIDTH 230
#DEFINE LABLE_HIEGHT 40

#DEFINE LABLE_TEXT_MODULE_LEFT 0
#DEFINE LABLE_TEXT_MODULE_TOP 0

#DEFINE LABLE_TEXT_COMMAND_LEFT 32
#DEFINE LABLE_TEXT_COMMAND_TOP 16

#DEFINE ICON_WIDTH 18
#DEFINE ICON_HEIGHT 15

#DEFINE ICON_LEFT_MODULE 16
#DEFINE ICON_TOP_MODULE 4

#DEFINE ICON_LEFT_COMMAND 32
#DEFINE ICON_TOP_COMMAND 4

#DEFINE ARROW_TOP 4
#DEFINE ARROW_LEFT 200

#DEFINE ARROW_WIDTH 16
#DEFINE ARROW_HEIGHT 16

#DEFINE ITEM_TYPE 1
#DEFINE ITEM_CAPTION 2
#DEFINE ITEM_COMMAND 3
#DEFINE ITEM_ICON 4

#DEFINE ARROW_STATUS 15

#DEFINE NUMBER_OF_SUBITEMS 20

#DEFINE MENU_CONTROL_1 21
#DEFINE MENU_CONTROL_2 22
#DEFINE MENU_CONTROL_3 23

#DEFINE MENU_HEIGHT 24

#DEFINE SUBMENU_CONTROL 25
#DEFINE SUBMENU_HEIGHT 26

#DEFINE MENU_FAV 27