#DEFINE LANG_SALES_ORDER 'Sales Order'
#DEFINE LANG_SALES_ORDER_APPROVAL  "Sales Order Approval"
#DEFINE LANG_INVOICE_SALES_ORDER "Invoice Sales Order"
#DEFINE LANG_PICKING_TICKET "Picking Ticket"
#DEFINE LANG_ALOC_BY_ORDER  'Allocation By Order'
#DEFINE LANG_ALOC_BY_STYLE 'Allocation By Style'
#DEFINE LANG_AUT_ALOC 'Automatic Allocation'
#DEFINE LANG_MANUAL_PL 'Manual Packing List'
#DEFINE LANG_AUT_PL 'Automatic Packing List'
#DEFINE LANG_CUSTOMER 'Customer'
#DEFINE LANG_SALES_REP 'Sales Representitive'
#DEFINE LANG_LOCATION 'Location'
#DEFINE LANG_STYLE  'Style'
#DEFINE LANG_ARTWORKDESIGN 'Artwork Design'
#DEFINE LANG_PACK 'Pack'
#DEFINE LANG_CODES 'Codes'
#DEFINE LANG_MASS_ORDER_CAN 'Mass Order Cancellation'
#DEFINE LANG_RTLDDATA ' Related Data'
#DEFINE LANG_ORDER_CONF_FORM 'Order Confirmation Form'
#DEFINE LANG_PIKTKT_FORM 'Pick Ticket Form'
#DEFINE LANG_PL_FORM 'Packing List Form'
#DEFINE LANG_INVOICE_FORM 'Invoice Form'
#DEFINE LANG_ORDERHEADER 'Order Header'
#DEFINE LANG_ORDER_DET 'Order Detail'
#DEFINE LANG_ORDER_STATUS 'Order Status'
#DEFINE LANG_ORDER_CANC 'Order Cancellation'
#DEFINE LANG_DELIVERY_SCH 'Delivery Schedule'
#DEFINE LANGFORECAST 'Forecasting'
#DEFINE LANG_ORDER_SAL_SUMMARY 'Order/Sales Summary'
#DEFINE LANG_STOCK_AVL 'Stock Availability'
#DEFINE LANG_GROSS_PROFIT  'Gross Profit'
#DEFINE LANG_PO_ALLOCATION  'CutTkt/PO Allocation'
#DEFINE LANG_CUSTOMER_ACTIVITY  'Customer Activity by Season/State'
#DEFINE LANG_CUSTOMER_MAILING   'Customer Mailing Label'
#DEFINE LANG_CUSTOMER_LETTERS   'Customer Letters'
#DEFINE LANG_CUSTOMER_DEPT  'Customer Department'
#DEFINE LANG_RTLREP 'Related Output'
#DEFINE LANG_PO 'Style Purchase Order'
#DEFINE LANG_PO_GEN_SO 'Generate PO from Sales Order'  
#DEFINE LANG_PO_GEN_OTS 'Generate PO based on Open To Sell'      
#DEFINE LANG_PO_CSTSHEET 'PO Cost Sheet'
#DEFINE LANG_PO_Alloc 'Style PO Allocation'
#DEFINE LANG_PO_SHIPMENT 'Style PO Shipment'
#DEFINE LANG_PO_ADJST_REC 'Adjust Cost for Receiving'
#DEFINE LANG_PO_RECEIVE 'Receive Style PO'
#DEFINE LANG_PO_CLOSE 'Close PO'
#DEFINE LANG_PO_FORM 'Purchase Order Form'
#DEFINE LANG_PO_HEADER 'Purchase Order Header'  
#DEFINE LANG_PO_DETAIL 'Purchase Order Detail'  
#DEFINE LANG_PO_CANCEL 'Purchase Order Cancellation' 
#DEFINE LANG_PO_COST_SHEET   'Purchase Order Cost Sheet'  
#DEFINE LANG_PO_REC_LOG  'P/O Receipts Log'
#DEFINE LANG_PO_SHIPMENT_STATUS  'Shipment Status'  
#DEFINE LANG_PO_SHIP_CST_SHEET   'Shipment Cost Sheet' 
#DEFINE LANG_PO_OPER_MANG  'Operation Management'
#DEFINE LANG_PO_CONTARCTOR_TRACK  'Contractor Tracking'
#DEFINE LANG_PO_GL_WIP 'GL-WIP Account' 
#DEFINE LANG_VENDOR 'Vendor' 
#DEFINE LANG_STYLE_CSTSHET 'Style Cost Sheet'
#DEFINE LANG_BANK_CHKACCT  'Bank/Checking Account'
#DEFINE LANG_SCAN_ITEM_BARCODE 'Scan Items Barcodes'
#DEFINE LANG_ISSUE_RET_STYLE_PO 'Issue Return Style PO'
#DEFINE LANG_MANF_RECEIVE 'Manufacturing Receiving'
#DEFINE LANG_AR_INVOICE  'AR Invoice'
#DEFINE LANG_STYLE_INV_PHY  'Style Physical Inventory'
#DEFINE LANG_STYLE_INV_ADJ  'Style Inventory Adjustment'
#DEFINE LANG_CREDIT_MEMO  'Credit Memo'
#DEFINE LANG_STYLE_SUMMARY  'Style Summary' 
#DEFINE LANG_STYLE_CUT_SOLD 'Style Cut & Sold'  
#DEFINE LANG_SPECIAL_CUT_SOLD 'Special Cut & Sold' 
#DEFINE LANG_UTILIZATION 'Style Utilization'
#DEFINE LANG_PRICE_LIST 'Price List'
#DEFINE LANG_ROYALTY 'Royalty' 
#DEFINE LANG_COSTING 'Costing'
#DEFINE LANG_DATE_SENSITIVE 'Date Sensitive Inventory'
#DEFINE LANG_STYLE_MASTER  'Style Master List'
#DEFINE LANG_INVENTORY_AGE 'Inventory Aging'
#DEFINE LANG_PHY_WORKSHEET 'Physical Inventory WorkSheet'
#DEFINE LANG_MARKDOWN 'Inventory & Markdown Values'
#DEFINE LANG_STK_ADJ_JRNL 'Stock Adjustment Journal'
#DEFINE LANG_PACK_SKU 'Pack/SKU'
*****
#DEFINE LANG_CASH_REC "Cash Receipt"
#DEFINE LANG_DEBIT_ADJ  'Debit Adjustment'
#DEFINE LANG_CREDIT_ADJ  'Credit Adjustment'
#DEFINE LANG_APPLY_DEBIT_CR 'Apply Debits/Credits'
#DEFINE LANG_REVERSE_DEBIT_CR  'Reverse key off/payments'
#DEFINE LANG_AGE_AR  'Age Accounts Receivable'
#DEFINE LANG_AGE_AR_REP  'AR Aging'
#DEFINE LANG_AGE_SUMMARY 'Aging Summary'
#DEFINE LANG_SALES_JOURNAL 'Sales Journal'
#DEFINE LANG_SALES_SUMMARY 'Sales Summary'
#DEFINE LANG_GROSS_PROFIT 'Gross Profit'
#DEFINE LANG_SHIPPING_LOG 'Shipping Log'
#DEFINE LANG_ACT_SUMMARY 'Activity Summary'
#DEFINE LANG_CASH_ADJ 'Cash & Adjustment'
#DEFINE LANG_CHARGE_BACK 'Chargebacks & Credits'
#DEFINE LANG_DEB_CRD_ADJ_MEMO 'Debit/Credit Adjustment Memo'
#DEFINE LANG_CUST_HIST 'Customer History'
#DEFINE LANG_CUST_STATEMENT  'Customer Statement'
#DEFINE LANG_GL_ENTRY 'GL Entry Report'
#DEFINE LANG_AP_INVOICE 'Payable Invoice' 
#DEFINE LANG_AP_APPROVE_PAY 'Approve For Payment'
#DEFINE LANG_AP_ADVANCE_CASH 'Advance Cash Payment'
#DEFINE LANG_AP_ADVANCE_MANUAL 'Advance Manual Check Payment'
#DEFINE LANG_AP_ADVANCE_NON_CHECK 'Advance Non-Check Payment'
#DEFINE LANG_BANK_RECONC  'Bank Reconciliation'
#DEFINE LANG_BANK_ADJUSTMENT 'Bank Adjustment'
#DEFINE LANG_AP_CASH 'Cash Payment'
#DEFINE LANG_AP_MANUAL 'Manual Check Payment'
#DEFINE LANG_AP_NON_CHECK 'Non-Check Payment'
#DEFINE LANG_PRINT_CHECK 'Print Check'
#DEFINE LANG_APPLY_DEBIT 'Apply Debits'
#DEFINE LANG_VOID_PAYMENT 'Void Payment'
#DEFINE LANG_CHECK_REGISTER 'Check Register'
#DEFINE LANG_AGED_PAYABLE  'Aged Payable'
#DEFINE LANG_AP_JOURNAL 'AP Journal'
#DEFINE LANG_APPROVED_TO_PAY 'Approved To Pay' 
#DEFINE LANG_PAYABLE_INV_SUMMARY 'Payable Invoice Summary' 
#DEFINE LANG_PAYABLE_INV_DETAILS 'Payable Invoice Details' 
#DEFINE LANG_INV_CONTRIBUTION 'Invoice Contribution' 
#DEFINE LANG_RELEASE_GL 'Release to GL'
#DEFINE LANG_SINGLE_TRANS 'Single Transaction'
#DEFINE LANG_JOURNAL_BATCH 'Journal Batch'
#DEFINE LANG_TRIAL_BALANCE  'Trial Balance'
#DEFINE LANG_BALANCE_SHEET  'Balance Sheet'
#DEFINE LANG_INCOME_STATEMENT  'Income Statement'
#DEFINE LANG_SINGLE_ACC 'Single Account'
#DEFINE LANG_GL_LINK_CODE 'GL Link Code'
#DEFINE LANG_GROUP 'Group'
#DEFINE LANG_RECURRING_ENTRY 'Recurring Entry'
#DEFINE LANG_GL_SETUP 'General Ledger Setup'
#DEFINE LANG_TYPES_RANGE 'Types and Ranges'
#DEFINE LANG_BUDGET 'Budget' 
#DEFINE LANG_SOURCE_JOURNAL 'Source Journal'
#DEFINE LANG_ACC_REC_UNPOST_ENTRY 'Account Reconc.-Unposted Entry'
#DEFINE LANG_UNPOST_BATCH 'Unposted Batch'
#DEFINE LANG_UNPOST_TRANS 'Unposted Transaction'
#DEFINE LANG_UNPOST_BATCH_TRANS 'Unposted Batch/Transaction'
#DEFINE LANG_ACC_REC 'Account Reconciliation'
#DEFINE LANG_POSTED_BATCH 'Posted Batch'
#DEFINE LANG_POSTED_TRANS 'Posted Transaction'
#DEFINE LANG_POSTED_BATCH_TRANS 'Posted Batch/Transaction'
#DEFINE LANG_ACCOUNT_GROUP 'Account Group' 
#DEFINE LANG_CHART_OF_ACCOUNT 'Chart Of Account'
#DEFINE LANG_ACC_TYPE 'Account Type'
#DEFINE LANG_SINGLE_TRANS_POST 'Posting Single Transaction'
#DEFINE LANG_JOURNAL_BATCH_POST 'Posting Journal Batch'
#DEFINE LANG_STY_INV_LOCK 'Style Inventory Locking'
#DEFINE LANG_STY_TRANS_INV 'Style Transfer Inventory'
#DEFINE LANG_MAT_PO 'Material Purchase Order'
#DEFINE LANG_GEN_MA_PO_WIP 'New PO Based on WIP Requirements'
#DEFINE LANG_MA_PO_SHIP  'Material PO Shipment'
#DEFINE LANG_REC_MA 'Receive Material PO/Shipment'
#DEFINE LANG_STY_SHIPMENT 'Style PO Shipment'
#DEFINE LANG_PO_RETURN 'Material PO Return'
#DEFINE LANG_ISSUE_MAT_RET 'Issue Material PO Return'
#DEFINE LANG_MATVEN_REF 'Material/Vendor Reference'
#DEFINE LANG_MAT_COSTSHEET 'Material Cost Sheet'
#DEFINE LANG_MAT_PO_FORM 'Material Purchase Order Form'
#DEFINE LANG_MAT_PO_COST_SHEET 'Material Cost Sheet'
#DEFINE LANG_MAT_REC_LOG 'Purchase Order Receipt Log'
#DEFINE LANG_MAT_PO_HEADER 'Purchase order Header'
#DEFINE LANG_MAT_PO_DET 'Purchase order Detail'
#DEFINE LANG_MAT_OTS 'Open to Sell'
#DEFINE LANG_MAT_WIP_ACC 'Material WIP GL- Account' 
#DEFINE LANG_STYLE_PO_CSTSHET 'Style PO Cost Sheet'
#DEFINE LANG_MAT_INV_PHY  'Material Physical Inventory'
#DEFINE LANG_MAT_INV_ADJ  'Material Inventory Adjustment'
#DEFINE LANG_MAT_INV_TRAN 'Material Transfer Inventory'
#DEFINE LANG_MAT_INV_LOCK 'Material Inventory Locking'
#DEFINE LANG_MATERIAL 'Material'
#DEFINE LANG_MAT_DATE_SENSITIVE 'Material Date Sensitive Inventory'
#DEFINE LANG_MAT_ADJ_JRNL 'Material Inventory Adjustment Journal'
#DEFINE LANG_MAT_MARKDOWN 'Material Inventory & Markdown Values'
#DEFINE LANG_MAT_INV_BY_ROLL 'Material Inventory Report By Roll'
#DEFINE LANG_MAT_STY_MASTER 'Style Material Master'
