#DEFINE LANG_MaMaTrGm_All       "ALL"
#DEFINE LANG_MaMaTrGm_Notify    "The report will print a maximum of 256 columns."
#DEFINE LANG_MaMaTrGm_Total     "^^TOTAL :^^"
#DEFINE LANG_MaMaTrGm_LibNotFnd "LIBRARY NOT FOUND"
#DEFINE LANG_MaMaTrGm_MsgClct   "Collecting the cost sheet information for Style : "