#IFDEF LANG_DESC   
  #UNDEF LANG_DESC   
#ENDIF
#DEFINE LANG_DESC   "Description"

#IFDEF LANG_LDESC  
  #UNDEF LANG_LDESC  
#ENDIF
#DEFINE LANG_LDESC  "Long Description"

#IFDEF LANG_SEASON 
  #UNDEF LANG_SEASON 
#ENDIF
#DEFINE LANG_SEASON "Season"

#IFDEF LANG_DIV    
  #UNDEF LANG_DIV    
#ENDIF
#DEFINE LANG_DIV    "Division"

#IFDEF LANG_PRICEA 
  #UNDEF LANG_PRICEA 
#ENDIF
#DEFINE LANG_PRICEA "Price A"

#IFDEF LANG_PRICEB 
  #UNDEF LANG_PRICEB 
#ENDIF
#DEFINE LANG_PRICEB "Price B"

#IFDEF LANG_PRICEC 
  #UNDEF LANG_PRICEC 
#ENDIF
#DEFINE LANG_PRICEC "Price C"

#IFDEF LANG_WIP    
  #UNDEF LANG_WIP    
#ENDIF
#DEFINE LANG_WIP    "WIP"

#IFDEF LANG_STOCK  
  #UNDEF LANG_STOCK  
#ENDIF
#DEFINE LANG_STOCK  "Stock"

#IFDEF LANG_ORDER  
  #UNDEF LANG_ORDER  
#ENDIF
#DEFINE LANG_ORDER  "Orders"

#IFDEF LANG_FABRIC 
  #UNDEF LANG_FABRIC 
#ENDIF
#DEFINE LANG_FABRIC "Fabric"

#IFDEF LANG_OTS    
  #UNDEF LANG_OTS    
#ENDIF
#DEFINE LANG_OTS    "O.T.S."

#IFDEF LANG_GRADE  
  #UNDEF LANG_GRADE  
#ENDIF
#DEFINE LANG_GRADE  "Grade"

#IFDEF LANG_ROYAL  
  #UNDEF LANG_ROYAL  
#ENDIF
#DEFINE LANG_ROYAL  "Royalty"

#IFDEF LANG_PATRN  
  #UNDEF LANG_PATRN  
#ENDIF
#DEFINE LANG_PATRN  "Pattern"

#IFDEF LANG_STATUS 
  #UNDEF LANG_STATUS 
#ENDIF
#DEFINE LANG_STATUS "Status"

#IFDEF LANG_SCALE  
  #UNDEF LANG_SCALE  
#ENDIF
#DEFINE LANG_SCALE  "Scale"

#IFDEF LANG_PREPAK 
  #UNDEF LANG_PREPAK 
#ENDIF
#DEFINE LANG_PREPAK "Prepack"

#IFDEF LANG_BPREPK 
  #UNDEF LANG_BPREPK 
#ENDIF
#DEFINE LANG_BPREPK "Buy Prepack"

#IFDEF LANG_QTYCRT 
  #UNDEF LANG_QTYCRT 
#ENDIF
#DEFINE LANG_QTYCRT "Qty / Carton"

#IFDEF LANG_COMM   
  #UNDEF LANG_COMM   
#ENDIF
#DEFINE LANG_COMM   "Commission"

#IFDEF LANG_LNKCD  
  #UNDEF LANG_LNKCD  
#ENDIF
#DEFINE LANG_LNKCD  "Link Code"

#IFDEF LANG_MAKE   
  #UNDEF LANG_MAKE   
#ENDIF
#DEFINE LANG_MAKE   "Manuf."

#IFDEF LANG_MCST1  
  #UNDEF LANG_MCST1  
#ENDIF
#DEFINE LANG_MCST1  "Mfg. Cost 1"

#IFDEF LANG_MCST2  
  #UNDEF LANG_MCST2  
#ENDIF
#DEFINE LANG_MCST2  "Mfg. Cost 2"

#IFDEF LANG_MCST3  
  #UNDEF LANG_MCST3  
#ENDIF
#DEFINE LANG_MCST3  "Mfg. Cost 3"

#IFDEF LANG_MCST4  
  #UNDEF LANG_MCST4  
#ENDIF
#DEFINE LANG_MCST4  "Mfg. Cost 4"

#IFDEF LANG_MCST5  
  #UNDEF LANG_MCST5  
#ENDIF
#DEFINE LANG_MCST5  "Mfg. Cost 5"

#IFDEF LANG_ICST1  
  #UNDEF LANG_ICST1  
#ENDIF
#DEFINE LANG_ICST1  "Imp. Cost 1"

#IFDEF LANG_ICST2  
  #UNDEF LANG_ICST2  
#ENDIF
#DEFINE LANG_ICST2  "Imp. Cost 2"

#IFDEF LANG_ICST3  
  #UNDEF LANG_ICST3  
#ENDIF
#DEFINE LANG_ICST3  "Imp. Cost 3"

#IFDEF LANG_ICST4  
  #UNDEF LANG_ICST4  
#ENDIF
#DEFINE LANG_ICST4  "Imp. Cost 4"

#IFDEF LANG_ICST5  
  #UNDEF LANG_ICST5  
#ENDIF
#DEFINE LANG_ICST5  "Imp. Cost 5"

#IFDEF LANG_PCST2  
  #UNDEF LANG_PCST2  
#ENDIF
#DEFINE LANG_PCST2  "% Cost 2"

#IFDEF LANG_PCST3  
  #UNDEF LANG_PCST3  
#ENDIF
#DEFINE LANG_PCST3  "% Cost 3"

#IFDEF LANG_PCST4  
  #UNDEF LANG_PCST4  
#ENDIF
#DEFINE LANG_PCST4  "% Cost 4"

#IFDEF LANG_PCST5  
  #UNDEF LANG_PCST5  
#ENDIF
#DEFINE LANG_PCST5  "% Cost 5"

#IFDEF LANG_TOTCST 
  #UNDEF LANG_TOTCST 
#ENDIF
#DEFINE LANG_TOTCST "Total Cost"

#IFDEF LANG_AVECST 
  #UNDEF LANG_AVECST 
#ENDIF
#DEFINE LANG_AVECST "Avg. Cost"

#IFDEF LANG_STKVAL 
  #UNDEF LANG_STKVAL 
#ENDIF
#DEFINE LANG_STKVAL "Stock Value"

#IFDEF LANG_SOLDDT 
  #UNDEF LANG_SOLDDT 
#ENDIF
#DEFINE LANG_SOLDDT "Sold Date"

#IFDEF LANG_STRTDT 
  #UNDEF LANG_STRTDT 
#ENDIF
#DEFINE LANG_STRTDT "Start Date"

#IFDEF LANG_DBIN   
  #UNDEF LANG_DBIN   
#ENDIF
#DEFINE LANG_DBIN   "Def. Bin"

#IFDEF LANG_INVSTY 
  #UNDEF LANG_INVSTY 
#ENDIF
#DEFINE LANG_INVSTY "Inventory"

#IFDEF LANG_MARKA  
  #UNDEF LANG_MARKA  
#ENDIF
#DEFINE LANG_MARKA  "Markup A"

#IFDEF LANG_MARKB  
  #UNDEF LANG_MARKB  
#ENDIF
#DEFINE LANG_MARKB  "Markup B"

#IFDEF LANG_MARKC  
  #UNDEF LANG_MARKC  
#ENDIF
#DEFINE LANG_MARKC  "Markup C"

#IFDEF LANG_CONSI1 
  #UNDEF LANG_CONSI1 
#ENDIF
#DEFINE LANG_CONSI1 "Cons. Info. 1"

#IFDEF LANG_CONSI2 
  #UNDEF LANG_CONSI2 
#ENDIF
#DEFINE LANG_CONSI2 "Cons. Info. 2"

#IFDEF LANG_COLOR
  #UNDEF LANG_COLOR
#ENDIF
#DEFINE LANG_COLOR "Color"