#DEFINE LANG_SMCTGR_MANUL        "Manual"
#DEFINE LANG_SMCTGR_USER         'User'
#DEFINE LANG_SMCTGR_GROUP_USER	 'Group of users'
#DEFINE LANG_SMCTGR_CALENDAR 	 'Calendar ID'
#DEFINE LANG_SMCTGR_DESC	  	 'Description'
#DEFINE LANG_SMCTGR_CATEGORIES   'Categories'
#DEFINE LANG_SMCTGR_USERID       'User ID'
#DEFINE LANG_SMCTGR_USERNAME	 'User Name'
#DEFINE LANG_SMCTGR_RESPONUSR    'Responsible user'
#DEFINE LANG_SMCTGR_GROUPID		 'Group ID'
#DEFINE LANG_SMCTGR_GROUPNAME	 'Group Name'
#DEFINE LANG_SMCTGR_SLCTPRED     'Select Predecessors for '
#DEFINE LANG_SMCTGR_CATGTASK     "Categories of Tasks"
#DEFINE LANG_SMCTGR_CATGORY      'Category'
#DEFINE LANG_SMCTGR_USERS        'Users'
#DEFINE LANG_SMCTGR_EXISTINGUSER "User Exist"