#DEFINE LANG_GL_Link_Code  'GL Link Code'
#DEFINE LANG_Link_Type  'Link Type'
#DEFINE LANG_Link_Description  'Link Description'
#DEFINE LANG_Category_Key  'Category Key'
#DEFINE LANG_Description  'Description'
#DEFINE LANG_GL_Account  'GL. Account'
#DEFINE LANG_GL_Description  'GL. Description'
#DEFINE LANG_Link_Type_Link_Code 'Link Type\Link Code :'
#DEFINE LANG_Copy_Information_From_GL_Link_code 'Copy Information From G/L Link code'
#DEFINE LANG_Type  'Type'
#DEFINE LANG_Link_code  'Link code'
#DEFINE LANG_Link_codes  'Link codes'
#DEFINE LANG_GL_Account1  'GL Account'
#DEFINE LANG_GL_Accounts  'GL Accounts'
#DEFINE LANG_Default_GL_link_code  'Default G/L. link code'
#DEFINE LANG_Customer  'Customer'
#DEFINE LANG_Sales  'Sales'
#DEFINE LANG_Select_link_type  'Select link type'
#DEFINE LANG_Work_in_process  'Work in process'
#DEFINE LANG_Material  'Material'
#DEFINE LANG_Style  'Style'
#DEFINE LANG_Select_a_company  'Select a company'
#DEFINE LANG_Key_Categories  'Key Categories'
#DEFINE LANG_G/L_Link_codes  'G/L Link codes'
