#DEFINE LANG_ChngConfig_RejectReasonPL         "This line has a packing list. cannot change the configuration"
#DEFINE LANG_ChngConfig_RejectReasonPO         "There is a Purshase order generated for this line. cannot change the configuration"
#DEFINE LANG_ChngConfig_RejectReasonCT         "There is a Cut Ticket generated for this line. cannot change the configuration"
#DEFINE LANG_ChngConfig_RejectReasonShipped     "This line has shipped quantity. cannot change the configuration"
#DEFINE LANG_ChngConfig_UnSelectCaption         "Un\<Select"
#DEFINE LANG_ChngConfig_SelectCaption		    "\<Select"
#DEFINE LANG_ChngConfig_HeaderMoverColor        "Color"
#DEFINE LANG_ChngConfig_HeaderMoverConfig       "Existing Configurations"
#DEFINE LANG_ChngConfig_HeaderMoverGroup        "Style Groups"
#DEFINE LANG_ChngConfig_FormCaption             "Styles for Sales Order # "