#DEFINE LANG_QTY_SOLD 'Quantity Sold'
#DEFINE LANG_QTY_ORDER 'Quantity Ordered'
#DEFINE LANG_QTY_RETURNED 'Quantity Returned'
#DEFINE LANG_QTY_ONHAND 'Quantity On Hand'
#DEFINE LANG_SCOPE 'Scope'
#DEFINE LANG_SEL_QTY_TYPE 'Select Quantity Type'
#DEFINE LANG_SELECT_DATE_RANGE 'Please select the product activity Date Range.'
#DEFINE LANG_SELECT_ACCOUNT 'Please select the product activity Account#.'
#DEFINE LANG_ACTIVITY_ID 'Activity ID'
#DEFINE LANG_Account 'Account#'
#DEFINE LANG_DESC 'Description'
#DEFINE LANG_DATE_FROM 'From'
#DEFINE LANG_DATE_TO 'To'
#DEFINE LANG_SEND 'Ready To Send'
#DEFINE LANG_SELECT_LOC  'Please select the product activity location.'
#DEFINE LANG_SELECT_PROD_ACT 'Prodcut Activity# '
#DEFINE LANG_SELECT_PROD_CREATED " has been created."