#DEFINE LANG_CustInfo_HdrAccount       'Acct #'
#DEFINE LANG_CustInfo_HdrName          'Name'
#DEFINE LANG_CustInfo_HdrPhone         'Phone'
#DEFINE LANG_CustInfo_HdrCountry       'Country'
#DEFINE LANG_CustInfo_HdrBalance       'Balance'
#DEFINE LANG_CustInfo_TitlCustomers    'Customers'
#DEFINE LANG_CustInfo_CapchpackID      'Pack ID'
#DEFINE LANG_CustInfo_MsgNoAccSel      'No account is selected, cannot proceed.'
#DEFINE LANG_CustInfo_MsgNo            'No '
#DEFINE LANG_CustInfo_MsgNoStySel      ' is selected, cannot proceed.'
#DEFINE LANG_CustInfo_MsgStyle         'style'
#DEFINE LANG_CustInfo_MsgPAckID        'pack ID'
#DEFINE LANG_CustInfo_MsgZeroVal       'Qty/Ctn or Wgh/Unt is zero, cannot update.'
#DEFINE LANG_CustInfo_CapchCancel      '\<Cancel'
#DEFINE LANG_CustInfo_HdrAccount2      'Account'
#DEFINE LANG_CustInfo_HdrpackID        'Pack_ID'
#DEFINE LANG_CustInfo_HdrDesc          'Desc'
#DEFINE LANG_CustInfo_HdrDevision      'Devision'
#DEFINE LANG_CustInfo_HdrSeason        'Season'
#DEFINE LANG_CustInfo_HdrPckColor      'Pack Color'
#DEFINE LANG_CustInfo_HdrPckSize       'Pack Size'
#DEFINE LANG_CustInfo_HdrPckVer        'Pack Version'
#DEFINE LANG_CustInfo_HdrScale         'Scale'
#DEFINE LANG_CustInfo_HdrPattern       'Pattern'
#DEFINE LANG_CustInfo_HdrGroup         'Group'
#DEFINE LANG_CustInfo_HdrDescription   'Description'
#DEFINE LANG_CustInfo_TitlStyle        'Style File'
#DEFINE LANG_CustInfo_TitlStyleClr     'Style Color'