* E303343,1 TMI 01/15/2013 [Start] adding the titles and captions related to the closing program header file
#DEFINE LANG_SMCLOSE_lcTCloseL "closing"
#DEFINE LANG_SMCLOSE_lcTCloseU "Closing"
#DEFINE LANG_SMCLOSE_lcTOpen "open"
#DEFINE LANG_SMCLOSE_lcTLock "locked"
#DEFINE LANG_SMCLOSE_lcTUnPostd "Unposted single transactions"
#DEFINE LANG_SMCLOSE_lcTUnGenAl "Ungenerated allocation transactions"
#DEFINE LANG_SMCLOSE_lcTUnGenRc "Ungenerated recurring transactions"
#DEFINE LANG_SMCLOSE_lcTCloseP "Closing period"
#DEFINE LANG_SMCLOSE_lcTCloseY "Closing year"
#DEFINE LANG_SMCLOSE_lcTColect "Collecting companies information...! "
#DEFINE LANG_SMCLOSE_lcTUnPostB "Unposted batches"
#DEFINE LANG_SMCLOSE_lcTGenRevT "Generating reverse transactions. "
#DEFINE LANG_SMCLOSE_lcTGenRevB "Generating reverse batches. "
#DEFINE LANG_SMCLOSE_lcTUpdMast "Updating master files. "
#DEFINE LANG_SMCLOSE_lcTFiscal "Fiscal year"
#DEFINE LANG_SMCLOSE_lcTAdjBal "Adjusting balance... "
#DEFINE LANG_SMCLOSE_lcTAdjPsYP "Adjusting posted year & period... "
#DEFINE LANG_SMCLOSE_lcTBatHand "Batch Handeling... "
#DEFINE LANG_SMCLOSE_lcTRclasfi "Reclacified from the batch file. "
#DEFINE LANG_SMCLOSE_lcTRPostBt "Repost batchs & transactions... "
#DEFINE LANG_SMCLOSE_lcTUpdBal "Update balances... "
#DEFINE LANG_SMCLOSE_lcTGnClsEn "Generate closing entries... "
#DEFINE LANG_SMCLOSE_lcTCrClsEn "Create closing entries... "
#DEFINE LANG_SMCLOSE_lcTYecNo "YEC No"
#DEFINE LANG_SMCLOSE_lcTPrior "Prior year closing entries by "
#DEFINE LANG_SMCLOSE_lcTClsEntn "Closing entry No. "
#DEFINE LANG_SMCLOSE_lcTCompFil "Update the company file... "
#DEFINE LANG_SMCLOSE_lcTCompAP "Upadte the AP files..."
#DEFINE LANG_SMCLOSE_lcTCmpChld "Update the AP child companies files..."
#DEFINE LANG_SMCLOSE_lcTClsDone "done"
#DEFINE LANG_SMCLOSE_No_current_year 'No current year , or more than one, pls correct.'
#DEFINE LANG_SMCLOSE_Current_year_mismatch_error 'Current year mismatch error.'
#DEFINE LANG_SMCLOSE_LANG_SMCLOSE_Problems_opening_companyS_files "Problems opening company's files"
*E303343,1 TMI 01/15/2013 [End  ] 
*E303557,1 MMT 03/09/2015 Don't close period has unreleased transactions[T20150227.0001][Start]
#DEFINE LANG_UNRELEASEDTRANSACTIONS "Period has unreleased transactions, do you want to release now"
*E303557,1 MMT 03/09/2015 Don't close period has unreleased transactions[T20150227.0001][END]