*N000682,1 HES Handle globalization issues [Start]
#DEFINE LANG_PWRKCNT_Work_ID 'Work Center ID'
#DEFINE LANG_PWRKCNT_Work_Name 'Work Center Name'
#DEFINE LANG_PWRKCNT_Plant_ID 'Plant ID'
#DEFINE LANG_PWRKCNT_Capacity 'Capacity Based'
#DEFINE LANG_PWRKCNT_Available_Number 'Available Number'
#DEFINE LANG_PWRKCNT_Load 'Load'
#DEFINE LANG_PWRKCNT_Work_Type 'Work Center Type'
#DEFINE LANG_PWRKCNT_Calender 'Calender ID'
#DEFINE LANG_PWRKCNT_MP_Machine 'Man Per Machine'
#DEFINE LANG_PWRKCNT_Overhead 'Overhead Rate'
#DEFINE LANG_PWRKCNT_Standard 'Standard Rate'
#DEFINE LANG_PWRKCNT_Actual 'Actual'
#DEFINE LANG_PWRKCNT_Forecast 'Forecast'
#DEFINE LANG_PWRKCNT_Humans 'Humans'
#DEFINE LANG_PWRKCNT_Machines 'Machines'
#DEFINE LANG_PWRKCNT_Employee_ID 'Employee ID'
#DEFINE LANG_PWRKCNT_Employee_Name 'Employee Name'
#DEFINE LANG_PWRKCNT_Work_Center 'Work Center'
#DEFINE LANG_PWRKCNT_Machine_ID 'Machine ID'
#DEFINE LANG_PWRKCNT_Machine_Desc 'Machine Description'
#DEFINE LANG_PWRKCNT_Type_field 'Type field'
#DEFINE LANG_PWRKCNT_Name_field 'Name field'
#DEFINE LANG_PWRKCNT_Plant_field 'Plant field'
#DEFINE LANG_PWRKCNT_Machine_Desc 'Machine Description'
#DEFINE LANG_PWRKCTR_COST_CENTER 'Cost Center'
*N000682,1 HES Handle globalization issues [End  ]