#DEFINE LANG_ALLOCENTRY 'Allocation Entry'
#DEFINE LANG_AUTOMAICENTRYCODE  'Automatic entry code'
#DEFINE LANG_REFERENCE 'Reference'
#DEFINE LANG_DESCRIPTION 'Description'
#DEFINE LANG_ALLOCATIONACCOUNTCODE 'Allocation account code'
#DEFINE LANG_AUOMATICENTRYBASE 'Automatic entry base'
#DEFINE LANG_RECURRBEGINDATE 'Recurring begin date'
#DEFINE LANG_RECURRENDDATE 'Recurring end date'
#DEFINE LANG_LASTRECURR 'Last recurring gen. date'
#DEFINE LANG_NEXTRECURR 'Next recurring gen. date'
#DEFINE LANG_FREQUENCYUNIT 'Frequency unit'
#DEFINE LANG_FREQUENCYNUMBER 'Frequency number'
#DEFINE LANG_REVERSETRANSACTION 'Reverse transaction'
#DEFINE LANG_SOURCEJOURNAL 'Source journal entry'
#DEFINE LANG_AMOUNTS "Amounts"
#DEFINE LANG_PERCENT "Percent"
#DEFINE LANG_CREATEDBY 'Created by '
#DEFINE LANG_ON 'On'
#DEFINE LANG_ALLOCATEDPERCNTAGES 'allocated percentages '
#DEFINE LANG_ALLOCATETRANS 'allocation transaction|allocation transaction '
#DEFINE LANG_EITHERDEBITCREDIT 'either debit or credit '
#DEFINE LANG_THEALLOCPERCENT 'the allocation percentage '
#DEFINE LANG_TOTALS 'Totals : '
#DEFINE LANG_TOTAL1 'Total : '
#DEFINE LANG_DEBIT 'Debit'
#DEFINE LANG_CREDIT 'Credit'
#DEFINE LANG_ALLOCPERCENT 'Allocation % '
#DEFINE LANG_SAVING 'Saving allocation entry'
#DEFINE LANG_DELETEING 'Deleting allocation entry'
#DEFINE LANG_S_DEBIT  'Debit '
#DEFINE LANG_S_CREDIT 'Credit '
#DEFINE LANG_S_ALLOCPERCENT 'Allocation %'
#DEFINE LANG_S_AUTO 'Automatic Entry Code:'
#DEFINE LANG_S_SAVING 'Saving allocation entry '
#DEFINE LANG_S_DELETING 'Deleting allocation entry '