#DEFINE LANG_Select_Auto_Types          'Select types for automatic entries...'
#DEFINE LANG_GLCPAUT_AutType            'Type'
#DEFINE LANG_GLCPAUT_AutCode            'Code'
#DEFINE LANG_GLCPAUT_AutDesc            'Description'
#DEFINE LANG_GLCPAUT_CopyStat           'Copy status'
#DEFINE LANG_Select_Caption             '\<Select'
#DEFINE LANG_Unselect_Caption           '\<Unselect'


#DEFINE LANG_GLCPTYP_AutType            'Type'
#DEFINE LANG_GLCPTYP_AutDesc            'Description'
#DEFINE LANG_GLCPTYP_CopyStat           'Copy status'


#DEFINE LANG_View_Budget_Details        '\<View budget details'
#DEFINE LANG_GLCPBUD_Budget_Code        'Budget code'
#DEFINE LANG_GLCPBUD_Budget_Year        'Year'
#DEFINE LANG_GLCPBUD_Budget_Desc        'Description'
#DEFINE LANG_GLCPBUD_CopyStat           'Copy status'
#DEFINE LANG_GLCPBUD_GLDETAL_Title      'View details for current budget'
#DEFINE LANG_GLCPBUD_GLDETAL_Code       'ACT'
#DEFINE LANG_GLCPBUD_GLDETAL_Desc       'Description'


#DEFINE LANG_View_Group_Details         '\<View group details'
#DEFINE LANG_GLCPGRP_Group_Code         'Group code'
#DEFINE LANG_GLCPGRP_Group_Desc         'Description'
#DEFINE LANG_GLCPGRP_CopyStat           'Copy status'
#DEFINE LANG_GLCPGRP_GLDETAL_Title      'Groupd accounts'
#DEFINE LANG_GLCPGRP_GLDETAL_Code       'ACT'
#DEFINE LANG_GLCPGRP_GLDETAL_Desc       'Description'


#DEFINE LANG_Select_Segments            'Select segment values to be copied...'
#DEFINE LANG_GLCPSEG_Segment_No         'Seg. No'
#DEFINE LANG_GLCPSEG_Segment_Value      'Segment Value'
#DEFINE LANG_GLCPSEG_Segment_Desc       'Description'
#DEFINE LANG_GLCPSEG_CopyStat           'Copy status'


#DEFINE LANG_Select_Accounts            'Select accounts to be copied...'
#DEFINE LANG_GLCPACT_Acount_Type        'Type'
#DEFINE LANG_GLCPACT_Acount_Code        'ACT'
#DEFINE LANG_GLCPACT_Account_Desc       'Description'
#DEFINE LANG_GLCPACT_CopyStat           'Copy status'
