# DEFINE LANG_ArCodTG_Inv        'Invoice'
# DEFINE LANG_ArCodTG_Prntd      'Printed'
# DEFINE LANG_ArCodTG_Date       'Date'
# DEFINE LANG_ArCodTG_Acc        'Account'
# DEFINE LANG_ArCodTG_Ord        'Order'
# DEFINE LANG_ArCodTG_Ref        'Reference'
# DEFINE LANG_ArCodTG_BillTo     'Bill to'
# DEFINE LANG_ArCodTG_SRep       'Sales Rep.'
# DEFINE LANG_ArCodTG_Pieces     'Pieces'
# DEFINE LANG_ArCodTG_Merch      'Merchandise'
# DEFINE LANG_ArCodTG_FileTitle  'Receivable invoices'
# DEFINE LANG_ArCodTG_WaitWind1  'Selecting records for report ...'
# DEFINE LANG_ArCodTG_WaitWind2  'Printing Labels for Invoice No. '