#DEFINE LANG_CONTRACTLABEL               "Contract"
#DEFINE LANG_LabelOrder                  "Order"
#DEFINE LANG_ObjectLink                  "Image Link"
#DEFINE LANG_Options                     "O\<ptions"
#DEFINE LANG_OptionOrderNotes            "\<Order Notes"
#DEFINE LANG_OptionObjectLink            "Ima\<ge Link"
#DEFINE LANG_OptionCustomerInquire       "Customer \<Inquire"
#DEFINE LANG_OptionCustomerNotepad       "Customer \<Notepad"
#DEFINE LANG_OptionAgingSummary          "\<Aging Summary"
#DEFINE LANG_OptionStyleInquire          "\<Style Inquire"
#DEFINE LANG_OptionSortByLine            "Sort By Lin\<e#"
#DEFINE LANG_OptionSortBYStyle           "Sort BY St\<yle"
#DEFINE LANG_OptionSortByStore           "Sort By Sto\<re"
#DEFINE LANG_OptionShowQuantityperSize   "Show \<Quantity per Size"
#DEFINE LANG_OptionShowSummary           "Show Su\<mmary"
#DEFINE LANG_OptionOrderTransactions     "Order \<Transactions"
#DEFINE LANG_OptionLineNotepad           "\<Line Notepad"
#DEFINE LANG_OptionCopyLine              "\<Copy Line"
#DEFINE LANG_OptionPasteLine             "\<Paste Line"
#DEFINE LANG_OptionZoomOrderLines        "\<Zoom Order Lines"
#DEFINE LANG_OptionEditOrderLines        "\<Edit Order Lines"
#DEFINE LANG_OptionSendAcknowledgement   "Send 855 Ac\<knowledgement"
#DEFINE LANG_OptionAcceptOrder           "\<Accept for 855 Acknowledgement"
#DEFINE LANG_OptionRejectOrder           "\<Reject for 855 Acknowledgement"
*ras
#DEFINE LANG_OptionSend865Acknowledgement   "Send 865 Ac\<knowledgement"
#DEFINE LANG_Option865AcceptOrder           "\<Accept for 865 Acknowledgement"
#DEFINE LANG_Option865RejectOrder           "\<Reject for 865 Acknowledgement"
#DEFINE LANG_OptionGenSendAcknowledgement   "Send Ac\<knowledgement"
#DEFINE LANG_OptionGenAcceptOrder           "\<Accept for Acknowledgement"
#DEFINE LANG_OptionGenRejectOrder           "\<Reject for Acknowledgement"
*ras
#DEFINE LANG_OptionOpen                  "\<Open"
#DEFINE LANG_OptionBooked                "\<Booked"
#DEFINE LANG_OptionShipped               "\<Shipped"
#DEFINE LANG_OptionProduction            "\<Production"
#DEFINE LANG_OptionDepletion             "\<Depletion"
#DEFINE LANG_OptionBulkorder             "Bul\<k order"
#DEFINE LANG_OptionCanceled              "\<Canceled"
#DEFINE LANG_OptionWorkOrder             "\<Work Order"
*E302774,1 TMI 10/18/2010 [Start] add the definition of the REMOVED LINES option  
#DEFINE LANG_OptionRemovedLines'\<Removed Lines'
*E302774,1 TMI 10/18/2010 [End  ] 
#DEFINE LANG_LabelDyelot         "Dyelot"
#DEFINE LANG_LabelCOnfiguration  "Configuration"
#DEFINE LANG_LabelStore          "Store"
#DEFINE LANG_LabelCustPo         "Cust. PO#"
#DEFINE LANG_LabelQuantity       "Quantity"
#DEFINE LANG_LabelWholeSale      "Wholesale Price"
#DEFINE LANG_LabelAmount         "Amount"
#DEFINE LANG_LabelPicked         "Picked"
#DEFINE LANG_LabelQty1           "Qty1"
#DEFINE LANG_LabelQty2           "Qty2"
#DEFINE LANG_LabelQty3           "Qty3"
#DEFINE LANG_LabelQty4           "Qty4"
#DEFINE LANG_LabelQty5           "Qty5"
#DEFINE LANG_LabelQty6           "Qty6"
#DEFINE LANG_LabelQty7           "Qty7"
#DEFINE LANG_LabelQty8           "Qty8"
#DEFINE LANG_LabelPik1           "Pik1"
#DEFINE LANG_LabelPik2           "Pik2"
#DEFINE LANG_LabelPik3           "Pik3"
#DEFINE LANG_LabelPik4           "Pik4"
#DEFINE LANG_LabelPik5           "Pik5"
#DEFINE LANG_LabelPik6           "Pik6"
#DEFINE LANG_LabelPik7           "Pik7"
#DEFINE LANG_LabelPik8           "Pik8"
#DEFINE LANG_LabelBook           "Booked" 
#DEFINE LANG_LabelBook1          "Book1"
#DEFINE LANG_LabelBook2          "Book2"
#DEFINE LANG_LabelBook3          "Book3"
#DEFINE LANG_LabelBook4          "Book4"
#DEFINE LANG_LabelBook5          "Book5"
#DEFINE LANG_LabelBook6          "Book6"
#DEFINE LANG_LabelBook7          "Book7"
#DEFINE LANG_LabelBook8          "Book8"
#DEFINE LANG_LabelCan            "Cancelled"
#DEFINE LANG_LabelCanDate        "Can. Date"
#DEFINE LANG_LabelCanReason      "Cancelation Reason"
#DEFINE LANG_LabelCan1           "Can1"
#DEFINE LANG_LabelCan2           "Can2"
#DEFINE LANG_LabelCan3           "Can3"
#DEFINE LANG_LabelCan4           "Can4"
#DEFINE LANG_LabelCan5           "Can5"
#DEFINE LANG_LabelCan6           "Can6"
#DEFINE LANG_LabelCan7           "Can7"
#DEFINE LANG_LabelCan8           "Can8"
#DEFINE LANG_LabelUsed           "Used"
#DEFINE LANG_LabelUsed1          "Used1"
#DEFINE LANG_LabelUsed2          "Used2"
#DEFINE LANG_LabelUsed3          "Used3"
#DEFINE LANG_LabelUsed4          "Used4"
#DEFINE LANG_LabelUsed5          "Used5"
#DEFINE LANG_LabelUsed6          "Used6"
#DEFINE LANG_LabelUsed7          "Used7"
#DEFINE LANG_LabelUsed8          "Used8"
#DEFINE LANG_LabelBalance        "Balance"
#DEFINE LANG_LabelBalance1       "Bal1"
#DEFINE LANG_LabelBalance2       "Bal2"
#DEFINE LANG_LabelBalance3       "Bal3"
#DEFINE LANG_LabelBalance4       "Bal4"
#DEFINE LANG_LabelBalance5       "Bal5"
#DEFINE LANG_LabelBalance6       "Bal6"
#DEFINE LANG_LabelBalance7       "Bal7"
#DEFINE LANG_LabelBalance8       "Bal8"
#DEFINE LANG_LabelOpen           "Open"
#DEFINE LANG_LabelOpen1          "Open1"
#DEFINE LANG_LabelOpen2          "Open2"
#DEFINE LANG_LabelOpen3          "Open3"
#DEFINE LANG_LabelOpen4          "Open4"
#DEFINE LANG_LabelOpen5          "Open5"
#DEFINE LANG_LabelOpen6          "Open6"
#DEFINE LANG_LabelOpen7          "Open7"
#DEFINE LANG_LabelOpen8          "Open8"
#DEFINE LANG_LabelComm1          "Comm1"
#DEFINE LANG_LabelComm2          "Comm2"
#DEFINE LANG_LabelGroup          "Group"
#DEFINE LANG_LabelGrossPrice     "Gross Price"
#DEFINE LANG_LabelDisc           "Disc.%"
#DEFINE LANG_LabelTransPrice     "Transmitted Price"
#DEFINE LANG_LabelPrice          "Price"
#DEFINE LANG_LabelStatus         "Status"
#DEFINE LANG_LabelPickTicket     "Pick Ticket"
#DEFINE LANG_LabelPickDate       "Pick Date"
#DEFINE LANG_LabelColorDesc      "Color Description"
#DEFINE LANG_Labelvendorsty      "Vendor style"
#DEFINE LANG_LabelName           "Name"
#DEFINE LANG_LabelStyleDesc      "Description"
#DEFINE LANG_LabelAlo1           "Alo1"
#DEFINE LANG_LabelAlo2           "Alo2"
#DEFINE LANG_LabelAlo3           "Alo3"
#DEFINE LANG_LabelAlo4           "Alo4"
#DEFINE LANG_LabelAlo5           "Alo5"
#DEFINE LANG_LabelAlo6           "Alo6"
#DEFINE LANG_LabelAlo7           "Alo7"
#DEFINE LANG_LabelAlo8           "Alo8"
#DEFINE LANG_LabelOrd1           "Ord1"
#DEFINE LANG_LabelOrd2           "Ord2"
#DEFINE LANG_LabelOrd3           "Ord3"
#DEFINE LANG_LabelOrd4           "Ord4"
#DEFINE LANG_LabelOrd5           "Ord5"
#DEFINE LANG_LabelOrd6           "Ord6"
#DEFINE LANG_LabelOrd7           "Ord7"
#DEFINE LANG_LabelOrd8           "Ord8"
#DEFINE LANG_LabelShp            "Shipped"
#DEFINE LANG_LabelShp1           "Ship1"
#DEFINE LANG_LabelShp2           "Ship2"
#DEFINE LANG_LabelShp3           "Ship3"
#DEFINE LANG_LabelShp4           "Ship4"
#DEFINE LANG_LabelShp5           "Ship5"
#DEFINE LANG_LabelShp6           "Ship6"
#DEFINE LANG_LabelShp7           "Ship7"
#DEFINE LANG_LabelShp8           "Ship8"
#DEFINE LANG_LabelInvoice        "Invoice#"
#DEFINE LANG_LabelInvoiceDate    "Inv. Date"
#DEFINE LANG_LabelCT             "C/T#"
#DEFINE LANG_LabelPO             "P/O#"
#DEFINE LANG_LabelEntered        "Entered"
#DEFINE LANG_LabelComplete       "Complete"
#DEFINE LANG_LabelVendor         "Vendor"
#DEFINE LANG_LabelQtyAlo         "Qty. Alo."
#DEFINE LANG_LabelQtyOrd         "Qty. Ord."
#DEFINE LANG_LabelQtyOpn         "Qty. Opn."
#DEFINE LANG_StatusBid          "Bid" 
#DEFINE LANG_StatusOpen         "Open" 
#DEFINE LANG_StatusHold         "Hold"
#DEFINE LANG_StatusCanceled     "Canceled" 
#DEFINE LANG_StatusComplete     "Complete" 
#DEFINE LANG_COLOrder            "Order#"
#DEFINE LANG_COLStatus           "Status"
#DEFINE LANG_COLAccount          "Acct"
#DEFINE LANG_COLStore            "Store"
#DEFINE LANG_COLname             "Name"
#DEFINE LANG_COLDept             "Department"
#DEFINE LANG_COLMultiPo          "Multi PO"
#DEFINE LANG_COLCustPo           "Cust. P.O#"
#DEFINE LANG_COLBulk             "Bulk"
#DEFINE LANG_COLMulti            "Multi"
#DEFINE LANG_COLcFacCode         "Factor Code"
#DEFINE LANG_COLRep1             "Sales Rep1"
#DEFINE LANG_COLComm1            "Commission 1"
#DEFINE LANG_COLRep2             "Sales Rep2"
#DEFINE LANG_COLComm2            "Commission 2"
#DEFINE LANG_COLOpen             "Open.Qty."
#DEFINE LANG_COLOpenAmt          "Open.Amt."
#DEFINE LANG_COLShip             "Ship.Qty."
#DEFINE LANG_COLShipAmt          "Ship.Amt."
#DEFINE LANG_COLBook             "Book.Qty."
#DEFINE LANG_COLBookAmt          "Book.Amt."
#DEFINE LANG_COLCancel           "Cancel.Qty."
#DEFINE LANG_COLCancelAmt        "Cancel.Amt."
#DEFINE LANG_COLEntered          "Entered"
#DEFINE LANG_COLStart            "Start"
#DEFINE LANG_COLComplete         "Complete"
#DEFINE LANG_COLCancelled        "Cancelled"
#DEFINE LANG_COLDisc             "Disc."
#DEFINE LANG_COLcWareCode        "Warehouse"
#DEFINE LANG_COLcAdd_User        "User"
#DEFINE LANG_COLdAdd_Date        "Date"
#DEFINE LANG_COLSeason           "Season"
#DEFINE LANG_COLDivision         "Division"
#DEFINE LANG_COLShipVia          "ShipVia"
#DEFINE LANG_COLNote1            "Notes 1"
#DEFINE LANG_COLNote2            "Notes 2"
#DEFINE LANG_COLCurrCode         "Currency"
#DEFINE LANG_COLExRate           "Ex. Rate"
#DEFINE LANG_COLCurrUnit         "Unit"
#DEFINE LANG_TipCancelOrder      "Cancel Order"
#DEFINE LANG_TipUnCancelOrder    "Uncancel Order"
#DEFINE LANG_TipCancelContract   "Cancel Contract"
#DEFINE LANG_TipUnCancelContract "Uncancel Contract"
#DEFINE LANG_OrderBrowse         "Orders"
#DEFINE LANG_NoOrdersFound       "orders matching the"
#DEFINE LANG_OpenBulkOrders      "Open bulk orders"
#DEFINE LANG_ColTerms            "Terms"
#DEFINE LANG_Departments         "Departments"
#DEFINE LANG_Factor              "Factor"
#DEFINE LANG_Contact             "Contact"
#DEFINE LANG_Phone               "Phone"
#DEFINE LANG_Factors             "Factors"
#DEFINE LANG_Message1            " while some stores are Potential. If you keep the order as "
#DEFINE LANG_Message2            ", the Potential Stores will be changed to Active. Otherwise, Keep the Potential Stores"
#DEFINE LANG_OptionReplaceConfig "Replace Configuration"
#DEFINE LANG_ARIAEDITREGION_Shipped "Shipped"
*B609618,1 MMT 06/16/2011 Cannot print order confirmation of EDI Temp. Order from scr.[T20110608.0006][Start]
*#DEFINE REPORT_DATA "laData[1]=ORDHDR.ORDER"
#DEFINE REPORT_DATA "laData[1]=ORDHDR.CORDTYPE,laData[2]=ORDHDR.ORDER"
*B609618,1 MMT 06/16/2011 Cannot print order confirmation of EDI Temp. Order from scr.[T20110608.0006][END]
#DEFINE LANG_ORDERCONTRACTCAPTION    "Sales Order Contract"
#DEFINE LANG_EDIORDERCAPTION         "EDI Temporary Sales Order"
#DEFINE LANG_OptionOrderShippingWizard   "Sales Order Shipping \<Wizard"
#DEFINE LANG_OptionPackInfo              "Packing \<Information"
#DEFINE LANG_LabelLineNo                 "Line #"
#DEFINE LANG_LabelSize                   "Size"
#DEFINE LANG_LabelPack                   "Pack"
#DEFINE LANG_LabelPackUnits              "Pack Units"
#DEFINE LANG_LabelInnerPack              "Inner Pack"

*!* E302590,1 MMT 03/31/2009 Add Alternative Ship Address screen to Sales order screen[Start]
#DEFINE LANG_ALTSHPADD1		             'Address1'
#DEFINE LANG_ALTSHPADD2		             'Address2'
#DEFINE LANG_ALTSHPADD3		             'Address3'
#DEFINE LANG_ALTSHPADD4		             'Address4'
#DEFINE LANG_ALTSHPADD5		             'Address5'
#DEFINE LANG_ALTSHPADD6		             'Address6'
*!* E302590,1 MMT 03/31/2009 Add Alternative Ship Address screen to Sales order screen[End]

*B608873,1 WAM 05/25/2009 Call the project screen
#DEFINE LANG_PROJECT		             'Sales Order Project'
*B608873,1 WAM 05/25/2009 (End)

*B609223,1 MMT 04/28/2010 add option to SO screen to re-Open Completed orders[Start]
#DEFINE LANG_CHANGESTATUS 				'Change status to Open'
*B609223,1 MMT 04/28/2010 add option to SO screen to re-Open Completed orders[End]

*E302945,1 WAM 07/26/2011 Call Carrier Integration program
#DEFINE LANG_Carrier                "Carrier"
#DEFINE LANG_ProcessCarrierShipment "Process Carrier Shipmen\<t"
*E302945,1 WAM 07/26/2011 (End)
*N000682,1 MMT 11/22/2012 Globalization changes[Start]
#DEFINE LANG_SOSTORE_SELECT '\<Select' 
#DEFINE LANG_SOORD_WIZARDTOOLTIP 'Sales Order Shipping Wizard'
#DEFINE LANG_SOORD_ALTSHPADD "Alternate Shipping Address"
#DEFINE LANG_SOORD_SHPADD "Shipping Address"
#DEFINE LANG_SOORD_ATSTORELEVEL  'At Store Level' 
#DEFINE LANG_SOALTSHP_SELECTADD "Select Address"
#DEFINE LANG_SOALTSHP_BROWTITLE "Alternate Shipping Addresses"
#DEFINE LANG_SOORD_WAITUPDATELINES "Update Order Line..." 
#DEFINE LANG_SOORD_COLLECTDATESTANDBY 'Collecting data...Please standby.' 
#DEFINE LANG_SOORD_COPYBULKLINES 'Copy bulk order lines... Please standby'
#DEFINE LANG_SOUPDATE_UPDATEALLOCQTY 'Updating alocated quantity...' 
#DEFINE LANG_SOUPDATE_UPDATINGORDERLINE 'Updating order lines...'
#DEFINE LANG_SOUPDATE_UNCANCELANDUPDATE 'Uncancelling and updating Cut & Sold...'
#DEFINE LANG_SOUPDATE_CANCELANDUPDATE 'Cancelling and updating Cut & Sold...' 
#DEFINE LANG_SOORD_YES "Yes"
#DEFINE LANG_SOORD_NO "No "
#DEFINE LANG_SOORD_SHPPEDCOMPLETE 'has been shipped complete'
#DEFINE LANG_SOORD_HASBEENCANCELLED 'has been canceled'
#DEFINE LANG_SOORD_MSGACCOUNT 'account'
*N000682,1 MMT 11/22/2012 Globalization changes[END]

*E612592,1 MMT 06/27/2022 Add Contract Recurrence Information option to the Contract Screen[Start]
#DEFINE LANG_SOORD_CONTRACT_INFO_OPTION  '\<Contract Recurrence Information'
*E612592,1 MMT 06/27/2022 Add Contract Recurrence Information option to the Contract Screen[End]