#DEFINE LANG_BRFLD01 'View Item '
#DEFINE LANG_BRFLD02 "Description"
#DEFINE LANG_BRFLD03 "Long Description"
#DEFINE LANG_BRFLD04 "Season"
#DEFINE LANG_BRFLD05 "Division"
#DEFINE LANG_BRFLD06 "Price A"
#DEFINE LANG_BRFLD07 "Price B"
#DEFINE LANG_BRFLD08 "Price C"
#DEFINE LANG_BRFLD09 "WIP"
#DEFINE LANG_BRFLD10 "Stock"
#DEFINE LANG_BRFLD11 "Orders"
#DEFINE LANG_BRFLD12 "Fabric"
#DEFINE LANG_BRFLD13 "O.T.S."
#DEFINE LANG_BRFLD14 "Grade"
#DEFINE LANG_BRFLD15 'Royalty'
#DEFINE LANG_BRFLD16 'Pattern'
#DEFINE LANG_BRFLD17 'Status'
#DEFINE LANG_BRFLD18 'Scale'
#DEFINE LANG_BRFLD19 'Prepack'
#DEFINE LANG_BRFLD20 'Buy Prepack'
#DEFINE LANG_BRFLD21 'Qty/Carton'
#DEFINE LANG_BRFLD22 'Commission'
#DEFINE LANG_BRFLD23 'Link Code'
#DEFINE LANG_BRFLD24 'Manuf.'
#DEFINE LANG_BRFLD25 'Cost 1'
#DEFINE LANG_BRFLD26 'Cost 2'
#DEFINE LANG_BRFLD27 'Cost 3'
#DEFINE LANG_BRFLD28 'Cost 4'
#DEFINE LANG_BRFLD29 'Cost 5'
#DEFINE LANG_BRFLD30 'Total Cost'
#DEFINE LANG_BRFLD31 'Cost2 %'
#DEFINE LANG_BRFLD32 'Cost3 %'
#DEFINE LANG_BRFLD33 'Cost4 %'
#DEFINE LANG_BRFLD34 'Cost5 %'
#DEFINE LANG_BRFLD35 'Ave. Cost'
#DEFINE LANG_BRFLD36 'Stock Value'
#DEFINE LANG_BRFLD37 'Sold Out Date'
#DEFINE LANG_BRFLD38 'Start date'
#DEFINE LANG_BRFLD39 'Inventory'
#DEFINE LANG_BRFLD40 'Bin #'
#DEFINE LANG_BRFLD41 'Markup A'
#DEFINE LANG_BRFLD42 'Markup B'
#DEFINE LANG_BRFLD43 'Markup C'
#DEFINE LANG_BRFLD44 'Cons. Info. 1'
#DEFINE LANG_BRFLD45 'Cons. Info. 2'
#DEFINE LANG_BRFLD46 'Scale'
#DEFINE LANG_BRFLD47 'Style'
#DEFINE LANG_COLOR   'Color'