#DEFINE LANG_TaskClct "Collecting OutLook Tasks..."
#DEFINE LANG_APPClct "Collecting OutLook Appointments..."
#DEFINE LANG_MSGClct "Collecting OutLook Messages..."
#DEFINE LANG_ProfMSG "Enter outlook profile"
#DEFINE LANG_LoggMSG "Login into outlook. Please wait..."
