#DEFINE LANG_PWEMPL_QUALIFICATION_CODE 'Qualification Code'
#DEFINE LANG_PWEMPL_DESCRIPTION 'Description'        
#DEFINE LANG_PWEMPL_VALUE 'Value(%)'     
#DEFINE LANG_PWEMPL_SHIFT_ID  'Shift ID'                                                                                                                                                                 
#DEFINE LANG_PWEMPL_SHIFT_START_TIME 'Shift Start Time'        
#DEFINE LANG_PWEMPL_SHIFT_END_TIME 'Shift End Time'  
*N000682,1 HES Handle globalization issues [Start]
#DEFINE LANG_PWEMPL_Name_Field 'Name field'  
#DEFINE LANG_PWEMPL_Plant_Field 'Plant field'  
#DEFINE LANG_PWEMPL_Qualification_Field 'Qualification field'  
#DEFINE LANG_PWEMPL_Employee_Shifts 'Employee Shifts'  
#DEFINE LANG_PWEMPL_Shift_Validate 'Shift finish can not preceeds Shift Start'
#DEFINE LANG_PWEMPL_hiring_Date_Validate 'Terminate date can not preceeds hiring date'
#DEFINE LANG_PWEMPL_Employee_Validate 'Employee age can not be less than 18 years'
#DEFINE LANG_PWEMPL_Personnel_ID 'Personnel ID' 
#DEFINE LANG_PWEMPL_Employee_name 'Employee name' 
#DEFINE LANG_PWEMPL_First_name 'First name' 
#DEFINE LANG_PWEMPL_Last_name 'Last name' 
#DEFINE LANG_PWEMPL_Plant_Id 'Plant Id' 
#DEFINE LANG_PWEMPL_Work_center 'Work center No.' 
#DEFINE LANG_PWEMPL_Cost_Center 'Cost Center' 
#DEFINE LANG_PWEMPL_Department 'Department No.' 
#DEFINE LANG_PWEMPL_Phone_1 'Phone 1' 
#DEFINE LANG_PWEMPL_Phone_2 'Phone 2' 
#DEFINE LANG_PWEMPL_Hour_Rate 'Hour Rate' 
#DEFINE LANG_PWEMPL_Over_Time 'Over Time %' 
#DEFINE LANG_PWEMPL_Base_Code 'Base Code' 
#DEFINE LANG_PWEMPL_category 'category' 
#DEFINE LANG_PWEMPL_FREQUENCY 'PAY FREQUENCY' 
#DEFINE LANG_PWEMPL_PAYROLL 'PAYROLL TYPE' 
#DEFINE LANG_PWEMPL_Social_no 'Social no.'
*N000682,1 HES Handle globalization issues [End  ]