#DEFINE  xlNone  -4142
#DEFINE  xlEdgeLeft  7
#DEFINE  xlContinuous  1
#DEFINE  xlThin  2
#DEFINE  xlAutomatic -4105
#DEFINE  xlEdgeTop  8
#DEFINE  xlEdgeBottom  9
#DEFINE  xlEdgeRight  10
#DEFINE  xlInsideVertical  11
#DEFINE  xlSolid  1
#DEFINE  xlDiagonalDown  5
#DEFINE  xlDiagonalUp  6
