#DEFINE Lang_KeyOffTrans		"Keyed Off Transactions"
#DEFINE Lang_TranNo 			'Tran #'
#DEFINE Lang_Description 		'Description'
#DEFINE Lang_Amount				'Amount'
#DEFINE Lang_TranDate			'Tran. Date'
#DEFINE Lang_Store				'Store'
#DEFINE Lang_Reference			'Reference'
#DEFINE Lang_ProcessTrans 		"Processing Transaction Number : "
#DEFINE Lang_UpdateTrans		"Updating Transaction Number : "
#DEFINE Lang_UpdateSalesRep		"Updating Sales Rep. commission for : "


*E611823,1 MMT 12/23/2019 Change Key off screen to use new GL tables[GL Enhancement][Start] 
#DEFINE LANG_GLDIST_INVOICE 'INVOICE             '
#DEFINE LANG_GLDIST_VOIDINVOICE 'VOID INVOICE        '
#DEFINE LANG_GLDIST_CASHR 'CASH RECEIPT        '
#DEFINE LANG_GLDIST_CREDITADJ 'CREDIT ADJUSTMENT   '
#DEFINE LANG_GLDIST_DEBITADJ 'DEBIT ADJUSTMENT    '
#DEFINE LANG_GLDIST_RM 'RETURN MERCHANDISE  '
#DEFINE LANG_GLDIST_VOIDRM 'VOID RETURN         '
#DEFINE LANG_GLDIST_INVPHY 'INVENTORY PHYSICAL  '
#DEFINE LANG_GLDIST_INVADJ 'INVENTORY ADJUSTMENT'
#DEFINE LANG_GLDIST_MATINVPHY 'MATERIAL INV. PHYSI.'
#DEFINE LANG_GLDIST_MATINVDJ 'MATERIAL INV. ADJUS.'
#DEFINE LANG_GLDIST_POREC 'P/O RECEIVING       '
#DEFINE LANG_GLDIST_MAPOREC 'MATERIAL P/O RECEIV.'
#DEFINE LANG_GLDIST_CTREC 'C/T RECEIVING       '
#DEFINE LANG_GLDIST_ZEROOUT 'ZERO OUT STOCK      '
#DEFINE LANG_GLDIST_NONMATLIB 'NON MAT. LIABILITY  '
#DEFINE LANG_GLDIST_POJOBCLOSE 'P/O JOB COST CLOSING'
#DEFINE LANG_GLDIST_MATOPREC 'MATERIAL OP. RECEIVE'
#DEFINE LANG_GLDIST_STYOPREC 'STYLE OP. RECEIVE   '
#DEFINE LANG_GLDIST_RECMFGORDER 'RECEIVE M.F.G. ORDER'
#DEFINE LANG_GLDIST_EXRATEDIFF 'EX. RATE DIFFERENCES'
#DEFINE LANG_GLDIST_KEYOFF 'KEY OFF'
#DEFINE LANG_GLDIST_MAJOBCLOSE 'MATERIAL JOB ClOSING'
#DEFINE LANG_GLDIST_CTJOBCLOSE 'C/T JOB COST CLOSING'
#DEFINE LANG_GLDIST_INVLOCK 'INVENTORY LOCKING'
*E611823,1 MMT 12/23/2019 Change Key off screen to use new GL tables[GL Enhancement][End] 


