#DEFINE LANG_HdInv 'Invoice'
#DEFINE LANG_HdDate 'Date'
#DEFINE LANG_HdStore 'Store'
#DEFINE LANG_HdOrder 'Order'
#DEFINE LANG_HdAcct 'Account'
#DEFINE LANG_HdAmt 'Amount'
#DEFINE LANG_HdPik 'Piktkt'
#DEFINE LANG_HdCstPo 'Cust P/O'
#DEFINE LANG_Invoices 'Invoices'
