#DEFINE LANG_ROLL "Rolls"
#DEFINE LANG_LOTS "Lots"
#DEFINE LANG_GRDFLD01  "R.Session"
#DEFINE LANG_GRDFLD02  "Date"
#DEFINE LANG_GRDFLD03  "Roll ID"
#DEFINE LANG_GRDFLD04  "Roll Bal."
#DEFINE LANG_GRDFLD05  "Roll balance"
#DEFINE LANG_GRDFLD06  "Apply Qty."      
#DEFINE LANG_GRDFLD07  "Issue Qty."
#DEFINE LANG_GRDFLD08  "Curr. Bal."
#DEFINE LANG_GRDFLD09  "New Bal."
#DEFINE LANG_GRDFLD10  "New balance"
#DEFINE LANG_GRDFLD11  "Unit Cost"
#DEFINE LANG_GRDFLD12  "Tran."
#DEFINE LANG_GRDFLD13  "Received"
#DEFINE LANG_GRDFLD14  "Issued"
#DEFINE LANG_GRDFLD15  "Current balance"
#DEFINE LANG_MESSGE1   "Applied quantity is not allowed to be negative."
#DEFINE LANG_MESSGE2   "Applied quantity is not allowed to decrease."
#DEFINE LANG_RECIVE  "receive"
#DEFINE LANG_RETURN  "return"
#DEFINE LANG_ISSUE   "Issue"
#DEFINE LANG_ADJUST  "adjust"
#DEFINE LANG_RANGE   "Range"
#DEFINE LANG_ROLLEXIST "This roll id already exist."
*N000682,1 MMT 11/20/2012 Globalization project[Start]
#DEFINE LANG_MALOTRO_NEW_BAL_COL     'NEW BAL. :'
#DEFINE LANG_MFMAROL_ASSIGNED   'Assigned'
*N000682,1 MMT 11/20/2012 Globalization project[End]