#DEFINE LANG_POEstLnd_Total       "Total"
#DEFINE LANG_POEstLnd_TotalMisc   "Total Misc."
#DEFINE LANG_POEstLnd_Open        "Open"
#DEFINE LANG_POEstLnd_Complete    "Complete"
#DEFINE LANG_POEstLnd_Closed      "Closed"
#DEFINE LANG_POEstLnd_MoverMsg    "Select Po Status"
