//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AriaMenu
    {
        public string ProductId { get; set; }
        public int MenuId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string MenuType { get; set; }
        public Nullable<int> MenuPosition { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Shortcut { get; set; }
        public string Icon { get; set; }
        public string MenuSettings { get; set; }
        public Nullable<bool> ShowInListView { get; set; }
        public Nullable<int> ObjectID { get; set; }
    }
}
