//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SystemMaster : DbContext
    {
        public SystemMaster()
            : base("name=SystemMaster")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AriaClientProduct> AriaClientProducts { get; set; }
        public DbSet<AriaFavorite> AriaFavorites { get; set; }
        public DbSet<AriaMenu> AriaMenus { get; set; }
        public DbSet<AriaProduct> AriaProducts { get; set; }
        public DbSet<AriaRole> AriaRoles { get; set; }
        public DbSet<AriaRoleObjectSecurityPrivilege> AriaRoleObjectSecurityPrivileges { get; set; }
        public DbSet<AriaSetting> AriaSettings { get; set; }
        public DbSet<AriaSettingCategory> AriaSettingCategories { get; set; }
        public DbSet<AriaUser> AriaUsers { get; set; }
        public DbSet<AriaUserRole> AriaUserRoles { get; set; }
        public DbSet<AriaUserSetting> AriaUserSettings { get; set; }
        public DbSet<Client> CLIENTS { get; set; }
        public DbSet<HostingServer> HostingServers { get; set; }
    }
}
