#DEFINE LANG_APAPLDB_OPENINV   		 "open invoices"
#DEFINE LANG_APAPLDB_DEBITMEMO    	 "debit memo "
#DEFINE LANG_APAPLDB_SESSION      	 "   Session: "
#DEFINE LANG_APAPLDB_VENDORS       	 "Vendors"
#DEFINE LANG_APAPLDB_VENDCODE    	 'Vendor Code'
#DEFINE LANG_APAPLDB_COMPANY		 'Company'
#DEFINE LANG_APAPLDB_PHONE			 'Phone'
#DEFINE LANG_APAPLDB_INVOICENO 		 "Inv. No."
#DEFINE LANG_APAPLDB_INVOICEDATE 	 "Inv. Date"
#DEFINE LANG_APAPLDB_DUEDATE 		 "Due Date"
#DEFINE LANG_APAPLDB_P 				 "Priority"
#DEFINE LANG_APAPLDB_OPENAMT 		 "Open Amount"
#DEFINE LANG_APAPLDB_TOTALAPP 		 "Total Approved"
#DEFINE LANG_APAPLDB_PAYMTHD		 "Pay. Method"
#DEFINE LANG_APAPLDB_DIVISION 		 "Division"
#DEFINE LANG_APAPLDB_DMNO			 "DM. No."
#DEFINE LANG_APAPLDB_DMDATE			 "DM. Date"
#DEFINE LANG_APAPLDB_REFER			 "Reference"
#DEFINE LANG_APAPLDB_OPENBAL 		 "Open Balance"
#DEFINE LANG_APAPLDB_CURRCODE 		 "Currency Code"
#DEFINE LANG_APAPLDB_DEBITMEMOS    	 "Debit memos"
#DEFINE LANG_APAPLDB_EDITING		 "You are editing "
#DEFINE LANG_APAPLDB_FORVEND		 " for vendor "
#DEFINE LANG_APAPLDB_ANOTHSESS		 "  in another session."
#DEFINE LANG_APAPLDB_INVOICE         "Invoice "
#DEFINE LANG_APAPLDB_VENDOR			 "Vendor "
#DEFINE LANG_APAPLDB_EDITED			 " is being edited by user "
#DEFINE LANG_APAPLDB_DUEFROM 		 "due from"
#DEFINE LANG_APAPLDB_DUETO			 "due to"
#DEFINE LANG_APAPLDB_DISCOUNTFROM	 "discount from"
#DEFINE LANG_APAPLDB_DISCOUNTTO		 "discount to"
#DEFINE LANG_APAPLDB_INVINFO		 'Invoice Information'
#DEFINE LANG_APAPLDB_DBINFO			 'Debit Memo Information'
#DEFINE LANG_APAPLDB_1099AMT		 '1099 Amount'
#DEFINE LANG_APAPLDB_ADJAPP			 'Adjustment Applied'
#DEFINE LANG_APAPLDB_AMOUNT			 'Amount'
#DEFINE LANG_APAPLDB_DBAMOUNT		 'Debit Memo Amount'
#DEFINE LANG_APAPLDB_DBDATE			 'Debit Memo Date'
#DEFINE LANG_APAPLDB_DATE			 'Date'
#DEFINE LANG_APAPLDB_DISCOUNT		 'Discount Taken'
#DEFINE LANG_APAPLDB_DBTMEMO    	 "Debit Memo "
#DEFINE LANG_APAPLDB_DBDUEDATE 		 'Debit Memo Due Date'
#DEFINE LANG_APAPLDB_PAID			 'Paid'
#DEFINE LANG_APAPLDB_REMIT			 'Remit To'
#DEFINE LANG_APAPLDB_APPDB		     "The applied|debit memo "
#DEFINE LANG_APAPLDB_APPINV 	 	 "The total applied|invoice "
#DEFINE LANG_APAPLDB_DISCACC		 "discount account" 
#DEFINE LANG_APAPLDB_TDiv  			 "division"
#DEFINE LANG_APAPLDB_TApSetup 		 "the AP setup"
#DEFINE LANG_APAPLDB_ALLINVOICE		 'all invoices'
#DEFINE LANG_APAPLDB_PAIDINV		 "paid"
#DEFINE LANG_APAPLDB_VOIDED			 "voided"
#DEFINE LANG_APAPLDB_ALLINV			 "all invoices"
#DEFINE LANG_APAPLDB_APPDATE		 "application date"
#DEFINE LANG_APAPLDB_HSTPROR		 'history prior   current  future  '
#DEFINE LANG_APAPLDB_INVONO			 'Invoice No. '
*!B610445,1 MMT 07/24/2013 Apply Debit Screen deos not filter invoice by currency[T20130717.0001][Start]
#DEFINE LANG_APAPL_SKIP 'skip'
*!B610445,1 MMT 07/24/2013 Apply Debit Screen deos not filter invoice by currency[T20130717.0001][End]*B610676,1 TMI 02/19/2014 19:03 [Start] Error message for some imbalances found in the new check while saving process
#DEFINE LANG_APAPLDB_IMBALANCE "Can not save, an imbalance in the saved data was detected"
*B610676,1 TMI 02/19/2014 19:03 [End  ] 