** Add A40 Fields Definitions to sydfield
SET DELETED ON
SET EXCLUSIVE OFF

** lcPath = '..\..\SYSFILES\SYDFIELD.DBF' : TO BE CORRECTED BY SABER
*lcPath = GETFILE('dbf')

IF EMPTY(lcPath )
  RETURN
ENDIF
IF JUSTFNAME(lcPath ) <> 'SYDFIELD.DBF'
  RETURN
ENDIF

USE R_SYDFIELD
SET FILTER TO CVER = 'A40'
LOCATE

SELECT 0
USE (lcPath ) ORDER CFLD_NAME
SET FILTER TO CVER = 'A40'
LOCATE

SELECT R_SYDFIELD
SCAN
  IF !SEEK(CFLD_NAME,'SYDFIELD')
    SCATTER MEMVAR MEMO
    INSERT INTO SYDFIELD FROM MEMVAR
    WAIT WINDOW NOWAIT CFLD_NAME
  ENDIF 
ENDSCAN
WAIT CLEAR
