#DEFINE LANG_ARIA_ConfigNum  	   "Configuration #"
#DEFINE LANG_ARIA_DyelotNum  	   "Dyelot #"
#DEFINE LANG_ARIA_Config     	   " Configurations"
#DEFINE LANG_ARIA_Dyelot     	   " Dyelots"
#DEFINE LANG_ARIA_Avl1     	 	   "Avl1"
#DEFINE LANG_ARIA_Avl2     	   	   "Avl2"
#DEFINE LANG_ARIA_Avl3     	       "Avl3"
#DEFINE LANG_ARIA_Avl4     	       "Avl4"
#DEFINE LANG_ARIA_Avl5     	       "Avl5"
#DEFINE LANG_ARIA_Avl6     	       "Avl6"
#DEFINE LANG_ARIA_Avl7     	       "Avl7"
#DEFINE LANG_ARIA_Avl8     	       "Avl8"
#DEFINE LANG_ARIA_TotAvl		   "TotAvl"
#DEFINE LANG_ARIA_Alo1     	 	   "Alo1"
#DEFINE LANG_ARIA_Alo2     	   	   "Alo2"
#DEFINE LANG_ARIA_Alo3     	       "Alo3"
#DEFINE LANG_ARIA_Alo4     	       "Alo4"
#DEFINE LANG_ARIA_Alo5     	       "Alo5"
#DEFINE LANG_ARIA_Alo6     	       "Alo6"
#DEFINE LANG_ARIA_Alo7     	       "Alo7"
#DEFINE LANG_ARIA_Alo8     	       "Alo8"
#DEFINE LANG_ARIA_TotAlo		   "TotAlo"
#DEFINE LANG_ARIA_Stk1     	 	   "Stk1"
#DEFINE LANG_ARIA_Stk2     	   	   "Stk2"
#DEFINE LANG_ARIA_Stk3     	       "Stk3"
#DEFINE LANG_ARIA_Stk4     	       "Stk4"
#DEFINE LANG_ARIA_Stk5     	       "Stk5"
#DEFINE LANG_ARIA_Stk6     	       "Stk6"
#DEFINE LANG_ARIA_Stk7     	       "Stk7"
#DEFINE LANG_ARIA_Stk8     	       "Stk8"
#DEFINE LANG_ARIA_TotStk		   "TotStk"
#DEFINE LANG_ARIA_MsgVar1		   " on the file"
#DEFINE LANG_ARIA_MsgVar2		   " in location "
#DEFINE LANG_ARIA_MsgSgx1          "Item\Warehouse :"
#DEFINE LANG_ARIA_MsgSgx2          "Item :"
#DEFINE LANG_ARIA_StyConfg         " Item Configuration "
#DEFINE LANG_ARIA_StyDyelot        " Item Dyelots "

#DEFINE LANG_ARIA_CITMMAJOR        "Item Code Major"
#DEFINE LANG_ARIA_CCSTSHT_ID       "Cost Sheet Code"
#DEFINE LANG_ARIA_CCSTSHTDSC       "Cost Sheet Description"
#DEFINE LANG_ARIA_LDEFCSTSHT       "Default Cost Sheet"
#DEFINE LANG_ARIA_CSTATUS          "Status"
#DEFINE LANG_ARIA_LBASONSIZ        "Base cost sheet on size"
#DEFINE LANG_ARIA_TOTCOST          "Total Cost"
#DEFINE LANG_ARIA_CCSTSHTTYP       "Procurement type"

#DEFINE LANG_ARIA_CONFIGMESG       "Configuration"
#DEFINE LANG_ARIA_DYELOTMESG       "Dyelot"
#DEFINE LANG_ARIA_Scale_Title      "Size Scales"

#DEFINE LANG_ARIA_UOM           "Units of Measurement"
#DEFINE LANG_ARIA_UOM_REL       "Relation Code"
#DEFINE LANG_ARIA_UOM_B         "Base UOM"
#DEFINE LANG_ARIA_UOM_V         "Converted UOM"
#DEFINE LANG_ARIA_UOM_CONF      "Conversion Factor"

#DEFINE LANG_ARIA_LOCATION      "Location"
#DEFINE LANG_ARIA_DESCRIPTION   "Description"
#DEFINE LANG_ARIA_LOCTTL        "Locations"


*N000682,1 MMT 11/20/2012 Globalization project[Start]
#DEFINE LANG_ARIA_ARIA_4_XP     "ARIA 4 XP"                                                                                                                                                                           #DEFINE LANG_ARIA_STYLE_TTL "Style"
#DEFINE LANG_ARIA_NODIMS 'No of Dimes'
#DEFINE LANG_ARIA_DIM1 'Dimention3'
#DEFINE LANG_ARIA_DIM2 'Dimention2'
#DEFINE LANG_ARIA_DIM3 'Dimention1'
#DEFINE LANG_ARIA_SCALEDESC 'Description'
#DEFINE LANG_ARIA_SCALECOLUMN 'Scale'
#DEFINE LANG_ARIA_SCALECNT 'Cnt'
#DEFINE LANG_ARIA_SCALESZ1 'Size 1'
#DEFINE LANG_ARIA_SCALESZ2 'Size 2'
#DEFINE LANG_ARIA_SCALESZ3 'Size 3'
#DEFINE LANG_ARIA_SCALESZ4 'Size 4'
#DEFINE LANG_ARIA_SCALESZ5 'Size 5'
#DEFINE LANG_ARIA_SCALESZ6 'Size 6'
#DEFINE LANG_ARIA_SCALESZ7 'Size 7'
#DEFINE LANG_ARIA_SCALESZ8 'Size 8'
#DEFINE LANG_ARIA_ACCNO 'Acct#'
#DEFINE LANG_ARIA_STATUS_CR 'S'
#DEFINE LANG_ARIA_REFERENCE 'Ref.'
#DEFINE LANG_ARIA_AMOUNT 'Amount'
#DEFINE LANG_ARIA_WAREHOUSE_CR 'WareHouse'
#DEFINE LANG_ARIA_FORACCOUNT 'for account: '
#DEFINE LANG_ARIA_S_STORE ' store: '
#DEFINE LANG_ARIA_CRMEMO_TITLE "Credit Memos"
#DEFINE LANG_ARIA_VEND_RETURNPO 'Return Purchase Orders'
#DEFINE LANG_ARIA_VEND_DYEPO 'Dye Purchase Order'
#DEFINE LANG_ARIA_VEND_CONTRACTS 'Contracts'
#DEFINE LANG_ARIA_VEND_ADORPO 'Adornment Purchase Order'
#DEFINE LANG_ARIA_VEND_STYLEPO 'Style Purchase Orders'
#DEFINE LANG_ARIA_VEND_INTERLOCPO 'Inter Location Purchase Orders'
#DEFINE LANG_ARIA_VEND_RETPO 'Return P/O'
#DEFINE LANG_ARIA_VEND_CONTARCT  'Contract'
#DEFINE LANG_ARIA_VEND_PO 'P/O '
#DEFINE LANG_ARIA_VEND_SOURCELOC 'Source Loc.'
#DEFINE LANG_ARIA_VEND_VENDOR 'Vendor'
#DEFINE LANG_ARIA_VEND_NAME 'Name'
#DEFINE LANG_ARIA_VEND_ENTERED 'Entered'
#DEFINE LANG_ARIA_VEND_COMPLETE 'Complete'
#DEFINE LANG_ARIA_VEND_TOTQTY 'Tot.Qty.'
#DEFINE LANG_ARIA_VEND_RECEIVE 'Receive'
#DEFINE LANG_ARIA_VEND_OPEN 'Open'
#DEFINE LANG_ARIA_VEND_SLOCATION 'location'
#DEFINE LANG_ARIA_VEND_SVENDOR 'vendor'
#DEFINE LANG_ARIA_VEND_ONFILE " on the file....!"
#DEFINE LANG_ARIA_VEND_FORTHIS "s for this "
#DEFINE LANG_ARIA_VEND_THEREARENO "There are no "
#DEFINE LANG_ARIA_RETAUTH_RANO "R/A #"
#DEFINE LANG_ARIA_RETAUTH_ISSUED "Issued"
#DEFINE LANG_ARIA_RETAUTH_PIECES "Pieces"
#DEFINE LANG_ARIA_RETAUTH_CARTONS "Cartons"
#DEFINE LANG_ARIA_RETAUTH_CUSTPO "Cust P/O"
#DEFINE LANG_ARIA_RETAUTH_INVOICE "Invoice"
#DEFINE LANG_ARIA_RETAUTH_VOID "Void"
#DEFINE LANG_ARIA_RETAUTH_ORDER 'Order'
#DEFINE LANG_ARIA_RETAUTH_COMPLETE 'This R/A is already complete!'
#DEFINE LANG_ARIA_RETAUTH_TITLE "Return Authorizations"
#DEFINE LANG_ARIA_RETAUTH_OPENRAS "Open R/As"
#DEFINE LANG_ARIA_RETAUTH_ACCOUNT "Account"
#DEFINE LANG_ARIA_RETAUTH_RAS "R/As"
#DEFINE LANG_ARIA_MATERIALPO 'Material Purchase Orders'
#DEFINE LANG_ARIA_MATERIALPOC 'Material Purchase Order Contracts'
#DEFINE LANG_ARIA_MATERIALPOR 'Material Purchase Order Returns'
#DEFINE LANG_ARIA_MATERIALNO 'No '
#DEFINE LANG_ARIA_MATERIALFOUND ' found'
#DEFINE LANG_ARIA_MATERIALFORVENDOR ' for vendor '
#DEFINE LANG_ARIA_APVENDOR 'A/P Vendors'
#DEFINE LANG_ARIA_APPHONE 'Phone'
#DEFINE LANG_ARIA_OURACC 'Our Account'
#DEFINE LANG_ARIA_EMPTYVENDORFILE 'Vendor file is empty'
#DEFINE LANG_ARIA_CURRENCY 'Currency'
#DEFINE LANG_ARIA_CURDESC 'Description'
#DEFINE LANG_ARIA_CURUNITS 'Units'
#DEFINE LANG_ARIA_CURSYMBOL 'Symbol'
#DEFINE LANG_ARIA_CURRS 'Currencies'
#DEFINE LANG_ARIA_BROWNOREC 'There are no records to browse.'
#DEFINE LANG_ARIA_CURRENTPERIOD 'Current'
*N000682,1 12/19/12 TMI Globlization changes[Start] add the salesrep title
#DEFINE LANG_ARIA_Sales_Representatives 'Sales Representatives'
*N000682,1 12/19/12 TMI Globlization changes[End  ] 
#DEFINE LANG_SALESREP_CODE "Code"
#DEFINE LANG_SALESREP_NAME "Name"
#DEFINE LANG_SALESREP_PHONE "Phone"
#DEFINE LANG_GLBROW_CUSTOMER 'Customer           '
#DEFINE LANG_GLBROW_SALES 'Sales              '
#DEFINE LANG_GLBROW_STYINV 'Style Invertory    '
#DEFINE LANG_GLBROW_MATINV 'Material Inverntory'
#DEFINE LANG_GLBROW_WIP 'Work in Process    '
#DEFINE LANG_GLBROW_TITLE 'GL Link Codes'
#DEFINE LANG_GLBROW_FOR 'for'
#DEFINE LANG_GLBROW_CODE 'Code'
#DEFINE LANG_GLBROW_DESC 'Description'
#DEFINE LANG_GLBROW_TYPE 'Type'
#DEFINE LANG_PPBROW_PREPACKS 'Prepacks'
#DEFINE LANG_PPBROW_SINGLEPREPACK 'Prepack'
#DEFINE LANG_PPBROW_TOTAL 'Total'
#DEFINE LANG_TRANTYPE_ADJ 'Adjustment        '
#DEFINE LANG_TRANTYPE_PHYINV 'Physical Inventory'
#DEFINE LANG_TRANTYPE_INVOICE 'Invoice           '
#DEFINE LANG_TRANTYPE_VINVOICE 'Void Invoice      '
#DEFINE LANG_TRANTYPE_RECCT 'Receive C/T       '
#DEFINE LANG_TRANTYPE_ISSADOR 'Issue Adornment order'
#DEFINE LANG_TRANTYPE_RECMFG 'Receive Mfg. Order'
#DEFINE LANG_TRANTYPE_PO 'P/O'
#DEFINE LANG_TRANTYPE_REC 'Receive'
#DEFINE LANG_TRANTYPE_ISSUE 'Issue'
#DEFINE LANG_TRANTYPE_RM 'Return Merchandise'
#DEFINE LANG_TRANTYPE_VCM 'Void Credit Memo  '
#DEFINE LANG_TRANTYPE_INVMARKDOWN 'Inventory Markdown'
#DEFINE LANG_PREPACK_NOPAREPACK 'There is no prepak for scale'
#DEFINE LANG_CHKPRD_MSG1 'does not fall within any period.'
#DEFINE LANG_CHKPRD_MSG2 'falls in a permanently locked period.'
#DEFINE LANG_CHKPRD_MSG3 'falls in a locked period.'
#DEFINE LANG_CHKPRD_MSG4 'belongs to prior period.'
#DEFINE LANG_CHKPRD_MSG5 'belongs to a future period.'
#DEFINE LANG_CHKPRD_MSG6 'belongs to a history fiscal year.'
#DEFINE LANG_CHKPRD_MSG7 'falls before the begining balance date.'
#DEFINE LANG_CHKPRD_MSG8 'No posting allowed before the begining balance date.'
#DEFINE LANG_CHKPRD_MSG9 'not in the current period.'
#DEFINE LANG_FERRINF_MSG1 'Invoice date'
#DEFINE LANG_FERRINF_MSG2 'Not allowed to create invoices for this date.'
#DEFINE LANG_FERRINF_MSG3 'System date'
#DEFINE LANG_FERRINF_MSG4 'Not allowed to void invoices for this date.'
#DEFINE LANG_FERRINF_MSG5 'Please check the system date.'
#DEFINE LANG_FERRINF_MSG6 'Not allowed to void invoices from prior periods.'
#DEFINE LANG_FERRINF_MSG7 'Transaction date'
#DEFINE LANG_FERRINF_MSG8 'Not allowed to enter inventory adjustment for this date.'
#DEFINE LANG_FERRINF_MSG9 'Not allowed to enter physical inventory for this date.'
#DEFINE LANG_FERRINF_MSG10 'Return date'
#DEFINE LANG_FERRINF_MSG11 'Not allowed to void credit memo from prior periods.'
#DEFINE LANG_FERRINF_MSG12 'Not allowed to zero out stock for this date.'
#DEFINE LANG_FERRINF_MSG13 'Not allowed to enter P/O receivings for this date.'
#DEFINE LANG_FERRINF_MSG14 'Not allowed to enter C/T receivings for this date.'
#DEFINE LANG_FERRINF_MSG15 'Not allowed to receive returns for this date.'
#DEFINE LANG_FERRINF_MSG16 'Not allowed to void credit memo for this date.'
#DEFINE LANG_FERRINF_MSG17 'Batch date'
#DEFINE LANG_FERRINF_MSG18 'Not allowed to enter payments for this batch date.'
#DEFINE LANG_FERRINF_MSG19 'Not allowed to enter adjustments for this batch date.'
#DEFINE LANG_FERRINF_MSG20 'Key off date'
#DEFINE LANG_FERRINF_MSG21 'Not allowed to make key off for this date.'
#DEFINE LANG_FERRINF_MSG22 'Material operation receiving date'
#DEFINE LANG_FERRINF_MSG23 'Not allowed to receive from material operation for this date.'
#DEFINE LANG_FERRINF_MSG24 'Style operation receiving date'
#DEFINE LANG_FERRINF_MSG25 'Not allowed to receive from style operation for this date.'
#DEFINE LANG_FERRINF_MSG26 'M.F.G. order receiving date' 
#DEFINE LANG_FERRINF_MSG27 'Not allowed to receive M.F.G. order for this date.'
#DEFINE LANG_VLADFLD_ALL "All"
*N000682,1 MMT 11/20/2012 Globalization project[End]
*N000682,1 MMT 03/14/2013 Fix issues of Globalization Testing Phase#2[Start]
#DEFINE LANG_GLDIST_INVOICE 'INVOICE             '
#DEFINE LANG_GLDIST_VOIDINVOICE 'VOID INVOICE        '
#DEFINE LANG_GLDIST_CASHR 'CASH RECEIPT        '
#DEFINE LANG_GLDIST_CREDITADJ 'CREDIT ADJUSTMENT   '
#DEFINE LANG_GLDIST_DEBITADJ 'DEBIT ADJUSTMENT    '
#DEFINE LANG_GLDIST_RM 'RETURN MERCHANDISE  '
#DEFINE LANG_GLDIST_VOIDRM 'VOID RETURN         '
#DEFINE LANG_GLDIST_INVPHY 'INVENTORY PHYSICAL  '
#DEFINE LANG_GLDIST_INVADJ 'INVENTORY ADJUSTMENT'
#DEFINE LANG_GLDIST_MATINVPHY 'MATERIAL INV. PHYSI.'
#DEFINE LANG_GLDIST_MATINVDJ 'MATERIAL INV. ADJUS.'
#DEFINE LANG_GLDIST_POREC 'P/O RECEIVING       '
#DEFINE LANG_GLDIST_MAPOREC 'MATERIAL P/O RECEIV.'
#DEFINE LANG_GLDIST_CTREC 'C/T RECEIVING       '
#DEFINE LANG_GLDIST_ZEROOUT 'ZERO OUT STOCK      '
#DEFINE LANG_GLDIST_NONMATLIB 'NON MAT. LIABILITY  '
#DEFINE LANG_GLDIST_POJOBCLOSE 'P/O JOB COST CLOSING'
#DEFINE LANG_GLDIST_MATOPREC 'MATERIAL OP. RECEIVE'
#DEFINE LANG_GLDIST_STYOPREC 'STYLE OP. RECEIVE   '
#DEFINE LANG_GLDIST_RECMFGORDER 'RECEIVE M.F.G. ORDER'
#DEFINE LANG_GLDIST_EXRATEDIFF 'EX. RATE DIFFERENCES'
#DEFINE LANG_GLDIST_KEYOFF 'KEY OFF'
#DEFINE LANG_GLDIST_MAJOBCLOSE 'MATERIAL JOB ClOSING'
#DEFINE LANG_GLDIST_CTJOBCLOSE 'C/T JOB COST CLOSING'
#DEFINE LANG_GLDIST_INVLOCK 'INVENTORY LOCKING'
#DEFINE LANG_OTSWAITWIND  'Collecting Open to Sell information...' 
#DEFINE LANG_CLEARERRORHANDLER "Clearing Error Handler" 
*N000682,1 MMT 03/14/2013 Fix issues of Globalization Testing Phase#2[End]