#IFDEF LANG_HdFuture
  #UNDEF LANG_HdFuture
#ENDIF
#DEFINE LANG_HdFuture 'FUTURE'

#IFDEF LANG_HdTotAvl
  #UNDEF LANG_HdTotAvl
#ENDIF
#DEFINE LANG_HdTotAvl 'TOTAL AVAIL'

#IFDEF LANG_HdTotSld
  #UNDEF LANG_HdTotSld
#ENDIF
#DEFINE LANG_HdTotSld 'TOT. SLD YTD'

#IFDEF LANG_BrowTitl
  #UNDEF LANG_BrowTitl
#ENDIF
#DEFINE LANG_BrowTitl 'Style Open To Sell for multiple periods'