#DEFINE LANG_ARCSLST_NOREC    "No Records Selected"
#DEFINE LANG_ARCSLST_SELCUST   "Selecting Customer...Please Wait"
#DEFINE LANG_ARCSLST_SORTCUST   "Sorting Customer...Please Wait"
#DEFINE LANG_ARCSLST_STATECODES 'State Codes'
#DEFINE LANG_ARCSLST_SSTATECODE 'State Code'
#DEFINE LANG_ARCSLST_DESC 'Description'
#DEFINE LANG_ARCSLST_CUSTACC 'Customer Account'
#DEFINE LANG_ARCSLST_CUSTNAME 'Customer Name'
#DEFINE LANG_ARCSLST_REGION 'Region'
#DEFINE LANG_ARCSLST_SELECTSTATUS 'Select Customer Status'
#DEFINE LANG_ARCSLST_ACTIVE 'Active'
#DEFINE LANG_ARCSLST_HOLD 'Hold'
#DEFINE LANG_ARCSLST_POTENTAIL 'Potential'
#DEFINE LANG_ARCSLST_CANCELLED 'Canceled'
