#DEFINE LANG_Arpinv_Inv  	 	"Invoice"
#DEFINE LANG_Arpinv_Yes 	 	"Yes"
#DEFINE LANG_Arpinv_No		 	"No"
#DEFINE LANG_Arpinv_Prntd 		"Printed"
#DEFINE LANG_Arpinv_Date 		"Date"
#DEFINE LANG_Arpinv_Acc 		"Account"
#DEFINE LANG_Arpinv_Order 		"Order"
#DEFINE LANG_Arpinv_Refrnc 		"Reference"
#DEFINE LANG_Arpinv_Bilto 		"Bill to"
#DEFINE LANG_Arpinv_SlsRp 		"Sales Rep."
#DEFINE LANG_Arpinv_Piecs 		"Pieces"
#DEFINE LANG_Arpinv_Mrchnds 	"Merchandise"
#DEFINE LANG_Arpinv_RecInv  	"Receivable invoices"
#DEFINE LANG_Arpinv_InvNotes 	"Invoice Notes"
#DEFINE LANG_Arpinv_LinNotes 	"Line Notes"
#DEFINE LANG_Arpinv_AtStore 	"At Store Level "
#DEFINE LANG_Arpinv_Form 		"Form '"