#DEFINE LANG_MAT_ICOSTLLBL1  'Price'
#DEFINE LANG_MAT_ICOSTLLBL2  'Freight'
#DEFINE LANG_MAT_ICOSTLLBL3  'Tax'
#DEFINE LANG_MAT_ICOSTLLBL4  'Quota'
#DEFINE LANG_MAT_ICOSTLLBL5  ''
#DEFINE LANG_MAT_ICOSTLLBL6  ''
#DEFINE LANG_MAT_ICOSTLLBL7  ''
#DEFINE LANG_TARGLOC "Target Location"
#DEFINE LANG_SOURCELOC "Source Location"
#DEFINE LANG_LOCATION "Location"
#DEFINE LANG_VENDOR "Vendor"
#DEFINE LANG_COMPDATE "Complete Date"
#DEFINE LANG_RECDATE "Receive Date"
#DEFINE LANG_STYPONO "Style PO #"
#DEFINE LANG_SHIPMENT "Shipment"
#DEFINE LANG_DYEORDERNO "Dye Order #"
#DEFINE LANG_MFGORDERNO "MFG Order #"
#DEFINE LANG_TICKETNO "Ticket #"
#DEFINE LANG_DATE 'Date'
#DEFINE LANG_MAPONO "Material PO #"
#DEFINE LANG_COLLECTDATA "Collecting data for Report... " 
#DEFINE LANG_ONLYTHESE 'Only these' 
#DEFINE LANG_COLORSS 's'
#DEFINE LANG_Title_PO 'Style Purchase Order Receipt Log'
#DEFINE LANG_Title_OTHER 'Dye Order Receipt Log'
