#DEFINE LANG_ITMCSREP_Active     "Active"
#DEFINE LANG_ITMCSREP_Hold       "Hold"
#DEFINE LANG_ITMCSREP_Cncld      "Cancelled"
#DEFINE LANG_ITMCSREP_InWork     "In Work"
#DEFINE LANG_ITMCSREP_FabCstSht  "Fabric Cost Sheet"
#DEFINE LANG_ITMCSREP_StyCstSht  "Style Cost Sheet"
#DEFINE LANG_ITMCSREP_FabOnly    "Fabric Only"
#DEFINE LANG_ITMCSREP_StyOnly    "Style Only"
#DEFINE LANG_ITMCSREP_FabClr     "Fabric/Color"
#DEFINE LANG_ITMCSREP_StyClr     "Style/Color"
#DEFINE LANG_ITMCSREP_NoRec      "There are no records to display...! ")  
#DEFINE LANG_ITMCSREP_OnlyThs    "Only These "
#DEFINE LANG_ITMCSREP_Only       " only"
#DEFINE LANG_ITMCSREP_CstStat    "Cost Sheet Status"
#DEFINE LANG_ITMCSREP_WaitFab    "Compiling The Cost Sheet Information For Fabric " 
#DEFINE LANG_ITMCSREP_WaitSty    "Compiling The Cost Sheet Information For Style " 

