*N000682,1 MMT 02/06/2013 Globalization changes[Start]
#DEFINE LANG_PONOTEPAD 'Purchase Order Notepad'
#DEFINE LANG_CONTNOTEPAD 'Contract Notepad'
#DEFINE LANG_RETNOTEPAD 'Return Purchase Order Notepad' 
#DEFINE LANG_INTNOTEPAD 'Inter-Location P/O Notepad'
#DEFINE LANG_DYENOTEPAD 'Dye Order Notepad'
#DEFINE LANG_SELECTED 'SELECTED ' 
#DEFINE LANG_RECFORREP ' RECORDS FOR REPORT' 
*N000682,1 MMT 02/06/2013 Globalization changes[END]
#DEFINE LANG_POSTYP_STYLE			"STYLE"
#DEFINE LANG_POSTYP_BrowseTitle	"Rejected Interlocation PO's"
#DEFINE LANG_POSTYP_PURCHASEORDER	"PO#"
#DEFINE LANG_POSTYP_CONTRACT		"Contract#"
#DEFINE LANG_POSTYP_RETURNPO    	"Ret.PO#"
#DEFINE LANG_POSTYP_INTERLOC		"Inter-Loc. PO"
#DEFINE LANG_POSTYP_STATUS 		"Status"
#DEFINE LANG_POSTYP_VENDOR 		"Vendor"
#DEFINE LANG_POSTYP_NAME	 		"Name"
#DEFINE LANG_POSTYP_ENTERED 		"Entered"
#DEFINE LANG_POSTYP_OPEN           "Open"
#DEFINE LANG_POSTYP_TOTAL          "PoTotal"
#DEFINE LANG_POSTYP_PURCHORDER     "Purchase Order"
#DEFINE LANG_POSTYP_CONTORDER      "Contract"
#DEFINE LANG_POSTYP_RETORDER       "Return Purchase Order"
#DEFINE LANG_POSTYP_INTERORDER     "Inter-Location P/O"
#DEFINE LANG_POSTYP_TEXTHEAD1      '        DATE         QTY   DATE   DIRECT'
#DEFINE LANG_POSTYP_TEXTHEAD2      'VENDOR  ORDERD PO #  ORDRD RECVD. SHIPD.'
#DEFINE LANG_POSTYP_TEXTHEAD       '[------------ PULLED -------------] TOTAL'
#DEFINE LANG_POSTYP_PONO				"PO #"