* N000682 ,1 Thabet Handle globalization issues [Start]
#DEFINE LANG_Selected 'Selected'
#DEFINE LANG_Records_in 'Records in'
#DEFINE LANG_Seconds 'Seconds...'
#DEFINE LANG_Cutting_Ticket 'Cutting Ticket #: '
#DEFINE LANG_Contract 'Contract #: '
#DEFINE LANG_Purchase_Order 'Purchase Order #: '
#DEFINE LANG_STAUS_OPEN 'Open'
#DEFINE LANG_STAUS_HOLD 'Hold'
#DEFINE LANG_STAUS_COMPLETE 'Complete'
#DEFINE LANG_STAUS_BID 'Bid'
#DEFINE LANG_STAUS_CANCEL 'Cancel'
#DEFINE LANG_STAUS_CLOSED  'Closed'
#DEFINE LANG_STAUS_ACTUAL 'Actual'
#DEFINE LANG_STAUS_ALL 'All'
* N000682 ,1 Thabet Handle globalization issues [END]