_Screen.Visible = .F. 
SET CPDIALOG OFF 
SET RESOURCE OFF 
SET SAFETY OFF 
lcSqlDict = GETDIR('','Select Aria4 SqlDictionary Folder')
IF !DIRECTORY(lcSqlDict) OR !FILE(ADDBS(lcSqlDict)+'SYDREPRT.DBF')
  MESSAGEBOX('Invlaid Directory')
  RETURN .F.
ENDIF
USE ADDBS(lcSqlDict)+'SYDREPRT.DBF' EXCLUSIVE 

IF TYPE('caria5id') = 'C'
  use IN SYDREPRT
  RETURN .F.
ENDIF

ALTER TABLE SYDREPRT ADD COLUMN caria5id C(32) 
SET ORDER TO 1 
IF SEEK('ARPINV')
  REPLACE caria5id WITH '1207'
ENDIF  
IF SEEK('SOORCN')
  REPLACE caria5id WITH '1209'
ENDIF  
IF SEEK('SOORDHD')
  REPLACE caria5id WITH '1211'
ENDIF
  
IF SEEK('ICSCLRT ')
  REPLACE caria5id WITH '1174'
ENDIF
  
IF SEEK('ALSTYF2 ')
  REPLACE caria5id WITH '1188'
ENDIF
  
IF SEEK('SMCCODE ')
  REPLACE caria5id WITH '1170'
ENDIF
  
IF SEEK('ARAGEAR ')
  REPLACE caria5id WITH '1176'
ENDIF
  
IF SEEK('ALAUTPLS')
  REPLACE caria5id WITH '1180'
ENDIF  
IF SEEK('SOUPDNF ')
  REPLACE caria5id WITH '1201'
ENDIF
  
IF SEEK('SMREBAL ')
  REPLACE caria5id WITH '1184'
ENDIF
  
IF SEEK('ALAUTNAL')
  REPLACE caria5id WITH '1182'
ENDIF  

IF SEEK('PMPRJSCH')
  REPLACE caria5id WITH '1190'
ENDIF
USE IN SYDREPRT
MESSAGEBOX('File is Updated')