#DEFINE LANG_MFPATH_TMPLATE        "Templates"
#DEFINE LANG_MFPATH_TMPLATEID      'Template ID'
#DEFINE LANG_MFPATH_TMPLATENAME    'Template Name'
#DEFINE LANG_MFPATH_CATEGORY	   'Categories'
#DEFINE LANG_MFPATH_CATEGORYID	   'Category ID'
#DEFINE LANG_MFPATH_DESC   		   'Description'
*MEDIA
*#DEFINE LANG_MFPATH_TASKID		   'Task ID'
*#DEFINE LANG_MFPATH_TASKNAME	   'Task Name'
#DEFINE LANG_MFPATH_TASKID		   'Activity ID'
#DEFINE LANG_MFPATH_TASKNAME	   'Activity Name'

*MEDIA
#DEFINE LANG_MFPATH_RESPONSIBLE    'Responsible'
#DEFINE LANG_MFPATH_ONECATEGORY	   'Category'
#DEFINE LANG_MFPATH_DURATION	   'Duration'    
#DEFINE LANG_MFPATH_CALENDAR   	   'Calendar'
#DEFINE LANG_MFPATH_SHOWTOCUST	   'Show to Customer'
#DEFINE LANG_MFPATH_UPDMETHOD	   'Update Method'
*MEDIA
*#DEFINE LANG_MFPATH_TASKS 		   'Tasks'
#DEFINE LANG_MFPATH_TASKS 		   'Activities'
*MEDIA
#DEFINE LANG_MFPATH_CALENDARS      'Calendars'
#DEFINE LANG_MFPATH_CALENDARID 	   'Calendar ID'
#DEFINE LANG_MFPATH_USERID		   'User ID'
#DEFINE LANG_MFPATH_USERNAME	   'User Name'
#DEFINE LANG_MFPATH_USERS			'Users'
#DEFINE LANG_MFPATH_GROUPID			'Group ID'
#DEFINE LANG_MFPATH_GROUPNAME 		'Group Name'
#DEFINE LANG_MFPATH_GROUPS			'Groups'
#DEFINE LANG_MFPATH_SLCTPRED		'Select Predecessors for '
*MEDIA
*#DEFINE LANG_MFPATH_SLCTTASK		'Select from available tasks for [ '
#DEFINE LANG_MFPATH_SLCTTASK		'Select from available activities for [ '
*MEDIA
#DEFINE LANG_MFPATH_SLCTTASKCTG		' ] Category.'

*:E302853,1 MMT 02/08/2011 add message to update project when template notification is changed[T20101022.0001][Start]
#DEFINE LANG_MFPATH_UPDPROJS    'Updating Projects...'
#DEFINE LANG_MFPATH_UPDPROJNO   'Project: '
*:E302853,1 MMT 02/08/2011 add message to update project when template notification is changed[T20101022.0001][End]
*N000682,1 MMT 12/03/2012 Globalization changes[Start]
#DEFINE LANG_MFPATH_GROUPOFUSERS "Group of users"
#DEFINE LANG_MFPATH_ONEUSER "User"
#DEFINE LANG_MFPATH_MANUAL "Manual"
#DEFINE LANG_MFPATH_EXISTINGUSER "User Exist"
*N000682,1 MMT 12/03/2012 Globalization changes[END]