#DEFINE LANG_ARIA_ConfigNum  	   "Configuration #"
#DEFINE LANG_ARIA_DyelotNum  	   "Dyelot #"
#DEFINE LANG_ARIA_Config     	   " Configurations"
#DEFINE LANG_ARIA_Dyelot     	   " Dyelots"
#DEFINE LANG_ARIA_Avl1     	 	   "Avl1"
#DEFINE LANG_ARIA_Avl2     	   	   "Avl2"
#DEFINE LANG_ARIA_Avl3     	       "Avl3"
#DEFINE LANG_ARIA_Avl4     	       "Avl4"
#DEFINE LANG_ARIA_Avl5     	       "Avl5"
#DEFINE LANG_ARIA_Avl6     	       "Avl6"
#DEFINE LANG_ARIA_Avl7     	       "Avl7"
#DEFINE LANG_ARIA_Avl8     	       "Avl8"
#DEFINE LANG_ARIA_TotAvl		   "TotAvl"
#DEFINE LANG_ARIA_Alo1     	 	   "Alo1"
#DEFINE LANG_ARIA_Alo2     	   	   "Alo2"
#DEFINE LANG_ARIA_Alo3     	       "Alo3"
#DEFINE LANG_ARIA_Alo4     	       "Alo4"
#DEFINE LANG_ARIA_Alo5     	       "Alo5"
#DEFINE LANG_ARIA_Alo6     	       "Alo6"
#DEFINE LANG_ARIA_Alo7     	       "Alo7"
#DEFINE LANG_ARIA_Alo8     	       "Alo8"
#DEFINE LANG_ARIA_TotAlo		   "TotAlo"
#DEFINE LANG_ARIA_Stk1     	 	   "Stk1"
#DEFINE LANG_ARIA_Stk2     	   	   "Stk2"
#DEFINE LANG_ARIA_Stk3     	       "Stk3"
#DEFINE LANG_ARIA_Stk4     	       "Stk4"
#DEFINE LANG_ARIA_Stk5     	       "Stk5"
#DEFINE LANG_ARIA_Stk6     	       "Stk6"
#DEFINE LANG_ARIA_Stk7     	       "Stk7"
#DEFINE LANG_ARIA_Stk8     	       "Stk8"
#DEFINE LANG_ARIA_TotStk		   "TotStk"
#DEFINE LANG_ARIA_MsgVar1		   " on the file"
#DEFINE LANG_ARIA_MsgVar2		   " in location "
#DEFINE LANG_ARIA_MsgSgx1          "Item\Warehouse :"
#DEFINE LANG_ARIA_MsgSgx2          "Item :"
#DEFINE LANG_ARIA_StyConfg         " Item Configuration "
#DEFINE LANG_ARIA_StyDyelot        " Item Dyelots "

#DEFINE LANG_ARIA_CITMMAJOR        "Item Code Major"
#DEFINE LANG_ARIA_CCSTSHT_ID       "Cost Sheet Code"
#DEFINE LANG_ARIA_CCSTSHTDSC       "Cost Sheet Description"
#DEFINE LANG_ARIA_LDEFCSTSHT       "Default Cost Sheet"
#DEFINE LANG_ARIA_CSTATUS          "Status"
#DEFINE LANG_ARIA_LBASONSIZ        "Base cost sheet on size"
#DEFINE LANG_ARIA_TOTCOST          "Total Cost"
#DEFINE LANG_ARIA_CCSTSHTTYP       "Procurement type"

#DEFINE LANG_ARIA_CONFIGMESG       "Configuration"
#DEFINE LANG_ARIA_DYELOTMESG       "Dyelot"
#DEFINE LANG_ARIA_Scale_Title      "Size Scales"

#DEFINE LANG_ARIA_UOM           "Units of Measurement"
#DEFINE LANG_ARIA_UOM_REL       "Relation Code"
#DEFINE LANG_ARIA_UOM_B         "Base UOM"
#DEFINE LANG_ARIA_UOM_V         "Converted UOM"
#DEFINE LANG_ARIA_UOM_CONF      "Conversion Factor"

#DEFINE LANG_ARIA_LOCATION      "Location"
#DEFINE LANG_ARIA_DESCRIPTION   "Description"
#DEFINE LANG_ARIA_LOCTTL        "Locations"

