#IFDEF LANG_NOLOC   
  #UNDEF LANG_NOLOC   
#ENDIF
#DEFINE LANG_NOLOC   "No locations found."

#IFDEF LANG_NOTASN  
  #UNDEF LANG_NOTASN  
#ENDIF
#DEFINE LANG_NOTASN  "is not asssigned to any location."

#IFDEF LANG_STYLE   
  #UNDEF LANG_STYLE   
#ENDIF
#DEFINE LANG_STYLE   "Style "

#IFDEF LANG_ITMCLR  
  #UNDEF LANG_ITMCLR  
#ENDIF
#DEFINE LANG_ITMCLR  "Item/Color "
