#DEFINE LANG_ARVINV_UNSELECT 'UnSe\<lect'
#DEFINE LANG_ARVINV_SELECT   'Se\<lect'                                                                                                                                                    
#DEFINE LANG_ARVINV_VOIDMULTIPLEINVOICE 'Voiding Multiple Invoices'
#DEFINE LANG_ARVINV_INVOICE  "Invoice"
#DEFINE LANG_ARVINV_DATE "Date"
#DEFINE LANG_ARVINV_ACCOUNT "Account"
#DEFINE LANG_ARVINV_STORE "Store"
#DEFINE LANG_ARVINV_BILLTO "Bill To"
#DEFINE LANG_ARVINV_REFERENCE "Reference"
#DEFINE LANG_ARVINV_PIECES "Pieces"
#DEFINE LANG_ARVINV_MERCHANDISE "Merchandise"
#DEFINE LANG_ARVINV_COLLECTINVOICE 'Collecting Invoice# '
#DEFINE LANG_ARVINV_VOIDINVOICE 'Voiding Invoice # '
#DEFINE LANG_ARVINV_NOINVOICEVOIDED 'No Invoice Voided.'
#DEFINE LANG_ARVINV_INVOICENUMBER 'Invoice# ' 
#DEFINE LANG_ARVINV_HASBEENVOIDED ' has been Voided.'
#DEFINE LANG_ARVINV_INVOICEFROM 'Invoices from ' 
#DEFINE LANG_ARVINV_TO ' to '
#DEFINE LANG_ARVINV_HAVEBEENVOIDED ' have been Voided.'
#DEFINE LANG_ARVINV_NORECORDSELECTED 'No Records Selected.' 
#DEFINE LANG_ARVINV_OPTIONGRID "Option Grid"
#DEFINE LANG_ARVINV_VOIDINVOICES "Void Invoices"