#DEFINE LANG_SMCRATE_ShipZone           'ShipTo Zip Code : '
#DEFINE LANG_SMCRATE_GetExcelPath       'Excel sheet Path : '
#DEFINE LANG_SMCRATE_GetExcelPathTitle  'Select'

*: N000682,1 HES Globalization Changes [Globalization Project]
#DEFINE LANG_Weight   'Weight : '
#DEFINE LANG_Zone   ' Zone : '
#DEFINE LANG_Rate   ' Rate : '
#DEFINE LANG_Converte   'Converte'
#DEFINE LANG_Path_name   'Path name'
#DEFINE LANG_ZONE   'ZONE'
*: N000682,1 HES Globalization Changes [Globalization Project]
