#DEFINE LANG_Type1 'Complete a Call'
#DEFINE LANG_Type2 'Complete an Appointment'
#DEFINE LANG_Type3 'Complete a Todo'
#DEFINE LANG_Type4 'Complete an Email'
*B611122,1 MMT 03/13/2016 User able to complete task without adding complete date[T20160226.0006][Start]
#DEFINE LANG_EMPTY_COMPLETE_DATE "Complete date is empty. Please enter the complete date"  
*B611122,1 MMT 03/13/2016 User able to complete task without adding complete date[T20160226.0006][End]