#DEFINE LANG_COLLDATA 'Collecting data...' 
#DEFINE LANG_DESC "Description"
#DEFINE LANG_CODE "Code"
#DEFINE LANG_TTLCODE 'Codes File'
#DEFINE LANG_USERNAME "User name"
#DEFINE LANG_USERID "User ID"
#DEFINE LANG_USERS 'Users'
