#DEFINE LANG_NORMAL  'Normal'
#DEFINE LANG_STATIS 'Statistical'
#DEFINE LANG_BEGBAL 'Beginning Balances'
#DEFINE LANG_SUBLED 'Subledger'
#DEFINE LANG_SUMMER 'Summerized'
#DEFINE LANG_HOLD 'Hold'
#DEFINE LANG_VOID 'Void'
#DEFINE LANG_APPOVED 'Approved'
#DEFINE LANG_UNPOSTED 'Unposted'
#DEFINE LANG_OUTOFBAL 'Out of balance'
#DEFINE LANG_EMPTY 'EMPTY'
#DEFINE LANG_YES 'Yes'
#DEFINE LANG_NO 'No'
#DEFINE LANG_ENDDATE "End date"
#DEFINE LANG_BEGINDATE "Begin date"
#DEFINE LANG_YEAR "Year"
#DEFINE LANG_TRANCODE 'Transaction Codes '
#DEFINE LANG_BATDESC "Batch description"
#DEFINE LANG_BATCHES 'Batches' 
#DEFINE LANG_BATNO "Batch number"