#DEFINE LANG_CUSTOMER "Customer"
#DEFINE LANG_SALES 'Sales'				
#DEFINE LANG_ALL "ALL"
#DEFINE LANG_WIP "Work in process"
#DEFINE LANG_MATERIAL "Material"            
#DEFINE LANG_STYLE "Style" 
#DEFINE LANG_REPORT_NAME 'GENERAL LEDGER LINK FILE' 