#DEFINE LANG_ModiPacks_Caption        "Orderd Packs" 
#DEFINE LANG_ModiPacks_MoverCaption   "Select Stores to be update"
#DEFINE LANG_ModiPacks_UpdateMsg      "None of Pack's numbers or price has changed. Can't update."
#DEFINE LANG_ModiPacks_NegativeQty    "Quantity"
#DEFINE LANG_ModiPacks_negativePric   "Price"
#DEFINE LANG_ModiPacks_Message1       "style with non existing scale"
#DEFINE LANG_ModiPacks_MessageIgnore  "Pack will be ignored."
#DEFINE LANG_ModiPacks_Message2       "canceled style"
#DEFINE LANG_ModiPacks_CannotModfiy    "Order line(s) in this pack already picked; Cannot decrease the Qty."