#DEFINE LANG_AUTOALLOC_COLROTITL1 			  'Only These '
#DEFINE LANG_AUTOALLOC_COLROTITL2 			  's.'
#DEFINE LANG_AutoAlloc_Scope				  'Scope'
#DEFINE LANG_AutoAlloc_Allocate				  'Allocate selected records'
#DEFINE LANG_AutoAlloc_release				  'Release selected records'
#DEFINE LANG_AutoAlloc_GenPick				  'Generate picking tickets'
#DEFINE LANG_AutoAlloc_SepertOpt			  '\-'
#DEFINE LANG_AutoAlloc_ScopeOpt				  '\<Scope'
#DEFINE LANG_AutoAlloc_AllocateOpt			  '\<Allocate selected records'
#DEFINE LANG_AutoAlloc_releaseOpt			  '\<Release selected records'
#DEFINE LANG_AutoAlloc_GenerateOp			  '\<Generate picking tickets'
#DEFINE LANG_AutoAlloc_Option	        	  'O\<ptions'
#DEFINE LANG_AutoAlloc_LabelOrder 			  'Order'
#DEFINE LANG_AutoAlloc_LabelAccount			  'Account'
#DEFINE LANG_AutoAlloc_LabelStore			  'Store'
#DEFINE LANG_AutoAlloc_LabelConfg			  'Configuration'
#DEFINE LANG_AutoAlloc_LabelDyelot			  'Dyelot'
#DEFINE LANG_AutoAlloc_LabelGroup			  'G'
#DEFINE LANG_AutoAlloc_LabelAvialable		  'Avail.'
#DEFINE LANG_AutoAlloc_LabelOpen			  'Open'
#DEFINE	LANG_AutoAlloc_LabelOpnAmnt		 	  'Opn Amnt.'
#DEFINE LANG_AutoAlloc_LabelPiktkt			  'Pick Tkt'
#DEFINE LANG_AutoAlloc_LabelPicked			  'Picked'
#DEFINE LANG_AutoAlloc_LabelPikAmnt			  'Pik Amnt.'
#DEFINE LANG_AutoAlloc_Season				  ' season'
#DEFINE LANG_AutoAlloc_Division	    		  ' division'
#DEFINE LANG_AutoAlloc_Group				  ' group'
#DEFINE LANG_AutoAlloc_FabricCode			  ' fabric code'
#DEFINE LANG_AutoAlloc_Pattern 				  ' pattern'
#DEFINE LANG_AutoAlloc_Configuration		  'Configuration:'
#DEFINE LANG_AutoAlloc_Dyelot		    	  'Dyelot       :'
#DEFINE LANG_AutoAlloc_CT   		   	      'C/T            :'
#DEFINE LANG_AutoAlloc_PO		    	      'P/O            :'
#DEFINE LANG_AutoAlloc_MsgAskAssign           '. Do you wish to assign it'
#DEFINE LANG_AutoAlloc_MsgSeason              '|Season'
#DEFINE LANG_AutoAlloc_MsgDivision            '|Division'
#DEFINE LANG_AutoAlloc_MsgAskForce1           'Do you want to force allocation?'
#DEFINE LANG_AutoAlloc_MsgAskForce2           'The allocated quantity|the available quantity'
#DEFINE LANG_AutoAlloc_LableProgress          'Preparing data files'
#DEFINE LANG_AutoAlloc_LableAssign            'Assigning piktkt number for...Order/Style : '
#DEFINE LANG_AutoAlloc_LableReleas            'Releasing...Order/Style : '
#DEFINE LANG_AutoAlloc_WaitMsgExcl            'Excluding'
#DEFINE LANG_AutoAlloc_WaitMsgSelc            'Selecting'
#DEFINE LANG_AutoAlloc_WaitMsgPO              ' purchase order '
#DEFINE LANG_AutoAlloc_WaitMsgCT              ' cutting ticket '
#DEFINE LANG_AutoAlloc_ProgrsAllo             'Allocating...'
#DEFINE LANG_AutoAlloc_ProgrsOrdNum           'Order number: '
#DEFINE LANG_AUTOALLOC_OPTNCONFG              'Exclude styles with Confg'
#DEFINE LANG_AUTOALLOC_OPTNDYELOT             'Exclude styles with dyelot'
#DEFINE LANG_AUTOALLOC_SQLMSG1                ' While opening '
#DEFINE LANG_AUTOALLOC_SQLMSG2                ' file.'
#DEFINE LANG_AUTOALLOC_MsgPickSep		      'Pick separates min%|0|100'
#DEFINE LANG_AUTOALLOC_MsgPickCoord		      'Pick coordinate groups min%|0|100'
#DEFINE LANG_AUTOALLOC_MsgCutOffUnt		      'Cut-off units'
#DEFINE LANG_AUTOALLOC_ButtSelect		      '\<Select'
#DEFINE LANG_AUTOALLOC_ButtUnSelect		      'Un\<select'
#DEFINE LANG_AutoAlloc_LabelReasone           'Reject Reason'
#DEFINE LANG_AutoAlloc_LabelReasMASetup       'This is a dyelot style but Use dyelot setup in MA is NO'
#DEFINE LANG_AutoAlloc_LabelReasAvlQty        'There is no available Qty'
#DEFINE LANG_AutoAlloc_LabelResaAvlQtCov1     'There is no available to cover the pick separates Min%'
#DEFINE LANG_AutoAlloc_LabelResaAvlQtCov2     'There is no available to cover the pick coordinate Min%'
#DEFINE LANG_AutoAlloc_LabelReasDyeNtAssgn1   'Dyelot '
#DEFINE LANG_AutoAlloc_LabelReasCnfgNtAssgn1  'Configuration '
#DEFINE LANG_AutoAlloc_LabelReasDyeNtAssgn2   ' is not assigned to location '
#DEFINE LANG_AutoAlloc_LabelResaStyleNtAssgn  'This style is not assigned to location '
#DEFINE LANG_AutoAlloc_LabelReasDyelotAssign  'No Dyelots assigned to this style'
#DEFINE LANG_AutoAlloc_LabelReasConfigAssign  'No configurations assigned to this style'
#DEFINE LANG_AutoAlloc_LabelReasSameFabDye    'Styles should be allocated within the same fabric dyelot. But the fabric dyelot is different.'
#DEFINE LANG_AutoAlloc_LabelReasNOFabDye      'There are no dyelots for Fabric/Color : '
#DEFINE LANG_AutoAlloc_ExcludingOrder         'Excluding order '
#DEFINE LANG_AutoAlloc_SelectingOrder         'Selecting order '
#DEFINE LANG_AutoAlloc_Excluding              'Excluding '
#DEFINE LANG_AutoAlloc_Selecting              'Selecting '
#DEFINE LANG_AutoAlloc_CannotChange           '. Cannot change.'
