#DEFINE LANG_Debit "Debit"
#DEFINE LANG_Credit "Credit"
#DEFINE LANG_DbAdj "Debit Adjustment"
#DEFINE LANG_CrAdj "Credit Adjustment"
#DEFINE LANG_AutoCarry "\<Auto Carry Account"
#DEFINE LANG_Options "O\<ptions"
#DEFINE LANG_HdFactor "Factor"
#DEFINE LANG_HdName "Name"
#DEFINE LANG_HdContact "Contact"
#DEFINE LANG_HdPhone "Phone"
#DEFINE LANG_Factors "Factors"