#DEFINE LANG_GLBUDGT_BudegtCode        'Budget Code '
#DEFINE LANG_GLBUDGT_Acct              'ACT'
#DEFINE LANG_GLBUDGT_AcctDesc          'Description'
*N000682,1 MMT 11/22/2012 Globalization changes[Start]
#DEFINE LANG_GLBUDGT_REF 'Ref. '
#DEFINE LANG_GLBUDGT_PD 'PD'
#DEFINE LANG_GLBUDGT_T 'T'
#DEFINE LANG_GLBUDGT_BUDGET 'Budget '
#DEFINE LANG_GLBUDGT_ACTUAL 'Actual '
#DEFINE LANG_GLBUDGT_BUDMINUSACT 'Budget - Actual'
#DEFINE LANG_GLBUDGT_THEBUDCODE "the budget code"
#DEFINE LANG_GLBUDGT_THEBUDYEAR "the budget year"
#DEFINE LANG_GLBUDGT_THEGROUPCODE "the group code"
#DEFINE LANG_GLBUDGT_GENEREATED "| is generated"
#DEFINE LANG_GLBUDGT_M_GENEREATE "|s are generated"
*N000682,1 MMT 11/22/2012 Globalization changes[END]