#DEFINE LANG_GLTRANS_TRANSACTION  'Transaction' 
#DEFINE LANG_GLTRANS_DESCRIPTION   'Description'          
#DEFINE LANG_GLTRANS_DEBIT 'Debit'         
#DEFINE LANG_GLTRANS_CREDIT 'Credit'                                                                                                                                                             
*N000682,1 12/14/12 TMI Globlization changes[Start] 
#DEFINE LANG_GLTRANS_CAPTION  'Single Transaction' 
#DEFINE LANG_GLTRANS_DETAIL  'Transaction Detail' 
#DEFINE LANG_Transaction_Header 'Transaction Header'
#DEFINE LANG_NOT_FOUND_NUMBER "GL Batch Number\Transaction Number : "
#DEFINE LANG_Automated_code_file 'Automated code file'
#DEFINE LANG_Transaction_Header 'Transaction Header'
*N000682,1 12/14/12 TMI Globlization changes[End  ] 