//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using System.Linq;

using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using Aria5SystemAdmin.Module;
using Aria5SystemAdmin.Module.BusinessObjects;
using DevExpress.Xpo.Metadata;

namespace Aria5.DevExpress.OneTouchAway.Module.BusinessObjects
{
    [DefaultClassOptions]
    [IsClient(true, true)]
    [RelatedEntity("Aria5-Windows8Xaml-ClientAccount")]
    public partial class ClientAccount : ClientBaseObject
    {
        public ClientAccount(Session session)
            : base(session)
        {

        }
        private System.String _AccountId;
        public System.String AccountId
        {
            get
            {
                return _AccountId;
            }
            set
            {
                SetPropertyValue("AccountId", ref _AccountId, value);
            }
        }

        private System.String _name;
        [SizeAttribute(100)]
        public System.String Name
        {
            get
            {
                return _name;
            }
            set
            {
                SetPropertyValue("Name", ref _name, value);
            }
        }

        private Contact _Contact;
     
        public Contact Contact
        {
            get
            {
                return _Contact;
            }
            set
            {
                SetPropertyValue("Contact", ref _Contact, value);
            }
        }

        private Guid    _ActiveProfile;

        public Guid ActiveProfile
        {
            get
            {
                return _ActiveProfile;
            }
            set
            {
                SetPropertyValue("ActiveProfile", ref _ActiveProfile, value);
            }
        }

   

        private System.Drawing.Image _Logo;
         [ValueConverter(typeof(ImageValueConverter))]
        public System.Drawing.Image Logo
        {
            get
            {
                return _Logo;
            }
            set
            {
                SetPropertyValue("Logo", ref _Logo, value);
            }
        }

       private System.Boolean  _IsActive;

        public System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                SetPropertyValue("IsActive", ref _IsActive, value);
            }
        }

        private ClientLanguage _DefaultLanguage;

        public ClientLanguage DefaultLanguage
        {
            get
            {
                return _DefaultLanguage;
            }
            set
            {
                SetPropertyValue("DefaultLanguage", ref _DefaultLanguage, value);
            }
        }

        private System.String _DBVersion;
        [SizeAttribute(35)]
        public System.String DBVersion
        {
            get
            {
                return _DBVersion;
            }
            set
            {
                SetPropertyValue("DBVersion", ref _DBVersion, value);
            }
        }
    }
}
