//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using Aria5SystemAdmin.Module;
namespace Aria5.DevExpress.OneTouchAway.Module.BusinessObjects
{
  [DefaultClassOptions]
  [IsClient(true, true)]
  [RelatedEntity("Aria5-Windows8Xaml-ClientAttachments")]
  public partial class ClientAttachments : ClientBaseObject
  {
    private System.Boolean _isCached;
    private System.DateTime _lastModified;
    private System.String _path;
    private System.String _machine;
    private System.Int32 _height;
    private System.Int32 _width;
    private System.String _theme;
    private System.Int32 _dPI;
    private System.String _view;
    private System.Drawing.Image _attachment;
    private System.String _name;
    private System.String _attachmentID;
    public ClientAttachments(Session session)
      : base(session)
    {
    }
    [SizeAttribute(30)]
    public System.String AttachmentID
    {
      get
      {
        return _attachmentID;
      }
      set
      {
        SetPropertyValue("AttachmentID", ref _attachmentID, value);
      }
    }
    [SizeAttribute(100)]
    public System.String Name
    {
      get
      {
        return _name;
      }
      set
      {
        SetPropertyValue("Name", ref _name, value);
      }
    }
    [ValueConverterAttribute(typeof(ImageValueConverter))]
    public System.Drawing.Image Attachment
    {
      get
      {
        return _attachment;
      }
      set
      {
        SetPropertyValue("Attachment", ref _attachment, value);
      }
    }
    [SizeAttribute(50)]
    public System.String View
    {
      get
      {
        return _view;
      }
      set
      {
        SetPropertyValue("View", ref _view, value);
      }
    }
    public System.Int32 DPI
    {
      get
      {
        return _dPI;
      }
      set
      {
        SetPropertyValue("DPI", ref _dPI, value);
      }
    }
    [SizeAttribute(50)]
    public System.String Theme
    {
      get
      {
        return _theme;
      }
      set
      {
        SetPropertyValue("Theme", ref _theme, value);
      }
    }
    public System.Int32 Width
    {
      get
      {
        return _width;
      }
      set
      {
        SetPropertyValue("Width", ref _width, value);
      }
    }
    public System.Int32 Height
    {
      get
      {
        return _height;
      }
      set
      {
        SetPropertyValue("Height", ref _height, value);
      }
    }
    [SizeAttribute(100)]
    public System.String Machine
    {
      get
      {
        return _machine;
      }
      set
      {
        SetPropertyValue("Machine", ref _machine, value);
      }
    }
    [SizeAttribute(250)]
    public System.String Path
    {
      get
      {
        return _path;
      }
      set
      {
        SetPropertyValue("Path", ref _path, value);
      }
    }
    public System.DateTime LastModified
    {
      get
      {
        return _lastModified;
      }
      set
      {
        SetPropertyValue("LastModified", ref _lastModified, value);
      }
    }
    public System.Boolean IsCached
    {
      get
      {
        return _isCached;
      }
      set
      {
        SetPropertyValue("IsCached", ref _isCached, value);
      }
    }
  }
}
