//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using Aria5SystemAdmin.Module;
namespace Aria5.DevExpress.OneTouchAway.Module.BusinessObjects
{
  [DefaultClassOptions]
  [IsClient(true, false)]
  [RelatedEntity("Aria5-Windows8Xaml-DataSortColumn")]


    public partial class DataSortColumn : ClientBaseObject
  {
    private System.String _direction;
    private System.String _name;
    private System.Int32 _order;
    private Aria5.DevExpress.OneTouchAway.Module.BusinessObjects.DataSort _sort;
    public DataSortColumn(Session session)
      : base(session)
    {
    }
    public Aria5.DevExpress.OneTouchAway.Module.BusinessObjects.DataSort Sort
    {
      get
      {
        return _sort;
      }
      set
      {
        SetPropertyValue("Sort", ref _sort, value);
      }
    }
    public System.Int32 Order
    {
      get
      {
        return _order;
      }
      set
      {
        SetPropertyValue("Order", ref _order, value);
      }
    }
    [SizeAttribute(100)]
    public System.String Name
    {
      get
      {
        return _name;
      }
      set
      {
        SetPropertyValue("Name", ref _name, value);
      }
    }
    [SizeAttribute(10)]
    public System.String Direction
    {
      get
      {
        return _direction;
      }
      set
      {
        SetPropertyValue("Direction", ref _direction, value);
      }
    }
  }
}
