//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using System.Linq;

using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using Aria5SystemAdmin.Module;
using DevExpress.Xpo.Metadata;

namespace Aria5.DevExpress.OneTouchAway.Module.BusinessObjects
{
    [DefaultClassOptions]
    [IsClient(true, false)]
    [RelatedEntity("Aria5-Windows8Xaml-GeneralSetting")]


    public partial class GeneralSetting : ClientBaseObject
    {
        public GeneralSetting(Session session)
            : base(session)
        {

        }

        private System.String _Name;
        public System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                SetPropertyValue("Name", ref _Name, value);
            }
        }

        private System.String _Value;
        public System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                SetPropertyValue("Value", ref _Value, value);
            }
        }


        [ValueConverterAttribute(typeof(ImageValueConverter))]
        private System.Drawing.Image _Image;
        public System.Drawing.Image Image
        {
            get
            {
                return _Image;
            }
            set
            {
                SetPropertyValue("Image", ref _Image, value);
            }
        }
        //private ClientAttachments _Image;
        //public ClientAttachments Image
        //{
        //    get
        //    {
        //        return _Image;
        //    }
        //    set
        //    {
        //        SetPropertyValue("Image", ref _Image, value);
        //    }
        //}
    }
}
