//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

using System.Linq;

using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using Aria5SystemAdmin.Module;
using DevExpress.Xpo.Metadata;

namespace Aria5.DevExpress.OneTouchAway.Module.BusinessObjects
{
    [DefaultClassOptions]
    [IsClient(true, false)]
    [RelatedEntity("Aria5-Windows8Xaml-ProfileGroupTile")]

    public partial class ProfileGroupTile :ClientBaseObject
    {
        public ProfileGroupTile(Session session)
            : base(session)
        {

        }
        private Aria5.DevExpress.OneTouchAway.Module.BusinessObjects.ProfileGroup _Group;
        private Aria5.DevExpress.OneTouchAway.Module.BusinessObjects.ClientEntity _entity;
        private Aria5.DevExpress.OneTouchAway.Module.BusinessObjects.ClientEntityCategory _entityCategory;
        private System.Guid _filter;
        private System.String _tileID;
        [SizeAttribute(30)]
        public System.String TileID
        {
            get
            {
                return _tileID;
            }
            set
            {
                SetPropertyValue("TileID", ref _tileID, value);
            }
        }

        [DataSourceProperty("Categories")]
        [ImmediatePostData]
        public Aria5.DevExpress.OneTouchAway.Module.BusinessObjects.ClientEntityCategory EntityCategory
        {
            get
            {
                return _entityCategory;
            }
            set
            {
                SetPropertyValue("EntityCategory", ref _entityCategory, value);
            }
        }
        [DataSourceProperty("Entities")]
        public ClientEntity Entity
        {
            get
            {
                return _entity;
            }
            set
            {
                SetPropertyValue("Entity", ref _entity, value);
            }
        }
        public System.Guid Filter
        {
            get
            {
                return _filter;
            }
            set
            {
                SetPropertyValue("Filter", ref _filter, value);
            }
        }
        [AssociationAttribute("ProfileGroupTiles-ProfileGroup")]
        public ProfileGroup Group
        {
            get
            {
                return _Group;
            }
            set
            {
                SetPropertyValue("Group", ref _Group, value);
                if (this.Group != null && this.Oid.ToString().IndexOf("000") > -1)
                {
                    this.EntityCategory = this.Group.EntityCategory;
                }

            }

        }

        private System.String _LinkedTo;
        public System.String LinkedTo
        {
            get
            {
                return _LinkedTo;
            }
            set
            {
                SetPropertyValue("LinkedTo", ref _LinkedTo, value);
            }
        }

        private ClientEntityType _EntityType;
        public ClientEntityType EntityType
        {
            get
            {
                return _EntityType;
            }
            set
            {
                SetPropertyValue("EntityType", ref _EntityType, value);
            }
        }

        private DataSort _DefaultDataSort;
        public DataSort DefaultDataSort
        {
            get
            {
                return _DefaultDataSort;
            }
            set
            {
                SetPropertyValue("DefaultDataSort", ref _DefaultDataSort, value);
            }
        }


        private System.Guid _Gadget;
        public System.Guid Gadget
        {
            get
            {
                return _Gadget;
            }
            set
            {
                SetPropertyValue("Gadget", ref _Gadget, value);
            }
        }

        private int _Row;
        public int Row
        {
            get
            {
                return _Row;
            }
            set
            {
                SetPropertyValue("Row", ref _Row, value);
            }
        }

        private int _Column;
        public int Column
        {
            get
            {
                return _Column;
            }
            set
            {
                SetPropertyValue("Column", ref _Column, value);
            }
        }

        private System.String _Name;
        [SizeAttribute(1204)]
        public System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                SetPropertyValue("Name", ref _Name, value);
            }
        }

        private System.Drawing.Image _Image;
         [ValueConverterAttribute(typeof(ImageValueConverter))]
        public System.Drawing.Image Image
        {
            get
            {
                return _Image;
            }
            set
            {
                SetPropertyValue("Image", ref _Image, value);
            }
        }
        private System.String _TileTemplateId;
        public System.String TileTemplateId
        {
            get
            {
                return _TileTemplateId;
            }
            set
            {
                SetPropertyValue("TileTemplateId", ref _TileTemplateId, value);
            }
        }

        private System.String _TileTemplateSizeId;
        public System.String TileTemplateSizeId
        {
            get
            {
                return _TileTemplateSizeId;
            }
            set
            {
                SetPropertyValue("TileTemplateSizeId", ref _TileTemplateSizeId, value);
            }
        }

        private System.String _SectionPageId;
        public System.String SectionPageId
        {
            get
            {
                return _SectionPageId;
            }
            set
            {
                SetPropertyValue("SectionPageId", ref _SectionPageId, value);
            }
        }


        private System.String _DetailPageId;
        public System.String DetailPageId
        {
            get
            {
                return _DetailPageId;
            }
            set
            {
                SetPropertyValue("DetailPageId", ref _DetailPageId, value);
            }
        }

        private System.String _Tilestretch;
        public System.String Tilestretch
        {
            get
            {
                return _Tilestretch;
            }
            set
            {
                SetPropertyValue("Tilestretch", ref _Tilestretch, value);
            }
        }

       
       

    }
}
