//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DevExpress.ExpressApp.DC;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl;
using DevExpress.Xpo;
using Aria5SystemAdmin.Module.BusinessObjects;
using Aria5SystemAdmin.Module;
using DevExpress.Xpo.Metadata;
namespace Aria5.DevExpress.OneTouchAway.Module.BusinessObjects
{
  [DefaultClassOptions]
  [IsClient(true, false)]
  [RelatedEntity("Aria5-Windows8Xaml-ProfileSetting")]
  public partial class ProfileSetting : ClientBaseObject
  {
    public ProfileSetting(Session session)
      : base(session)
    {
    }
    private System.String _Value;
    public System.String Value
    {
      get
      {
        return _Value;
      }
      set
      {
        SetPropertyValue("Value", ref _Value, value);
      }
    }
    private System.String _Name;
    public System.String Name
    {
      get
      {
        return _Name;
      }
      set
      {
        SetPropertyValue("Name", ref _Name, value);
      }
    }
    private System.Drawing.Image _Image;
    [ValueConverterAttribute(typeof(ImageValueConverter))]

    public System.Drawing.Image Image
    {
      get
      {
        return _Image;
      }
      set
      {
        SetPropertyValue("Image", ref _Image, value);
      }
    }
    private Guid _Account;
    public Guid Account
    {
        get
        {
            return _Account;
        }
        set
        {
            SetPropertyValue("Account", ref _Account, value);
        }
    }
    private Profile _Profile;
    public Profile Profile
    {
      get
      {
        return _Profile;
      }
      set
      {
        SetPropertyValue("Profile", ref _Profile, value);
      }
    }

  
   
  }
}
