* N000682 ,1 Thabet Handle globalization issues [Start]
#DEFINE LANG_DETAILED_ISTING 'DETAILED LISTING OF OPEN R/A'
#DEFINE LANG_DETAILED_LISTING_OF_ELECTRONIC 'DETAILED LISTING OF ELECTRONIC R/A'  
#DEFINE LANG_DETAILED_LISTING_OF_RETURNS 'DETAILED LISTING OF RETURNS'
#DEFINE LANG_DETAILED_LISTING_OF_OPEN 'DETAILED LISTING OF OPEN R/A ,ELECTRONIC R/A AND RETURNS'
#DEFINE LANG_DETAILED_LISTING_OF_RETURNSANDOPEN 'DETAILED LISTING OF OPEN R/A AND RETURNS'
* N000682 ,1 Thabet Handle globalization issues [END]