#DEFINE LANG_Soorcn_Contract       "Contract"
#DEFINE LANG_Soorcn_Order          "Order"
#DEFINE LANG_Soorcn_EDITemp        "EDI Temp. Order"
#DEFINE LANG_Soorcn_OrdType        "Order Type"
#DEFINE LANG_Soorcn_OrdNum         "Order#"
#DEFINE LANG_Soorcn_Account        "Account"
#DEFINE LANG_Soorcn_Store          "Store"
#DEFINE LANG_Soorcn_EntDate        "Entered Date"
#DEFINE LANG_Soorcn_Season         "Season"
#DEFINE LANG_Soorcn_Division       "Division"
#DEFINE LANG_Soorcn_Terms          "Terms"
#DEFINE LANG_Soorcn_ShipVia        "ShipVia"
#DEFINE LANG_Soorcn_Status         "Status"
#DEFINE LANG_Soorcn_OpenAmt        "Open Amt."
#DEFINE LANG_Soorcn_Bulk           "Bulk"
#DEFINE LANG_Soorcn_OrdOrCont      "Orders/Contracts"
#DEFINE LANG_Soorcn_Orders         "Orders..."
#DEFINE LANG_Soorcn_EDITmpOrd      "EDI Temporary Orders"
#DEFINE LANG_Soorcn_Contracts      "Contracts..."
#DEFINE LANG_Soorcn_NewItem        "New Item"
#DEFINE LANG_Soorcn_DelItem        "Deleted Item"
#DEFINE LANG_Soorcn_QtyDecreased   "Quantity Decreased"
#DEFINE LANG_Soorcn_QtyIncreased   "Quantity Increased"
#DEFINE LANG_Soorcn_PrcChange      "Price Changed"
#DEFINE LANG_Soorcn_QtyChange      "Quantity Changed"
#DEFINE LANG_Soorcn_Style          "Style"
#DEFINE LANG_Soorcn_LineNo         "Line Number"
#DEFINE LANG_Soorcn_Pack           "Pack"
#DEFINE LANG_Soorcn_NotePad        "NotePad"
#DEFINE LANG_Soorcn_OrdNotPad      "Order Notepad"
#DEFINE LANG_Soorcn_EdiTmpNotPad   "EDI Temporary Order Notepad"
#DEFINE LANG_Soorcn_ContNotPad     "Contract Notepad"
#DEFINE LANG_Soorcn_Line           "Line"
#DEFINE LANG_Soorcn_DistCenter     "  Dist. Center : "