#DEFINE LANG_Soorcn_Line           "Line"
#DEFINE LANG_Soorcn_NotePad        "Notepad"
#DEFINE LANG_Soorcn_OrdNotPad      "Order Notepad"
#DEFINE LANG_Soorcn_EdiTmpNotPad   "EDI Temporary Order Notepad" 
#DEFINE LANG_Soorcn_DistCenter     "  Dist. Center : "
#DEFINE LANG_Soorcn_ContNotPad     "Contract Notepad"
#DEFINE LANG_Soorcn_SelMessage     " Selected"
#DEFINE LANG_Soorcn_Records     " Records in "
#DEFINE LANG_Soorcn_Seconds     " Seconds "