#DEFINE LANG_Soorcngm_InList          "IN LIST"
#DEFINE LANG_Soorcngm_PrtOrd          "Printing Order#:..."
#DEFINE LANG_Soorcngm_Abort           "..<Space Bar> TO ABORT"
#DEFINE LANG_Soorcngm_Pack            "PACK # : "
#DEFINE LANG_Soorcngm_Sku             "SKU # : "
#DEFINE LANG_Soorcngm_PackUpc         "PACK UPC#"
#DEFINE LANG_Soorcngm_PackSku         "PACK SKU #"
#DEFINE LANG_Soorcngm_PckUpc          "PACK UPC#: "
#DEFINE LANG_Soorcngm_PckSku          "PACK SKU # : "
#DEFINE LANG_Soorcngm_StyUpc          "STYLE UPC # : "
#DEFINE LANG_Soorcngm_StySku          "STYLE SKU # : " 
#DEFINE LANG_Soorcngm_PriPiec         "Price / Piece"
#DEFINE LANG_Soorcngm_PriPack         "Price / Pack"
