#DEFINE LANG_MFGENCT_SCOPE       'Scope'
#DEFINE LANG_MFGENCT_PO          'P/O'
#DEFINE LANG_MFGENCT_CT          'C/T'
#DEFINE LANG_MFGENCT_ITMSTRNFND  'Item structure not found.'
#DEFINE LANG_MFGENCT_ENTEREDDATE 'Entered date must be less than or equal completion date'
#DEFINE LANG_MFGENCT_COMPLETDATE 'Completion date must be greater than or equal Entered date'
#DEFINE LANG_MFGENCT_UNALLORDERS 'Check the unallocated orders.'
#DEFINE LANG_MFGENCT_ORDER       'Order'
#DEFINE LANG_MFGENCT_SELECT      '\<Select'
#DEFINE LANG_MFGENCT_UNSELECT    'Un\<Select'
#DEFINE LANG_MFGENCT_NOTES       '\<Notes'
#DEFINE LANG_MFGENCT_GENERATE    'Generate'
#DEFINE LANG_MFGENCT_CLEARALO    'Clear Allo\<cation'
#DEFINE LANG_MFGENCT_ALORDERS    'Allocated \<Orders'
#DEFINE LANG_MFGENCT_CLEARGEN    'Clear'
#DEFINE LANG_MFGENCT_ALLOCATE    'Allo\<cate'
#DEFINE LANG_MFGENCT_SELORDLINE  'Selecting order lines.'
#DEFINE LANG_MFGENCT_PODEFAULTS  'P/O Defaults'
#DEFINE LANG_MFGENCT_PRICE       'price'
#DEFINE LANG_MFGENCT_DUTY        'duty'
#DEFINE LANG_MFGENCT_VENDOR      'Vendor'
#DEFINE LANG_MFGENCT_ZERORATE    ' or zero rate'
#DEFINE LANG_MFGENCT_POORDERS    'purchase orders'
#DEFINE LANG_MFGENCT_CTORDERS    'cutting tickets'
#DEFINE LANG_MFGENCT_GENPOORD    'Generating Purchase Orders. Please standby....'
#DEFINE LANG_MFGENCT_ASSIGNSTYLE 'Assigning Style'
#DEFINE LANG_MFGENCT_TOWAREHOUSE 'to warehouse'
#DEFINE LANG_MFGENCT_CHECKUNALLO 'Check the unallocated orders.'
#DEFINE LANG_MFGENCT_DETAILS     'Details'
#DEFINE LANG_MFGENCT_CONFIG      'Configuration'
#DEFINE LANG_MFGENCT_DYELOT      'Dyelot'
#DEFINE LANG_MFGENCT_PRIMFABREQU 'Computing primary fabrics requirements.'
#DEFINE LANG_MFGENCT_IMPSTYCOST  'Imported Style Cost Sheets'
#DEFINE LANG_MFGENCT_MFGSTYCOST  'Manfactured Style Cost Sheets'
#DEFINE LANG_MFGENCT_HOLD        'hold'
#DEFINE LANG_MFGENCT_CANCELLED   'cancelled'
#DEFINE LANG_MFGENCT_INWORK      'in work'
#DEFINE LANG_MFGENCT_COMPLETION  'Completion'
#DEFINE LANG_MFGENCT_FABRICS     'Fabrics'
#DEFINE LANG_MFGENCT_LCTEXT1     'Location Dyelot         Onhand'
#DEFINE LANG_MFGENCT_LCTEXT2     'Unall. WIP'
#DEFINE LANG_MFGENCT_DEALLOCATE  'De\<allocate'
#DEFINE LANG_MFGENCT_ALLOCATE1   '\<Allocate'
#DEFINE LANG_MFGENCT_SOALLO      'Sales Orders Allocation'
#DEFINE LANG_MFGENCT_ADDING      'Adding'
#DEFINE LANG_MFGENCT_POCMD       '\<P/O'
#DEFINE LANG_MFGENCT_LINE        'Line'
#DEFINE LANG_MFGENCT_GENCTORD    'Generating Cutting Tickets. Please standby....'
#DEFINE LANG_MFGENCT_PATTERN     'Pattern'
#DEFINE LANG_MFGENCT_COSTSHEET   'Cost Sheet'
#DEFINE LANG_MFGENCT_DTLCTORDERS 'Details of cutting tickets'

*B608873,1 WAM changes to generate PO from sales order
#DEFINE LANG_MFGENCT_START      'Start'
#DEFINE LANG_MFGENCT_COMPLETE   'Complete'
*B608873,1 WAM (End)

*N000682,1 MMT 11/20/2012 Globalization project[Start]
#DEFINE LANG_MFGENCT_OTS1     "OTS1 "
#DEFINE LANG_MFGENCT_OTS2     "OTS2 "
#DEFINE LANG_MFGENCT_OTS3     "OTS3 "
#DEFINE LANG_MFGENCT_OTS4     "OTS4 "
#DEFINE LANG_MFGENCT_OTS5     "OTS5 "
#DEFINE LANG_MFGENCT_OTS6     "OTS6 "
#DEFINE LANG_MFGENCT_OTS7     "OTS7 "
#DEFINE LANG_MFGENCT_OTS8     "OTS8 "
#DEFINE LANG_MFGENCT_TOT_OTS     "TOT. OTS "
#DEFINE LANG_MFGENCT_ORD1     "Ord1 "
#DEFINE LANG_MFGENCT_ORD2     "Ord2 "
#DEFINE LANG_MFGENCT_ORD3     "Ord3 "
#DEFINE LANG_MFGENCT_ORD4     "Ord4 "
#DEFINE LANG_MFGENCT_ORD5     "Ord5 "
#DEFINE LANG_MFGENCT_ORD6     "Ord6 "
#DEFINE LANG_MFGENCT_ORD7     "Ord7 "
#DEFINE LANG_MFGENCT_ORD8     "Ord8 "
#DEFINE LANG_MFGENCT_TOT_ORD     "Tot. Ord "
#DEFINE LANG_MFGENCT_WEEK     "Week"
#DEFINE LANG_MFGENCT_YEAR     "Year"
#DEFINE LANG_MFGENCT_QTY1     "Qty1"
#DEFINE LANG_MFGENCT_QTY2     "Qty2"
#DEFINE LANG_MFGENCT_QTY3     "Qty3"
#DEFINE LANG_MFGENCT_QTY4     "Qty4"
#DEFINE LANG_MFGENCT_QTY5     "Qty5"
#DEFINE LANG_MFGENCT_QTY6     "Qty6"
#DEFINE LANG_MFGENCT_QTY7     "Qty7"
#DEFINE LANG_MFGENCT_QTY8     "Qty8"
#DEFINE LANG_MFGENCT_TOTQTY     "TotQty"
#DEFINE LANG_MFGENCT_TOT_QTY "Tot. Qty."
#DEFINE LANG_MFGENCT_TEMPLATE 'Template'
#DEFINE LANG_MFGENCT_TEMPLATEDESC 'Description'
#DEFINE LANG_MFGENCT_MTEMPLATE 'Templates'
#DEFINE LANG_MFGENCT_MULTIPLE 'Multiple'
#DEFINE LANG_MFGENCT_SINGLE 'Single'
#DEFINE LANG_MFGENCT_COLLWAITSTYLE 'Collecting data for style:'
#DEFINE LANG_MFGENCT_STYLES 'styles'
#DEFINE LANG_MFGENCT_COMPLETION 'Completion'
#DEFINE LANG_MFGENCT_AVLBLE 'Available'
#DEFINE LANG_MFGENCT_AVLDATE 'Available date'
#DEFINE LANG_MFGENCT_ENTERED 'entered'
*N000682,1 MMT 11/20/2012 Globalization project[End]