#DEFINE LANG_POSTREC_IssueReturn     'Issue Reurn P/O'
#DEFINE LANG_POSTREC_IssueR          'R'
#DEFINE LANG_POSTREC_IssueRMat       'G'
#DEFINE LANG_POSTREC_IssueIntrPO     'Issue Inter Location P/O'
#DEFINE LANG_POSTREC_IssueN          'N'
#DEFINE LANG_POSTREC_IssueIntrPOS    'Issue Inter Location P/O Shipment'
#DEFINE LANG_POSTREC_IssueIntrPOSH   'U'
#DEFINE LANG_POSTREC_IssueIntrPOB    'Issue Inter Location Batch'
#DEFINE LANG_POSTREC_IssueH          'H'
#DEFINE LANG_POSTREC_IssueAdronPO    'Issue Adornment P/O'
#DEFINE LANG_POSTREC_IssueA          'A'
#DEFINE LANG_POSTREC_ReceiveCT       'Receive Cutting Ticket'
#DEFINE LANG_POSTREC_ReceiveM        'M'
#DEFINE LANG_POSTREC_ReceiveCTB      'Receive Batch'
#DEFINE LANG_POSTREC_ReceiveT        'T'
#DEFINE LANG_POSTREC_ReceiveDyeOrd   'Receive Dye Order'
#DEFINE LANG_POSTREC_ReceiveD        'D'
#DEFINE LANG_POSTREC_ReceiveSPOShip  'Receive by Shipment'
#DEFINE LANG_POSTREC_ReceiveSS       'S'
#DEFINE LANG_POSTREC_ReceivePOB      'Receive P/O Batch'
#DEFINE LANG_POSTREC_ReceiveSPOB     'B'
#DEFINE LANG_POSTREC_ReceivePO       'Receive by P/O'
#DEFINE LANG_POSTREC_ReceiveSPOI     'I'
#DEFINE LANG_POSTREC_ReceiveIntrPO   'Receive Inter Location P/O'
#DEFINE LANG_POSTREC_ReceiveIntrPOO  'O'
#DEFINE LANG_POSTREC_ReceiveIntrPOBT 'Receive Inter Location P/O Batch'
#DEFINE LANG_POSTREC_ReceiveIntrPOIS 'Receive Inter Location P/O Shipment'
#DEFINE LANG_POSTREC_ReceiveIntrPOSH  'C'
#DEFINE LANG_POSTREC_ReceiveIntrPOB  'L'
#DEFINE LANG_POSTREC_ReceiveAdronPO  'Receive Adronment PO'
#DEFINE LANG_POSTREC_ReceiveAdronPOE 'E'
#DEFINE LANG_POSTREC_AssignBins      'Assign Bins'
#DEFINE LANG_POSTREC_ReceiveMatPO    'Receive by P/O'
#DEFINE LANG_POSTREC_ReceiveMatPOP    'P'
#DEFINE LANG_POSTREC_ReceiveMatPOSHP  'Receive by Shipment'
#DEFINE LANG_POSTREC_ReceiveMatPOF    'F'
#DEFINE LANG_POSTREC_BrowseTitle      'Style Purchase Orders'
#DEFINE LANG_POSTREC_POBrowTitl       'P/O #  '
#DEFINE LANG_POSTREC_StatusBrowTitl   'Status'
#DEFINE LANG_POSTREC_VendorBrowTitl   'Vendor'
#DEFINE LANG_POSTREC_EnteredBrowTitl  'Entered'
#DEFINE LANG_POSTREC_CompleteBrowTitl 'Complete'
#DEFINE LANG_POSTREC_TotQtyBrowTitl   'Total Qty.'
#DEFINE LANG_POSTREC_AmountBrowTitl   'Amount'
#DEFINE LANG_POSTREC_ReceiveBrowTitl  'Receive'
#DEFINE LANG_POSTREC_OpenBrowTitl      'Open'
#DEFINE LANG_POSTREC_IntrLocBrowseTitle  'Inter-Location Purchase Orders'
#DEFINE LANG_POSTREC_SourceLBrowTitl    'Source Location'

*AMH*
#DEFINE LANG_POSTREC_1STQUALITY         '1st Quality'
#DEFINE LANG_POSTREC_2NDQUALITY         '2nd Quality'
#DEFINE LANG_POSTREC_DAMAGED            'Damaged'
#DEFINE LANG_POSTREC_FIRSTQUALITY       'First Quality'
#DEFINE LANG_POSTREC_SECONDQUALITY      'Second Quality'
#DEFINE LANG_POSTREC_MFRCVQ             'Edit Line Quantity'
#DEFINE LANG_POSTREC_BUDGET             'Budget'
#DEFINE LANG_POSTREC_PRVRCPT            'Prv. Rcpt .'
#DEFINE LANG_POSTREC_CANCEL             'Cancel'
#DEFINE LANG_POSTREC_BALANCE            'Balance'
#DEFINE LANG_POSTREC_MESSAG1            'You can not exceed the issued quantity.'

*! B125565,1 WSH 04/11/2005, Add Constants to use in calling POSTYREC. [Start]
#DEFINE LANG_POSTREC_POSTYREC           'Style P/O Receipts Log'
#DEFINE LANG_POSTREC_MAPOREC            'Material P/O Receipts Log'
#DEFINE LANG_POSTREC_DYEORD             'Dye Order Receipts Log'
*! B125565,1 WSH 04/11/2005, [End]

*: N000601,1 MMT 03/20/2007 Convert Rolls Screen to Aria4XP[Start]
#DEFINE LANG_POSTREC_ROLLS            'Rolls label'
*: N000601,1 MMT 03/20/2007 Convert Rolls Screen to Aria4XP[End]


*E302963,1 MMT 09/07/2011 Modify the PO Receiving to Import Scanned Batch and create Temp. rec. Batch[T20110521.0001][Start]
#DEFINE LANG_POSTREC_STATUS_OPEN 'Open'
#DEFINE LANG_POSTREC_STATUS_O 'O'
#DEFINE LANG_POSTREC_STATUS_A 'A'
#DEFINE LANG_POSTREC_STATUS_APPROVED  'Approved'
#DEFINE LANG_POSTREC_TMPRECBATCH 'Temporary receiving batch'
#DEFINE LANG_POSTREC_STATUS_CANCEL 'Cancelled'
#DEFINE LANG_POSTREC_STATUS_POSTED 'Posted'
#DEFINE LANG_POSTREC_STATUS_P 'P'
#DEFINE LANG_POSTREC_STATUS_X 'X'
#DEFINE LANG_POSTREC_ISPOSTED 'is posted'
#DEFINE LANG_POSTREC_ISNOTAPPROVED 'is not approved'
#DEFINE LANG_POSTREC_ISCANCELLED 'is cancelled'
#DEFINE LANG_POSTREC_CANCBATCH   'Cancel Batch'
#DEFINE LANG_POSTREC_BATCHBROWSE_REC         'Recv. #'
#DEFINE LANG_POSTREC_BATCHBROWSE_REC_STATUS  "S"
#DEFINE LANG_POSTREC_BATCHBROWSE_REC_DESC    "Description"
#DEFINE LANG_POSTREC_BATCHBROWSE_REC_DATE    "Date"
#DEFINE LANG_POSTREC_BATCHBROWSE_TOTSTK      "Tot.Stk"
#DEFINE LANG_POSTREC_BATCHBROWSE_REC_TOTOTH  "Tot.Oth"
#DEFINE LANG_POSTREC_BATCHBROWSE_REC_TOTCAN  "Tot.Can"
#DEFINE LANG_POSTREC_BATCHBROWSE_TITLE 'Temp. Receive Batchs'
#DEFINE LANG_POSTREC_BATCHHASNOLINES 'has no lines'
#DEFINE LANG_POSTREC_BATCH_ERROR "*                                Error log                                                                 *"
#DEFINE LANG_POSTREC_BATCH_NO   'Batch#'
#DEFINE LANG_POSTREC_BATCH_DESC 'Desc.#'
#DEFINE LANG_POSTREC_BATCH_VENDOR 'Vendor'
#DEFINE LANG_POSTREC_BATCH_DATE 'Date'
#DEFINE LANG_POSTREC_BATCH_TITLE "BATCH"
#DEFINE LANG_POSTREC_BATCH_STYLE  "STYLE: "
#DEFINE LANG_POSTREC_BATCH_CANCELREC 'cancel'
#DEFINE LANG_POSTREC_BATCH_UNCANCELREC 'uncancel'
#DEFINE LANG_POSTREC_BATCH_UNCANCELBATCH 'Uncancel Batch'
#DEFINE LANG_POSTREC_BATCH_CANCBATCH 'Cancel Batch'
#DEFINE LANG_POSTREC_STYLENOTINPO    'Style is not included in this PO'
*E302963,1 MMT 09/07/2011 Modify the PO Receiving to Import Scanned Batch and create Temp. rec. Batch[T20110521.0001][END]

*N037687,1 MMT 09/30/2012 Convert Receive MFG Order to Aria4xp[T20110914.0019][START]
#DEFINE LANG_POSTREC_MMO_REC_MMO  "Receive Material Manufacturing Order"           
#DEFINE LANG_POSTREC_REC_MMO  "Material Manufacturing Receive"           
#DEFINE LANG_POSTREC_MMOW          'W'
#DEFINE LANG_POSTREC_MMO_MMO "Material Manufacturing Order"           
#DEFINE LANG_POSTREC_MMO_RECING_MMO  "Receiving Material Manufacturing Order"           
*N037687,1 MMT 09/30/2012 Convert Receive MFG Order to Aria4xp[T20110914.0019][END]

*N000682,1 MMT 11/20/2012 Globalization project[Start]
#DEFINE LANG_POSTREC_ISSUE_INTERLOCATION_PO     "Issue Inter-Location PO"
#DEFINE LANG_POSTREC_RECEIVE_MATERIAL_PO     "Receive Material PO"
#DEFINE LANG_POSTREC_ISSUE_RETURN_STYLE_PO     "Issue Return Style PO"
#DEFINE LANG_POSTREC_ISSUE_RETURN_MATERIAL_PO     "Issue Return Material PO"
#DEFINE LANG_POSTREC_INTERLOC_PO     'Inter-Loc. P/O#'
#DEFINE LANG_POSTREC_CT     'C/T #'
#DEFINE LANG_POSTREC_ISSUING_DATE     "Issuing Date"
#DEFINE LANG_POSTREC_RECEIVING_DATE     "Receiving Date"
#DEFINE LANG_POSTREC_CARTONS     "Cartons"
#DEFINE LANG_POSTREC_CONFIGURATION     'Configuration'
#DEFINE LANG_POSTREC_DYELOT     'Dyelot'
#DEFINE LANG_POSTREC_SOURCE_1     'Source'
#DEFINE LANG_POSTREC_TARGET     'Target'
#DEFINE LANG_POSTREC_LOCATION     'Location'
#DEFINE LANG_POSTREC_PATTERN     'Pattern'
#DEFINE LANG_POSTREC_ORIGINAL     'Original'
#DEFINE LANG_POSTREC_STOCK     'Stock'
#DEFINE LANG_POSTREC_OTHER     'Other'
#DEFINE LANG_POSTREC_REFERENCE     'Reference'
#DEFINE LANG_POSTREC_ORDER     'Order #'
#DEFINE LANG_POSTREC_PO     'P/O#'
#DEFINE LANG_POSTREC_ROLLS_1     'RO\<LLS'
#DEFINE LANG_POSTREC_LOTS     '\<LOTS'
#DEFINE LANG_POSTREC_ROLLS_2 '\<Rolls'
#DEFINE LANG_POSTREC_TITLE_DYEORDER 'Dye Order'
#DEFINE LANG_POSTREC_TITLE_ADOR 'Adornment Order'
#DEFINE LANG_POSTREC_TITLE_INTERPO 'Inter-Location P/O'
#DEFINE LANG_POSTREC_TITLE_CT 'Cutting ticket'
#DEFINE LANG_POSTREC_TITLE_RETPO 'Return P/O'
#DEFINE LANG_POSTREC_TITLE_PO 'P/O'
#DEFINE LANG_POSTREC_MSG_RECEVING  'receiving'
#DEFINE LANG_POSTREC_MSG_ISSUING 'issuing'
#DEFINE LANG_POSTREC_MSG_ISS 'issue'
#DEFINE LANG_POSTREC_MSG_REC 'receive'
#DEFINE LANG_POSTREC_MSG_ISCOMPLTELYRECEVIED 'is completely received. Cannot proceed.'
#DEFINE LANG_POSTREC_MSG_COMPLETE 'complete'
#DEFINE LANG_POSTREC_MSG_BID 'Bid'
#DEFINE LANG_POSTREC_MSG_CLOSED 'Closed'
#DEFINE LANG_POSTREC_MSG_STYLE 'Style'
#DEFINE LANG_POSTREC_MSG_FABRIC 'Fabric'
#DEFINE LANG_POSTREC_MSG_RECCT 'receiving cutting ticket'
#DEFINE LANG_POSTREC_MSG_RECDYE 'receiving dye order'
#DEFINE LANG_POSTREC_MSG_RECINTER 'receiving inter location P/O'
#DEFINE LANG_POSTREC_MSG_RECPO 'receiving purchase order'
#DEFINE LANG_POSTREC_OPTION 'O\<ptions'
#DEFINE LANG_POSTREC_EDTLANFCSTPERLINE 'Edit landed cost per line'
#DEFINE LANG_POSTREC_PRICE 'Price'
#DEFINE LANG_POSTREC_TOTALCOST 'Total Cost'
#DEFINE LANG_POSTREC_SHIPTO 'ShipTo'
#DEFINE LANG_POSTREC_QTY 'Quantity'
#DEFINE LANG_POSTREC_DESCSTY 'Desc'
#DEFINE LANG_POSTREC_SHIPPING 'Shipping'
#DEFINE LANG_POSTREC_POSTING 'Posting all transactions ...'
#DEFINE LANG_POSTREC_UPDATEGL 'Updating General Ledger Distribution File '
#DEFINE LANG_POSTREC_BROWLINE 'Line'
#DEFINE LANG_POSTREC_BROWSELECT 'Select'
#DEFINE LANG_POSTREC_RECDATE 'This receiving date'
#DEFINE LANG_POSTREC_FALLANYPRD 'does not fall within any period.'
#DEFINE LANG_POSTREC_LIKECONTINUE 'Would you like to continue any way ?'
#DEFINE LANG_POSTREC_S_SHIPMENT 'shipment'
#DEFINE LANG_POSTREC_COMPREC 'completely received'
#DEFINE LANG_POSTREC_HOLD 'Hold'
#DEFINE LANG_POSTREC_CANCELLED 'canceled'
#DEFINE LANG_POSTREC_ISISSUED 'is issued'
#DEFINE LANG_POSTREC_ISNOTISSUED 'is not issued'
#DEFINE LANG_POSTREC_ISSUED 'issued'
#DEFINE LANG_POSTREC_REVD 'received'
#DEFINE LANG_POSTREC_MSGROLLS 'rolls'
#DEFINE LANG_POSTREC_MSGLOTS 'lots'
#DEFINE LANG_POSTREC_MSGISSUES 'issues'
#DEFINE LANG_POSTREC_MSGRECEIPTS 'receipts'
#DEFINE LANG_POSTREC_APO 'a P/O'
#DEFINE LANG_POSTREC_ANINTERLOC 'an Inter-Location P/O'
#DEFINE LANG_POSTREC_LOTBROW_LOTNO 'Lot No.'
#DEFINE LANG_POSTREC_LOTBROW_OPERATION 'Operation'
#DEFINE LANG_POSTREC_LOTBROW_CONTDEPT 'Cont./Dept.'
#DEFINE LANG_POSTREC_LOTBROW_NAME 'Name'
#DEFINE LANG_POSTREC_LOTBROW_TRANSDATE 'Trans.Date'
#DEFINE LANG_POSTREC_LOTBROW_DUEDATE 'Due Date'
#DEFINE LANG_POSTREC_LOTBROW_TOTAL 'Total'
#DEFINE LANG_POSTREC_LOTBROW_LOTS 'Lots'
#DEFINE LANG_POSTREC_TITLECT "Cutting Tickets"
#DEFINE LANG_POSTREC_BROWCT "Cutkt#"
#DEFINE LANG_POSTREC_BROWDIVISION "Division"
*N000682,1 MMT 11/20/2012 Globalization project[End]
*B610575,1 MMT 11/04/2013 add option to Print Cut tkt rec. log while receiving Cut.tkt[T20131030.0018][Start]
#DEFINE LANG_POSTREC_CTRECLOG 'Cutting Ticket Receipts Log'
*B610575,1 MMT 11/04/2013 add option to Print Cut tkt rec. log while receiving Cut.tkt[T20131030.0018][End]