#DEFINE LANG_Arshlog_SelectMsg    " Selected"
#DEFINE LANG_Arshlog_RecInMsg     " Records in"
#DEFINE LANG_Arshlog_SecondMsg    "  Seconds..."
#DEFINE LANG_Arshlog_StCode       " Code "
#DEFINE LANG_Arshlog_Description  "Description"
#DEFINE LANG_Arshlog_Group        " Group"
#DEFINE LANG_Arshlog_Account      "Account"
#DEFINE LANG_Arshlog_TotalMsg     " Totals ==>"
#DEFINE LANG_Arshlog_Acct         "Acct#"
#DEFINE LANG_Arshlog_Store        "Store"
#DEFINE LANG_Arshlog_Name         "Name"
#DEFINE LANG_Arshlog_StCodes      " Codes"
#DEFINE LANG_Arshlog_Dept         "Department"
#DEFINE LANG_Arshlog_Invoice      "Invoice"
#DEFINE LANG_Arshlog_ShipDate     "Shipping Date"
#DEFINE LANG_Arshlog_SalesRep     "Sales Rep"
#DEFINE LANG_Arshlog_DEPARTMENT   "DEPARTMENT"
#DEFINE LANG_Arshlog_InvNo		  "Invoice No."
#DEFINE LANG_Arshlog_ShipDt		  "SHIPDATE"
#DEFINE LANG_Arshlog_SalesRp	  "SALESREP"
