#DEFINE LANG_UPSPACK_LblInvoice       'Invoice'
#DEFINE LANG_UPSPACK_LblDate          'Date'
#DEFINE LANG_UPSPACK_LblAccount	      'Account'
#DEFINE LANG_UPSPACK_LblStore		  'Store'
#DEFINE LANG_UPSPACK_LblOrder		  'Order'
#DEFINE LANG_UPSPACK_LblName		  'Name'
#DEFINE LANG_UPSPACK_LblPieces		  'Pieces'
#DEFINE LANG_UPSPACK_LblAmount		  'Amount'
#DEFINE LANG_UPSPACK_LblWareHouse	  'Warehouse'
#DEFINE LANG_UPSPACK_LblCurrency	  'Currency'
#DEFINE LANG_UPSPACK_LblCurrRate	  'Curr.Rate'
#DEFINE LANG_UPSPACK_LblRep1		  'Rep1'
#DEFINE LANG_UPSPACK_LblComm		  'Comm'
#DEFINE LANG_UPSPACK_LblRep2		  'Rep2'
#DEFINE LANG_UPSPACK_LblTerms		  'Terms'
#DEFINE LANG_UPSPACK_MsgNtUPS         'Ship Via for the selected invoice is not UPS type.'
#DEFINE LANG_UPSPACK_Voided			  'Voided'
#DEFINE LANG_UPSPACK_Active			  'Active'
#DEFINE LANG_UPSPACK_ButtCancel       '\<Cancel'
#DEFINE LANG_UPSPACK_ButtClose        '\<Close'
#DEFINE LANG_UPSPACK_MsgPrint         'Do You Want To'
#DEFINE LANG_UPSPACK_BrowHdr          'Invoices'