SET DELETED ON
CLOSE TABLES ALL
SET SAFETY OFF 
SET TALK OFF 

= MESSAGEBOX("Please select the System Files Directory.",64,'Fill EDICRTSQ file program')
LCSYSDIR = GETDIR("","Select Aria27 System Files Folder")
LCSYSDIR = UPPER(ADDBS(LCSYSDIR))

IF !FILE(LCSYSDIR+'SYDFILES.DBF')
  =MESSAGEBOX("This is not the System Files Directory. Cannot proceed.",16,'Update SQL Mapppings Dictionary')
  RETURN
ENDIF

USE LCSYSDIR+'SYCCOMP.DBF' IN 0 SHARED
SELECT SYCCOMP
SCAN FOR !EMPTY(CCOM_DDIR)
  
  LCDATADIR = ADDBS(ALLTRIM(CCOM_DDIR))
  
  USE LCDATADIR+'codes.DBF' IN 0 SHARED  
  SELECT CODES
  SET ORDER TO CCODE_NO   && CDEFCODE+CFLD_NAME+CCODE_NO+CDISCREP+CRLTD_NAM 
 
  SELECT * FROM codes WHERE ALLTRIM(cfld_name) == "CTERMCODE" AND codes.crltfield = "N" INTO CURSOR NXTMNTH1
  SELECT NXTMNTH1
  SCAN 
    WAIT WINDOW "Fix compnay "+SYCCOMP.ccomp_id +" Code " + ALLTRIM(NXTMNTH1.CDISCREP) NOWAIT 
    
    SELECT CODES
    if SEEK(NXTMNTH1.CDEFCODE+NXTMNTH1.CFLD_NAME+NXTMNTH1.CCODE_NO+SPACE(30)+'NTERDISCD' )
      SCATTER MEMVAR MEMO 
      M.crltd_nam = "NXTMNTHDY"
      M.crltd_vlu = "10"
          
      APPEND BLANK 
      GATHER MEMVAR MEMO 
    ENDIF 
    
    SELECT CODES    
    IF SEEK(NXTMNTH1.CDEFCODE+NXTMNTH1.CFLD_NAME+NXTMNTH1.CCODE_NO+SPACE(30)+'EOMDAY') AND ALLTRIM(codes.crltd_vlu)='0'
      Replace codes.crltd_vlu WITH '20'
    ENDIF 
    
    SELECT NXTMNTH1
  ENDSCAN 
  USE IN NXTMNTH1
  USE IN codes

ENDSCAN

USE IN SYCCOMP

= MESSAGEBOX(" Fix Is Done !!")

