#DEFINE LANG_Cut_Title	'Mass Cutting Ticket Cancellation'
#DEFINE LANG_Po_Title	'Mass Purchase Order Cancellation'
#DEFINE LANG_So_Title   'Mass Order Cancellation'
#DEFINE LANG_Collect    'Collecting Order quantities for order# '
#DEFINE LANG_No_Rec	    'No records were selected'
#DEFINE LANG_Select 	'Se\<lect'
#DEFINE LANG_unSelect	'UnSe\<lect'
#DEFINE LANG_So_MSG		'Sales Orders'
#DEFINE LANG_Po_MSG		'Purchase Orders'
#DEFINE LANG_Inter_MSG	'Inter-Location Purchase Orders'
#DEFINE LANG_CT_MSG				'Cutting Tickets'
#DEFINE LANG_Msg_Alloc         'There is an allocated SO, with a Pick Ticket, for these CT lines. '
#DEFINE LANG_Msg_Release 	 'You have to release this Pick Ticket manually first'
#DEFINE LANG_Msg_CT 		'These cutting tickets have allocated quantities from order(s),'
#DEFINE LANG_Msg_CT_Cncl	'canceling these lines will release the allocation, would you like to continue ?'
#DEFINE LANG_Msg_Alloc_Po   'There is an allocated SO, with a Pick Ticket, for these PO lines. '
#DEFINE LANG_Msg_Po			'These Purchase Orders have allocated quantities from order(s),'
#DEFINE LANG_Msg_So			'These Sales Order lines have allocated quantities,'
#DEFINE LANG_Msg__cancl_den 'canceling these lines will release the allocation, but access to do this is denied, Cannot proceed.'
#DEFINE LANG_Msg__Hold_Ct_Po   'CT/PO is Hold, Would You like to update the generated CT/PO accordingly?'
#DEFINE LANG_Upd_msg 		'Updating CT# '
#DEFINE LANG_Upd_msg_PO 		'Updating PO# '
#DEFINE LANG_Qty_msg_MAX 		' is the maximum quantity to shave'