# DEFINE LANG_Arcmlb_SRepCode     'Sales Representitive Code'
# DEFINE LANG_Arcmlb_Name         'Name'
# DEFINE LANG_Arcmlb_waitwindow1  'Collecting data For Account # ..'
# DEFINE LANG_Arcmlb_Fac          'Factor'
# DEFINE LANG_Arcmlb_Contact      'Contact'
# DEFINE LANG_Arcmlb_Phone        'Phone'   
# DEFINE LANG_Arcmlb_FileTtl      'State Codes'
# DEFINE LANG_Arcmlb_StateCode    'State Code'
# DEFINE LANG_Arcmlb_Desc         'Description'
# DEFINE LANG_Arcmlb_Range        'Range 1 : 9'