#DEFINE LANG_ICSTYREP_TextMode              "TEXT"
#DEFINE LANG_ICSTYREP_CollData              "Collecting data..."
#DEFINE LANG_ICSTYREP_PrintedTranscations   "Transactions to be printed"
#DEFINE LANG_ICSTYREP_WIP                   "WIP"
#DEFINE LANG_ICSTYREP_Stock                 "Stock"
#DEFINE LANG_ICSTYREP_Dyelot				"Dyelot"
#DEFINE LANG_ICSTYREP_Plan					"Plan"
#DEFINE LANG_ICSTYREP_Unallocated			"Unallocated"
#DEFINE LANG_ICSTYREP_OTS					"OTS"
#DEFINE LANG_ICSTYREP_Imm_OTS				"Imm. OTS"
#DEFINE LANG_ICSTYREP_Orders				"Orders"
#DEFINE LANG_ICSTYREP_Work_orders			"Work orders"
#DEFINE LANG_ICSTYREP_Intransit				"Intransit"
#DEFINE LANG_ICSTYREP_Book					"Book"
#DEFINE LANG_ICSTYREP_Shipped				"Shipped"
#DEFINE LANG_ICSTYREP_Allocated				"Allocated"
#DEFINE LANG_ICSTYREP_Return				"Return"
#DEFINE LANG_ICSTYREP_Return_auth		    "Return auth."
#DEFINE LANG_ICSTYREP_Error                 "Error, No Transaction was selected !!!"
#DEFINE LANG_ICSTYREP_Ordered				"Ordered"
#DEFINE LANG_ICSTYREP_Work_Ordered          "Work Ordered"
#DEFINE LANG_ICSTYREP_Return_Auth1		    "Return Auth."
#DEFINE LANG_ICSTYREP_Booked				"Booked"
#DEFINE LANG_ICSTYREP_Open_to_sell			"Open to sell"
#DEFINE LANG_ICSTYREP_Imm_Open_to_sell      "Imm. Open to sell"
#DEFINE LANG_ICSTYREP_Style           		"Style"
#DEFINE LANG_ICSTYREP_Season           		"Season"
#DEFINE LANG_ICSTYREP_Division         		"Division"
#DEFINE LANG_ICSTYREP_Primary_Fabric		"Primary Fabric"
#DEFINE LANG_ICSTYREP_Style_Group           "Style Group"
#DEFINE LANG_ICSTYREP_Material_type			"Material type"
#DEFINE LANG_ICSTYREP_Department			"Department"
#DEFINE LANG_ICSTYREP_Printer				"PRINTER"
#DEFINE LANG_ICSTYREP_Location              "Location"
#DEFINE LANG_ICSTYREP_Bin					"Bin"
#DEFINE LANG_ICSTYREP_Total					"Total"
#DEFINE LANG_ICSTYREP_Cost_Val				"Cost Val."
#DEFINE LANG_ICSTYREP_Sales_Val				"Sales Val."
#DEFINE LANG_ICSTYREP_ALERT					"ALERT"
#DEFINE LANG_ICSTYREP_Unit_Price			"Unit_Price"
#DEFINE LANG_ICSTYREP_Sales_Value			"Sales_Value"
#DEFINE LANG_ICSTYREP_Avrg_Cost				"Avrg_Cost"
#DEFINE LANG_ICSTYREP_Cost_Value			"Cost_Value"
#DEFINE LANG_ICSTYREP_Unit_Cost				"Unit_Cost"
#DEFINE LANG_ICSTYREP_Bins					"Bins"
#DEFINE LANG_ICSTYREP_Ave_Cost				"Ave_Cost"
#DEFINE LANG_ICSTYREP_Description			"Description"
#DEFINE LANG_ICSTYREP_Average_cost			"Average cost"
#DEFINE LANG_ICSTYREP_Warehouse_Total		"Warehouse Total"
#DEFINE LANG_ICSTYREP_Grand_Total			"Grand Total"
#DEFINE LANG_ICSTYREP_Positive				"Positive"
#DEFINE LANG_ICSTYREP_Negative				"Negative"
#DEFINE LANG_ICSTYREP_Net					"Net"
#DEFINE LANG_ICSTYREP_Both					"Both"
#DEFINE LANG_ICSTYREP_All	  				"All"
#DEFINE LANG_ICSTYREP_Configuration			"Configuration"
#DEFINE LANG_ICSTYREP_Dialog	  	    	"Dialog"