#DEFINE LANG_SoAlocp_Select    "Selecting record for "
#DEFINE LANG_SoAlocp_CutTktA   "C/T # "
#DEFINE LANG_SoAlocp_PoA       "P/O # "
#DEFINE LANG_SoAlocp_CutTktB   "CutTkt#"
#DEFINE LANG_SoAlocp_PoB       "P/O#"
#DEFINE LANG_SoAlocp_Status    "Status"
#DEFINE LANG_SoAlocp_Issue     "Issue" 
#DEFINE LANG_SoAlocp_Complete  "Complete"
#DEFINE LANG_SoAlocp_Season    "Se"
#DEFINE LANG_SoAlocp_Div       "Di"
#DEFINE LANG_SoAlocp_Budget    "Budget"
#DEFINE LANG_SoAlocp_Damage    "Dameged"
#DEFINE LANG_SoAlocp_Open      "Open"
#DEFINE LANG_SoAlocp_Vendor    "Vendor"
#DEFINE LANG_SoAlocp_Name      "Name"
#DEFINE LANG_SoAlocp_TotQty    "Tot. Qty."
#DEFINE LANG_SoAlocp_Amount    "Amount"
#DEFINE LANG_SoAlocp_Receive   "Receive"
#DEFINE LANG_SoAlocp_PrntDye   "Print Dyelot"
#DEFINE LANG_SoAlocp_PrntCnfg  "Print Configuration"
#DEFINE LANG_SoAlocp_LblZ      "ZZZZZZ"
#DEFINE LANG_SoAlocp_SelStyle  "Selecting Records for Style "
#DEFINE LANG_SoAlocp_Bid       "Bid"       
#DEFINE LANG_SoAlocp_Hold      "Hold"     
#DEFINE LANG_SoAlocp_Cancelled "Cancelled" 
*!* B609356,1 SMA 07/28/2010 Already exist....[BEGIN]... [T20091027.0093]
*#DEFINE LANG_SoAlocp_Complete  "Complete"  
*!* B609356,1 SMA 07/28/2010 Already exist....[END]..... [T20091027.0093]
