#DEFINE LANG_Soshlb_Printing			"Printing"
#DEFINE LANG_Soshlb_Order				"Order"
#DEFINE LANG_Soshlb_Invoice				"Invoice"			  	
#DEFINE LANG_Soshlb_pick_ticket			"Pick Ticket"
#DEFINE LANG_Soshlb_Coll_Pick           "Collecting Data for Pick Ticket # "
#DEFINE LANG_Soshlb_Coll_Invoice   		"Collecting Data for Invoice # "
#DEFINE LANG_Soshlb_Coll_Order			"Collecting Data for Order # "
#DEFINE LANG_Soshlb_Store				" Store: "
#DEFINE LANG_Soshlb_Labels              " Labels" 
#DEFINE LANG_Soshlb_MultiPo				"*Multi_PO*     "
