* N000682 ,1 Thabet Handle globalization issues [Start]
#DEFINE LANG_REPORT_DATE 'report date'
#DEFINE LANG_NO_OF_1 'No. of days for the 1st bucket|zero'
#DEFINE LANG_NO_OF_2 'No. of days for the 2nd bucket|no. of days for the 1st bucket'
#DEFINE LANG_NO_OF_3 'No. of days for the 3rd bucket|no. of days for the 2nd bucket'
#DEFINE LANG_NO_OF_4 'No. of days for the 4th bucket|no. of days for the 3rd bucket'
#DEFINE LANG_ENTERED_VALUE_ZERO 'Entered value|zero'
#DEFINE LANG_CURRENCY 'Currency'
#DEFINE LANG_CURRENCY_CODE 'Currency code'
#DEFINE LANG_DESCRIPTION 'Description'
#DEFINE LANG_SYMBOL 'Symbol'
#DEFINE LANG_FACTOR 'Factor'
#DEFINE LANG_FACTORS 'Factors'
#DEFINE LANG_FACTOR_COMPANY_NAME 'Factor/Company name'
#DEFINE LANG_BUCKETSIZE 'Bucket Size'
#DEFINE LANG_DAY1BUCKET 'Days for 1st Bucket'
* N000682 ,1 Thabet Handle globalization issues [END]