* N000682 ,1 Thabet Handle globalization issues [Start]
#DEFINE LANG_Validating_vendor 'Validating vendor'
#DEFINE LANG_Transactions 'Transactions'
#DEFINE LANG_Validating_data_for_Invoice 'Validating data for Invoice# :'
#DEFINE LANG_Currency 'Currency' 
#DEFINE LANG_Currency_code 'Currency code'
#DEFINE LANG_Description 'Description'
#DEFINE LANG_Symbol 'Symbol'
#DEFINE LANG_STYPO 'Style Purchase Order'
#DEFINE LANG_RETSTYPO 'Style Purchase Order Return'
#DEFINE LANG_SHIPMENT 'Shipment'
#DEFINE LANG_CUTTKT 'Cutting Ticket'
#DEFINE LANG_MAPO 'Material PO'
#DEFINE LANG_RETMAPO 'Material PO Return'
#DEFINE LANG_MFGORDER 'Material MFG Order' 
#DEFINE LANG_GENEXP 'General Expense' 
#DEFINE LANG_COSTPP 'Purchase Price'
#DEFINE LANG_COSTF 'Freight'
#DEFINE LANG_COSTT 'Tax'
#DEFINE LANG_COSTQ 'Quota'
#DEFINE LANG_COST_TYPE 'Cost Type'
#DEFINE LANG_BR_RETPO 'Return P/O#'
#DEFINE LANG_BR_PO 'P/O #'
#DEFINE LANG_BR_VENDOR 'Vendor'
#DEFINE LANG_BR_S 'S'
#DEFINE LANG_BR_NAME 'Name'
#DEFINE LANG_BR_ENTERED 'Entered'
#DEFINE LANG_BR_TOTQTY 'Tot.Qty.'
#DEFINE LANG_BR_COMPLETE 'Complete'
#DEFINE LANG_BR_AMOUNT 'Amount'
#DEFINE LANG_BR_RECEIVE 'Receive'
#DEFINE LANG_BR_OPEN 'Open'
#DEFINE LANG_BR_CUTTKT 'Cutkt'
#DEFINE LANG_BR_STYLE 'Style'   
#DEFINE LANG_BR_SE 'Se'
#DEFINE LANG_BR_ISSUE 'Issue'  
#DEFINE LANG_BR_DI 'Di'
#DEFINE LANG_BR_BUGDGET 'Budget'
#DEFINE LANG_BR_DAMAGE 'Damged'
#DEFINE LANG_BR_RCVD 'Recvd' 
#DEFINE LANG_BR_ORDER 'Order#'
#DEFINE LANG_BR_FABRIC 'Fabric'
#DEFINE LANG_BR_WAREHOUSE  'Warehouse'
#DEFINE LANG_RETPOMA  "Return Material PO #"
#DEFINE LANG_MATPONO "Material PO #"
* N000682 ,1 Thabet Handle globalization issues [END]