#DEFINE LANG_Hold					'On Hold'
#DEFINE LANG_Select 				'Se\<lect'
#DEFINE LANG_unSelect				'UnSe\<lect'
#DEFINE LANG_AccTitl 				'Accounts'
#DEFINE LANG_Wait_Approve			'Approving orders...'
#DEFINE LANG_Wait_Approve_ORDERS	'Approving orders for account : '
#DEFINE LANG_Approve_ORDERS_NUM		" , order# "
#DEFINE LANG_Order					'Order#'
#DEFINE LANG_Status					'Status'
#DEFINE LANG_Season					'Season'
#DEFINE LANG_Factor					'Factor'
#DEFINE LANG_Complete				'Complete'
#DEFINE LANG_OpenAmnt				'Open Amnt.'
#DEFINE LANG_AprNum					'Aprvl-No'
#DEFINE LANG_AppAmnt				'Approved'
#DEFINE LANG_ApprAmount				'Approved amount'

