#DEFINE LANG_APBANK_BrowseTitle          'Bank'
#DEFINE LANG_APBANK_Account_BrowseTitle  'Chart of Accounts'
#DEFINE LANG_APBANK_Currency_BrowseTitle 'Currency'
#DEFINE LANG_APBANK_Bank_BrowseTitle     'Banks'
#DEFINE LANG_APBANK_Mover_Text           'Select Safe Users'
#DEFINE LANG_APBANK_Empty_Checks         'You have to enter at least one checking account.'
#DEFINE LANG_APBANK_No_GL_Account        'You have to enter GL Cash account.'
#DEFINE LANG_APBANK_Adjustment_Amount    'Adjustment amount must be greater than zero.'

#DEFINE LANG_APBANK_Default_Bank         'You cannot delete default bank.'
#DEFINE LANG_APBANK_Default_ChkAccount   'You cannot remove the default checking account.'
#DEFINE LANG_APBANK_Empty_Bank           'You have to enter the bank code.'